<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('DDS::dds_form_headline')?></h2>
    <?=$this->flashmessages()?>
    <form method="post" action="<?=$this->url('dds-email')?>" name="docdelisForm">
      <? if ($this->department): ?>
        <input type="hidden" name="subito[hdepartment]" value="<?=$this->department?>"/>
      <? endif; ?>
      <fieldset>
        <legend><?=$this->transEsc("DDS::dds_form_delivery_data")?>:</legend>
        <!-- name -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="" for="sname"><?=$this->transEsc("Name")?>:*</label>
          </div>
            <? if (isset($this->error->username)): ?>
              <div class="medium-9 columns error-field">
                <?=$this->error->username;?>
              </div>
            <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sname" name="subito[username]" class="w-100" <?=(!empty($this->username) ? 'value="' . $this->username . '"' : '')?>/>
          </div>
        </div>
        <!-- phone -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sphone"><?=$this->transEsc("DDS::form_field_phone")?>:</label>
          </div>
          <? if (isset($this->error->phone)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->phone;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sphone" name="subito[phone]" class="w-100" <?=(!empty($this->phone) ? 'value="' . $this->phone . '"' : '')?>/>
          </div>
        </div>
        <!-- email -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="semail"><?=$this->transEsc("DDS::form_field_email")?>:*</label>
           </div>
            <? if (isset($this->error->email)): ?>
              <div class="medium-9 columns error-field">
                <?=$this->error->email;?>
              </div>
            <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="semail" name="subito[email]" class="w-100" <?=(!empty($this->email) ? 'value="' . $this->email . '"' : '')?>/>
          </div>
        </div>
        <!-- user id -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="suserid"><?=$this->transEsc("DDS::form_field_library_id")?>:*</label>
          </div>
          <? if (isset($this->error->userid)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->userid;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="suserid" name="subito[userid]" class="w-100" <?=(!empty($this->userid) ? 'value="' . $this->userid . '"' : '')?>/>
          </div>
        </div>
        <!-- division -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sdivision"><?=$this->transEsc("DDS::form_field_division")?>:*</label>
          </div>
          <? if (isset($this->error->division)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->division;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <select id="sdivision" name="subito[division]" size="1" class="w-100"/>
            <option value=""></option>
            <? foreach ($this->divisions as $cat => $division): ?>
              <option value="<?=$cat?>" <?=($this->division == $cat) ? 'selected="selected"' : ''?>><?=$division?></option>
            <? endforeach; ?>
            </select>
          </div>
        </div>
        <!-- department -->
        <div class="row input-sdepartment">
          <div class="medium-3 columns">
            <label class="inline" for="sdepartment"><?=$this->transEsc("DDS::form_field_department")?>:*</label>
          </div>
          <? if (isset($this->error->department)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->department;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <select id="sdepartment" name="subito[department]" size="1" class="w-100"/>
            <option value=""></option>
            </select>
          </div>
        </div>
        <!-- department medicine -->
        <div class="row input-department">
          <div class="medium-3 columns">
            <label class="inline" for="smdepartment"><?=$this->transEsc("DDS::form_field_department")?>:*</label>
          </div>
          <div class="medium-9 columns">
            <input type="text" id="smdepartment" name="subito[inputdepartment]" class="w-100" <?=(!empty($this->inputdepartment) ? 'value="' . $this->inputdepartment . '"' : '')?>/>
          </div>
        </div>
      </fieldset>


      <fieldset>
        <legend><?=$this->transEsc("DDS::dds_form_details_ordered_title")?>:</legend>

        <!-- author -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sauthor"><?=$this->transEsc("DDS::form_field_author")?>:*</label>
          </div>
          <? if (isset($this->error->author)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->author;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sauthor" name="subito[author]" class="w-100" <?=(!empty($this->author) ? 'value="' . $this->author . '"' : '')?>/>
          </div>
        </div>
        <!-- title of issue -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sarticle"><?=$this->transEsc("DDS::form_field_title")?>:</label>
          </div>
          <? if (isset($this->error->article)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->article;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sarticle" name="subito[article]" class="w-100" <?=(!empty($this->article) ? 'value="' . $this->article . '"' : '')?>/>
          </div>
        </div>
        <!-- title of journal -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sjournal"><?=$this->transEsc("DDS::form_field_journal")?>:*</label>
          </div>
          <? if (isset($this->error->journal)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->journal;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sjournal" name="subito[journal]" class="w-100" <?=(!empty($this->journal) ? 'value="' . $this->journal . '"' : '')?>/>
          </div>
        </div>
        <!-- issn -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sjournal"><?=$this->transEsc("ISSN")?>:</label>
        </div>
          <? if (isset($this->error->issn)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->issn;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="sissn" name="subito[issn]" class="w-100" <?=(!empty($this->issn) ? 'value="' . $this->issn . '"' : '')?>/>
          </div>
        </div>
        <!-- publish date -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="spublishdate"><?=$this->transEsc("DDS::form_field_publishing_date")?>:*</label>
          </div>
          <? if (isset($this->error->publishdate)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->publishdate;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="spublishdate" name="subito[publishdate]" class="w-100" <?=(!empty($this->publishdate) ? 'value="' . $this->publishdate . '"' : '')?>/>
          </div>
        </div>
        <!-- journal number -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="snumber"><?=$this->transEsc("DDS::form_field_volume")?>:*</label>
          </div>
          <? if (isset($this->error->number)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->number;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="snumber" name="subito[number]" class="w-100" <?=(!empty($this->number) ? 'value="' . $this->number . '"' : '')?>/>
          </div>
        </div>
        <!-- pages -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="spages"><?=$this->transEsc("DDS::form_field_pages")?>:*</label>
          </div>
          <? if (isset($this->error->pages)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->pages;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <input type="text" id="spages" name="subito[pages]" class="w-100" <?=(!empty($this->pages) ? 'value="' . $this->pages . '"' : '')?>/>
          </div>
        </div>
        <!-- remarks -->
        <div class="row">
          <div class="medium-3 columns">
            <label class="inline" for="sremarks"><?=$this->transEsc("DDS::form_fields_remarks")?>:</label>
          </div>
          <? if (isset($this->error->remarks)): ?>
            <div class="medium-9 columns error-field">
              <?=$this->error->remarks;?>
            </div>
          <? endif; ?>
          <div class="medium-9 columns">
            <textarea id="sremarks" name="subito[remarks]" class="w-100"><?=(!empty($this->remarks) ? $this->remarks : '')?></textarea>
          </div>
        </div>
        <div class="row">
          <div class="medium-9 columns medium-offset-3">
            <input role="button" type="submit" class="button small" value="<?=$this->transEsc("DDS::form_button_submit")?>"/>
          </div>
        </div>
      </fieldset>
    </form>
    <div class="subito-pg">
      <?=$this->transEsc("DDS::dds_text_questions")?>
      <a href="mailto:info@ub.uni-leipzig.de?subject=<?=$this->transEsc("Dokumentenlieferdienst")?>">info@ub.uni-leipzig.de</a>
    </div>

    <div class="input-department subito-pg">
      <div><?=$this->transEsc("Bei eventuellen Rückfragen wenden Sie sich bitte an die Abteilung Fernleihe der Medizin")?>:</div>
      <div><?=$this->transEsc("Phone")?>: +49 (0)341 - 97 14014</div>
      <div><?=$this->transEsc("Email")?>: <a href="mailto:zbmed.fernleihe@medizin.uni-leipzig.de?subject=<?=$this->transEsc("Dokumentenlieferdienst")?>">zbmed.fernleihe@medizin.uni-leipzig.de</a></div>
    </div>
    <div class="subito-pg">
      <p class="required">
        * <?=$this->transEsc("DDS::dds_text_mandatory_fields")?></p>
    </div>
  </div>
</div>
<?
$this->inlineScript()->captureStart();
echo <<<JS
  $(document).ready(function(){
        // if department already selected and post request failed then
        // rebuild select menu
        if ( $('input:hidden[name="subito\\[hdepartment\\]"]').val() != 'undefined') {
            department.addDepartmentSelect(
                    $('input[name="subito\\[hdepartment\\]"]').val(),
                    $('select[name="subito\\[division\\]"]').val()
            );
        }
        $('select[name="subito\\[division\\]"]').change(function() {
            department.init($(this).val());
        });
        $('.row input').focus(function() {
            $(this).parent().prev('.error-field').hide(200);
        });
        $('.forme-group select').focus(function() {
            $(this).parent().prev('.error-field').hide(200);
        });
        /*if ( $('#loginOptions a.login').length ) {
            var loginUrl = {
              followup: true,
              followupModule: 'Subito',
              followupAction: 'Subito'
            };
            $('#loginOptions a.login').attr('href', function ( index, value ) {
                return value + '?' + $.param( loginUrl );
            });
            // console.log($('#loginOptions a.login').attr('href'));
        }*/
    });
/**
* Show & hide of subito form elements regarding select menu status.
* Add options for department select menu
*
* @author Frank Morgner<morgnerf@ub.uni-leipzig.de>
* @see https://katalog.ub.uni-leipzig.de/Subito/Subito
**/

var department = {
    init: function ( divisionid ) {
        addOptions = false;
        var elements = [];
        if ( divisionid == '15') {
            elements = {
                "department":"show",
                "costcentre":"show",
                "sdepartment":"hide"
            }
        } else if (divisionid == '') {
            elements = {
                "department":"hide",
                "costcentre":"hide",
                "sdepartment":"hide"
            }
        } else {
            elements = {
                "department":"hide",
                "costcentre":"hide",
                "sdepartment":"show"
            }
            var addOptions = true;
        }
        department.showHideElements(elements);
        if (addOptions == true) {
            department.addDepartmentOptions( divisionid );
        }
    },
    addDepartmentOptions: function ( divisionid ) {
        $('select[name="subito\\[department\\]"]').empty();
        var departments = $this->departments;
        department.addOptionElement('','');
        $.each(departments[divisionid], function (index, value) {
            department.addOptionElement(value,index);
        });
    },
    addDepartmentSelect: function (departmentid, divisionid) {
        department.init ( divisionid );
        department.addSelectElement ( departmentid );
    },
    addOptionElement: function ( text, value ) {
        jQuery('<option/>', {
                text: department.htmlEntitiesDecode(text),
                value: value
        }).appendTo('select[name="subito\\[department\\]"]');
    },
    addSelectElement: function ( departmentid )  {
        $('select[name="subito\\[department\\]"] option').filter(function () {
            //console.log($(this).val() + ' == ' + departmentid);
            return $(this).val() == departmentid;
        }).prop('selected', true);
    },
    htmlEntitiesDecode: function ( value ) {
        if (value) {
            return jQuery('<div/>').html(value).text();
        }
        return value;
    },
    showHideElements: function ( elements ) {
        $.each(elements, function (index, value) {
            if (value == 'show') {
                $('.input-' + index).show(200);
            }
            if (value == 'hide') {
                $('.input-' + index).hide(200);
            }
        });
    }
}
JS;
$this->inlineScript()->captureEnd();

echo $this->inlineScript();
?>