<? 
    $status = isset($row['status']) ? strtolower($row['status']) : 'unknown';
    $duedate = isset($row['duedate']) ? $row['duedate'] : '';
    $message = '';
    if (is_array($row['message']) && array_key_exists('en', $row['message'])) {
        $message = isset($row['message'][$this->layout()->userLang]) ? $row['message'][$this->layout()->userLang] : $row['message']['en'];
    }
    
    $class = 'text-success';
    $icon = 'fa-check';
   
    if ($status == 'on loan' || $status == 'permanent on loan' || $status == 'unavailable') {
        $class = "text-danger";
        $icon = 'fa-times';
    }
        
    $isStorageReadingroom = strpos($row['location'],'Lesesaal');
?>
<tr>
    <td>        
    <? if (isset($row['callnumber']) && $row['callnumber'] != 'Unknown'): ?>
        <?=$this->escapeHtml($row['callnumber'])?>
    <? endif; ?>
    </td>
    <? if (is_array($row['message'])): ?>
        <td class="<?=$this->escapeHtmlAttr($class)?>">
            <i class="fa <?=$this->escapeHtmlAttr($icon)?>"></i>
            <?=$this->escapeHtml($message)?>            
        </td>
    <? endif; ?>
    <td>
        <? if($status == 'on loan' && !empty($duedate)): ?>
            <?=$this->transEsc('Due')?> <?=$this->escapeHtml($duedate)?>
            <? if ( !empty($row['link']) && !$this->client()->is('only_one_holds_button') ): ?>
                &ndash; <a href="<?=$row['link']?>" class="<? if (!$this->client()->is('koha_link')):?>modal-link modal-remote <? endif; ?> external"><?=$this->transEsc('Recall This')?></a>
            <? endif; ?>
        <? elseif($status == 'unavailable'): ?>
            <?=$this->transEsc('daia-'.strtolower($row['status']))?>
            <? if (!empty($row['link']) && !$this->client()->is('only_one_holds_button') ): ?>
                &ndash; <a href="<?=$row['link']?>" class="<? if (!$this->client()->is('koha_link')):?>modal-link modal-remote <? endif; ?> external"><?=$this->transEsc('Recall This')?></a>
            <? endif; ?>
        <? else: ?>
            <?=$this->transEsc('daia-'.strtolower($row['status']))?>
            <? if (!empty($row['link']) && !$this->client()->is('only_one_holds_button') && $this->client()->is('always_place_hold') && ( $status != 'for reference') || $this->client()->is('show_readingroom_link') && !$isStorageReadingroom  ) : ?>
                &ndash; <a href="<?=$row['link']?>" class="<? if (!$this->client()->is('koha_link')):?>modal-link modal-remote <? endif; ?> external"><?=$this->transEsc('Place a Hold')?></a>
            <? endif; ?>            
        <? endif; ?>
    </td>
    
</tr>

