<? $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>

<tr>
  <th><?=$this->transEsc("Call Number")?>: </th>
  <td width="50%">
    <? foreach ($callNos as $callNo): ?>
      <? if ($this->callnumberHandler): ?>
        <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
      <? else: ?>
        <?=$this->escapeHtml($callNo)?>
      <? endif; ?>
      <br />
    <? endforeach; ?>
  </td>
</tr>

<? endif; ?>
<tr>
    <th><?=$this->transEsc('Fernleihindikator')?></th>
    <td><?=$this->transEsc($row['availability'])?></td>
</tr>