<?php $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
<tr>
  <th><?=$this->transEsc("Call Number")?>: </th>
  <td width="50%">
    <?php foreach ($callNos as $callNo): ?>
      <?php if ($this->callnumberHandler): ?>
        <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
      <?php else: ?>
        <?=$this->escapeHtml($callNo)?>
      <?php endif; ?>
      <br />
    <?php endforeach; ?>
  </td>
</tr>
<?php endif; ?>
<?php if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
  <tr>
    <?php // Translation for summary is a special case for backwards-compatibility?>
    <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
    <td>
      <?php foreach ($textFields as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <?php endforeach; ?>
    </td>
  </tr>
<?php endforeach; endif; ?>
<?php foreach ($holding['items'] as $row): ?>
<?php // AJAX Check record?
$check = isset($row['check']) && $row['check'];
$checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
$checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
?>
<?php if (isset($row['barcode']) && $row['barcode'] != ""): ?>
<tr vocab="http://schema.org/" typeof="Offer">
  <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
  <td>
    <?php if ($row['reserve'] == "Y"): ?>
      <link property="availability" href="http://schema.org/InStoreOnly" />
      <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
    <?php endif; ?>
    <?php if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
      <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
    <?php else: ?>
      <?php if ($row['availability']): ?>
        <?php /* Begin Available Items (Holds) */ ?>
         <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
        <?php if (isset($row['link']) && $row['link']): ?>
          <a class="<?=$check ? 'checkRequest ' : ''?>placehold" <?php if (!empty($row['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
        <?php endif; ?>
        <?php if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
          <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
        <?php endif; ?>
        <?php if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
          <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
        <?php endif; ?>
      <?php else: ?>
        <?php /* Begin Unavailable Items (Recalls) */ ?>
        <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
        <?php if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><?php endif; ?>
        <?php if (isset($row['duedate']) && $row['duedate']): ?>
          &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
        <?php endif; ?>
        <?php if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
          <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
        <?php endif; ?>
        <?php if (isset($row['link']) && $row['link']): ?>
          <a class="<?=$check ? 'checkRequest' : ''?> placehold" <?php if (!empty($row['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($row['item_notes'])): ?>
        <div class="item-notes">
          <b><?=$this->transEsc("Item Notes")?>:</b>
          <ul>
            <?php foreach ($row['item_notes'] as $item_note): ?>
              <li><?=$this->escapeHtml($item_note) ?></li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php /* Embed item structured data: library, barcode, call number */ ?>
    <?php if ($row['location']): ?>
      <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
    <?php endif; ?>
    <?php if ($row['barcode']): ?>
      <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
    <?php endif; ?>
    <?php if ($row['callnumber']): ?>
      <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
    <?php endif; ?>
    <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
      <link property="itemOffered" href="#record" />
  </td>
</tr>
<?php endif; ?>
<?php endforeach; ?>
