<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */


// Hide the total result count -- because of limitations in the way facet
    // paging works, we can't actually determine an accurate total count.  (Note
    // that this setting simply modifies the behavior of search/results.phtml below).
    $this->skipTotalCount = true;

    // Load standard settings from the default search results screen:
    echo $this->render('search/results.phtml');

    // Override some details...

    // Set up page title:
    $this->headTitle($this->translate('Author Browse'));

    // Set up empty search box pointing at Solr module:
    $this->layout()->searchbox = $this->context($this)->renderInContext('search/searchbox.phtml', ['searchClassId' => 'Solr']);

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('author-home') . '">' . $this->transEsc('Author') . '</a></li> '
         . '<li class="active">' . $this->transEsc('Author Results for') . ' ' . $this->escapeHtml($this->params->getDisplayQuery()) . '</li>';
?>
