<?php if ($this->client()->is('disable_footer')):
    $colwidth = 'col-sm-12';
else:
    $colwidth = 'col-sm-3';
endif; ?>
<?php if (!$this->client()->is('disable_footer') || $boxNo === 3): ?>
    <?php $links = $this->client()->getFooterLinks($boxNo); ?>
    <div class="<?= $colwidth ?>">
        <div class="well">
            <p><strong><?= $heading ?></strong></p>
            <?php if (count($links) > 0): ?>
                <ul>
                    <?php foreach ($links as $k => $link): ?>
                        <?php $external = false;
                        if ($boxNo == 3 && $k == count($links) - 1) {
                            $translation = 'Privacy';
                        } else {
                            $translation = 'footer_box_' . $boxNo . '_' . ($k + 1);
                        }
                        if (strpos($link, '://') !== false):
                            $external = true;
                            $url = $link;
                        elseif (strpos($link, '/') !== false):
                            $url = $link;
                        elseif ($link == 'bsz-privacy'):
                            $external = true;
                            $url = 'https://elib.dlr.de/datenschutz.html';
                        else:
                            $url = $this->url($link);
                        endif; ?>
                        <li><a href="<?= $url ?>"
                               class="<?= $external ? 'external' : 'internal' ?>"><?= $this->transEsc($translation) ?></a>
                        </li>
                    <?php endforeach; ?>
                    <?php if ($boxNo == 3 && $this->client()->is('help_link')): ?>
                        <li><a class="internal help-link"
                               href="<?= $this->url('help-home') ?>?topic=search"><?= $this->transEsc('Hilfe zu den Suchoperatoren') ?></a>
                        </li>
                    <?php endif; ?>
                </ul>
            <?php endif; ?>
            <div class="nofloat"></div>
        </div>
    </div>
<?php endif; ?>