<?php // This is a text-only email template; do not include HTML! ?>

<?=$this->client()->get('Site')->get('title')?>
------------------------------------------------------------
  <?=$this->driver->getBreadcrumb()?>

  <?=$this->driver->getPrimaryAuthor()?>

  <?=$this->driver->getCleanISBN() ?? $this->driver->getCleanISSN() ?>

  <?=$this->translate('email_link')?>: <?=$this->serverUrl($this->recordLink()->getUrl($this->driver))?>

------------------------------------------------------------
<?php if (!empty($this->message)): ?><?=$this->translate("Message From Sender")?>:
<?=$this->message?>
<?php endif; ?>

