<!-- finc:- recommend - sidefacets -->
<?
$this->headScript()->appendFile('facets.js');

$results = $this->recommend->getResults();
$options = $this->searchOptions($this->searchClassId);
?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets();
if (count($checkboxFilters) > 0): ?>
  <?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if ($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown++;
    }
    $html .= '"><input type="checkbox" name="filter[]" value="' . $this->escapeHtmlAttr($current['filter']) . '"
      ' . ($current['selected'] ? 'checked="checked"' : '') . ' id="' . $this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])) . '"
      onclick="document.location.href=\'' . ($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])) . '\';" />' . $this->transEsc($current['desc']) . '</label>';
  }
  ?>
  <div class="checkboxFilter<? if ($shown == 0): ?> hidden<? endif; ?>"><?=$html?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters);
if (!empty($filterList)): ?>
  <div class="list-group filters">
    <div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
        $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
        if ($index !== false) {
          unset($collapsedFacets[$index]); // Open if we have a match
        }
        if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->replaceTerm($filter['value'], '');
        } else {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
        }
        if ($filter['displayText'] == '[* TO *]') {
          $filter['displayText'] = $this->translate('filter_wildcard');
        }
        ?>
        <? /* use tooltip toggler in finc, CK */ ?>
        <a class="list-group-item active" href="<?=$removeLink?>" data-toggle="tooltip" title="<?=$this->transEsc('clear_tag_filter')?>">
          <span class="pull-right flip"><i class="fa fa-minus-square-o" aria-hidden="true"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' ';
          if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
<?=isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : ''?>
<? /* finc-specific: sidefacet()->displayAllowedFacetValues, #7624 - CK*/ ?>
<? $sideFacetSet = $this->sidefacet()->displayAllowedFacetValues($this->recommend->getFacetSet());
$rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <? $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>
    <? $showMoreInLightbox = $this->recommend->getShowInLightboxSetting($title); ?>
    <div class="list-group facet" id="side-panel-<?=$this->escapeHtmlAttr($title)?>">
      <? /* Fix in all instance branches to avoid validation error 'href not allowed on div'; CK */ ?>
      <a class="list-group-item title<? if (in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title)?>">
        <?=$this->transEsc($cluster['label'])?>
      </a>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title)?>" class="collapse<? if (!in_array($title, $collapsedFacets)): ?> in<? endif ?>">
        <? if (isset($rangeFacets[$title])): ?>
        <div class="list-group-item">
          <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
            <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
            <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
            <div class="row">
              <? $extraInputAttribs = ($rangeFacets[$title]['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
              <div class="col-sm-6">
                <label for="<?=$this->escapeHtmlAttr($title)?>from">
                  <?=$this->transEsc('date_from')?>:
                </label>
                <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from"
                       value="<?=isset($rangeFacets[$title]['values'][0]) ? $this->escapeHtmlAttr($rangeFacets[$title]['values'][0]) : ''?>" <?=$extraInputAttribs?>/>
              </div>
              <div class="col-sm-6">
                <label for="<?=$this->escapeHtmlAttr($title)?>to">
                  <?=$this->transEsc('date_to')?>:
                </label>
                <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to"
                       value="<?=isset($rangeFacets[$title]['values'][1]) ? $this->escapeHtmlAttr($rangeFacets[$title]['values'][1]) : ''?>" <?=$extraInputAttribs?>/>
              </div>
            </div>
            <? if ($rangeFacets[$title]['type'] == 'date'): ?>
              <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
            <? endif; ?>
            <input class="btn btn-transparent" type="submit" value="<?=$this->transEsc('Set')?>"/>
          </form>
        </div>
        <? if ($rangeFacets[$title]['type'] == 'date'): ?>
        <? $this->headScript()->appendFile('vendor/bootstrap-slider.js'); ?>
        <? $this->headLink()->appendStylesheet('vendor/bootstrap-slider.min.css'); ?>
        <?
        $min = !empty($rangeFacets[$title]['values'][0]) ? min($rangeFacets[$title]['values'][0], 1400) : 1400;
        $future = date('Y', time() + 31536000);
        $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, $rangeFacets[$title]['values'][1]) : $future;
        $low = !empty($rangeFacets[$title]['values'][0]) ? $rangeFacets[$title]['values'][0] : $min;
        $high = !empty($rangeFacets[$title]['values'][1]) ? $rangeFacets[$title]['values'][1] : $max;
        $reversed = $this->layout()->rtl ? 'true' : 'false';
        $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
  .slider({
     'min':{$min},
     'max':{$max},
     'handle':"square",
     'tooltip':"hide",
    'value':[{$low},{$high}],
    'reversed': {$reversed}
  })
  .on('change', fillTexts)
  .data('slider');
});
// finc: Update slider handle position with input date - CK (adapted from search - advanced - ranges
$('#{$this->escapeHtmlAttr($title)}from, #{$this->escapeHtmlAttr($title)}to').change(function () {
  var from = Number($('#{$this->escapeHtmlAttr($title)}from').val());
  var to   = Number($('#{$this->escapeHtmlAttr($title)}to').val());
  if (from <= 0) {
    from = {$min};
  }
  if (to <= 0) {
    to = {$max};
  }
  $('#{$this->escapeHtmlAttr($title)}dateSlider').slider('setValue', [from, to], true);
});
JS;
        ?>
        <?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <? endif; ?>
        <? else: ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
        <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
        <? if (!in_array($title, $collapsedFacets)): ?>
        <?
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
        ?>
        <?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <? else: ?>
        <?
        $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
        ?>
        <?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <? endif; ?>
        <li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
            data-facet="<?=$this->escapeHtmlAttr($title)?>"
            data-path="<?=$this->currentPath()?>"
            data-exclude="<?=$allowExclude?>"
            data-operator="<?=$this->recommend->getFacetOperator($title)?>"
            data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
            data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
        </li>
        <noscript>
          <? endif; ?>
          <? foreach ($cluster['list'] as $i => $thisFacet): ?>
                  <?
                  if (strlen($thisFacet['displayText']) == 0) {
                    $thisFacet['displayText'] = "-";
                  }
                  ?>
              <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
                  <? if ($i == $facets_before_more): ?>
              <? $idAndClass = 'id="more-narrowGroupHidden-'.$this->escapeHtmlAttr($title).'" class="list-group-item narrow-toggle"'; ?>
              <? if ($facetLightbox = $options->getFacetListAction()): ?>
                <? $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams().'&amp;facet='.$title.'&amp;facetop='.$thisFacet['operator'].'&amp;facetexclude='.($allowExclude ? 1 : 0); ?>
              <? else: ?>
                <? $moreUrl = '#'; ?>
              <? endif; ?>
              <? if (($showMoreInLightbox && $showMoreInLightbox !== 'more') && $facetLightbox): ?>
                <a <?=$idAndClass ?> data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('more')?> ...</a>
                <? break; ?>
              <? else: ?>
                <a <?=$idAndClass ?> href="<?=$moreUrl ?>" onclick="return moreFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')" rel="nofollow"><?=$this->transEsc('more')?> ...</a>
              <? endif; ?>
                  <? endif; ?>
                  <? if ($thisFacet['isApplied']): ?>
              <a class="list-group-item active<? if ($i >= $facets_before_more): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>" title="<?=$this->transEsc('applied_filter') ?>">
                        <? if ($thisFacet['operator'] == 'OR'): ?>
                  <i class="fa fa-check-square-o" aria-hidden="true"></i>
                        <? else: ?>
                  <span class="pull-right flip"><i class="fa fa-check" aria-hidden="true"></i></span>
                        <? endif; ?>
                        <?= $this->escapeHtml($thisFacet['displayText']) ?>
                      </a>
                  <? else: ?>
                    <? $addURL = $this->currentPath() . $results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
                    <? if ($allowExclude): ?>
                <div class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
                    <? else: ?>
                <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
                        <? endif; ?>

                <? /* Fixme: Is this correct? - CK */ ?>
                <? /* Finc-specific: make click on found items number select facet, like facet-title - CK */ ?>
              <span class="badge">
                <? if ($allowExclude): ?>
                  <a href="<?= $addURL ?>" class="badge-result-count"><?= $this->localizedNumber($thisFacet['count']) ?></a>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-minus-square-o" aria-hidden="true"></i></a>
                <? else: ?>
                  <?= $this->localizedNumber($thisFacet['count']) ?>
                <? endif; ?>
              </span>
             <? /* Fixme END - CK */ ?>

                    <? if ($allowExclude): ?>
                    <a href="<?= $addURL ?>">
                  <? endif; ?>
                    <? if ($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-square-o" aria-hidden="true"></i>
                    <? endif; ?>
                    <?= $this->escapeHtml($thisFacet['displayText']) ?>
              <? if ($allowExclude): ?>
                    </a>
                </div>
              <? else: ?>
                </a>
              <? endif; ?>
                  <? endif; ?>
                <? endforeach; ?>
          <? if ($showMoreInLightbox === 'more' && $facetLightbox = $options->getFacetListAction()): ?>
            <? $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams().'&amp;facet='.$title.'&amp;facetop='.$thisFacet['operator'].'&amp;facetexclude='.($allowExclude ? 1 : 0); ?>
            <a class="list-group-item narrow-toggle <?=$moreClass ?>" data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('see all')?> ...</a>
          <? endif; ?>
          <? if ($i >= $facets_before_more): ?><a class="list-group-item narrow-toggle <?=$moreClass ?>" href="#" onclick="return lessFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
          <? endif; ?>
          <? if (in_array($title, $hierarchicalFacets)): ?>
        </noscript>
        <? endif; ?>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!-- finc: recommend - sidefacets - END -->
