<!-- search - controls - LIMIT.phtml -->
<? $limitList = $this->params->getLimitList(); ?>
<? if (count($limitList) > 1): ?>
  <? /* Do not use form-inline as it messes up the select box */ ?>
  <form class="limit" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" method="post">
    <label for="limit"><?=$this->transEsc('Results per page')?></label>
    <? /* Do not use form-control as it messes up the select box */ ?>
    <select id="limit" name="limit" class="jumpMenu">
      <? foreach ($limitList as $limitVal => $limitData): ?>
        <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
<!-- search - controls - LIMIT.phtml - end -->
