<!-- finc: search - advanced - limit -->
<? /* BS version has error in line 16 -- space missing before 'selected' - throws w3c error - CK  */ ?>
<?
// Set up convenience variables:
$limitList = $this->options->getLimitOptions();

// If a previous limit was used, make that the default; otherwise, use the "default default"
$lastLimit = $this->searchMemory()->getLastLimit($this->options->getSearchClassId());
$defaultLimit = empty($lastLimit) ? $this->options->getDefaultLimit() : $lastLimit;
?>
<? if (count($limitList) > 1): ?>
  <fieldset class="limits">
    <legend><?=$this->transEsc('Results per page')?></legend>
    <select id="limit" name="limit" class="form-control">
      <? foreach ($limitList as $limitVal): ?>
        <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=($limitVal == $defaultLimit) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($limitVal)?></option>
      <? endforeach; ?>
    </select>
  </fieldset>
<? endif; ?>
<!-- finc: search - advanced - limit - END -->
