<!-- search - controls - LIMIT.phtml -->
<? $limitList = $this->params->getLimitList(); ?>
<? if (count($limitList) > 1): ?>
  <form class="limit" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" method="post">
    <div class="row">
      <div class="small-5 columns">
        <label class="right inline" for="limit"><?=$this->transEsc('Results per page')?></label>
      </div>
      <div class="small-7 columns">
        <select id="limit" name="limit" class="jumpMenu">
          <? foreach ($limitList as $limitVal => $limitData): ?>
            <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
    <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
<!-- search - controls - LIMIT.phtml - end -->