<? 
  $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('dedup_settings') . '</li>';
  $this->headTitle()->setPrefix($this->transEsc('Privacy'));
?>
<?=$this->flashmessages()?>
<div class="col-sm-6">
    
    <h1><?=$this->transEsc('dedup_settings')?></h1>
    <p><?=$this->transEsc('dedup_settings_text')?></p>
    
    <form method="POST" action="#"  class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-sm-8"><?=$this->transEsc('dedup_settings_switch')?></label>
            <div class="col-sm-4">
                <div class="checkbox">
                    <input type="checkbox" name="dedup_status" value="1" />
                </div>                
            </div>         
            
        </div>
        <div class="form-group">        
            <div class="col-sm-offset-8 col-sm-4">
              <button type="submit" class="btn btn-primary"><?=$this->transEsc('Submit')?></button>
            </div>
        </div>
        
    </form>
    

</div>

