<?php if ($this->client()->is('disable_footer')):
 $colwidth = 'col-sm-12';
else:
 $colwidth = 'col-sm-4';
endif;?>
<?php if (!$this->client()->is('disable_footer') || $boxNo === 3): ?>
  <?php $links = $this->client()->getFooterLinks($boxNo); ?>
  <div class="<?=$colwidth?>">
    <div class="well">          
        <h5><?=$heading?></h5>
    <?php if ($links): ?>
    <ul>
        <?php foreach ($links as $k => $link): ?>
            <?php $external = false;
            if ($boxNo == 3 && $k == count($links) - 1) {
                $translation = 'Privacy';
            } else {
                $translation = 'footer_box_' . $boxNo . '_' . ($k + 1);
            }
            if (strpos($link, '://') !== false):
                $external = true;
                $url = $link;
            elseif (strpos($link, '/') !== false):
                $url = $link;
            else:
                $url = $link;
                //$url = $this->url($link);
            endif; ?>
            
            <li><a href="<?=$url?>" class="<?= $external ? 'external' : 'internal'?>" <?= $external ? 'target="boss"' : ''?>><?=$this->transEsc($translation)?></a></li>
        <?php endforeach; ?>
        <?php if ($boxNo == 3 && $this->client()->is('help_link')): ?>
        <li><a class="internal help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search"><?=$this->transEsc('Help with Search Operators')?></a></li>
        <?php elseif ($boxNo == 3 && $this->client()->is('help_link_advanced')): ?>
        <li><a class="internal help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=advsearch"><?=$this->transEsc('Help with Advanced Search')?></a></li>
        <?php endif; ?>
    </ul>
  <?php endif; ?>
  <div class="nofloat"></div>
    </div>
  </div>
  <?php endif; ?>