<?php
$this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('ILL::Resigning') . '</li>';

$this->headTitle()->setPrefix($this->transEsc('ILL::Resigning'));
?>
<div class="col-sm-12">
    <h3><?=$this->transEsc('ILL::resigning_header')?></h3>
</div>
<div class="col-sm-12 col-md-8">

    <form class="form-horizontal" method="GET" action="<?=$this->url('search-results')?>">
        <input type="hidden" value="AND" name="join" />
        <input type="hidden" value="AND" name="bool0[]" />
        <input type="hidden" name="hiddenFilters[]" value="-consortium:FL" />
        <div class="form-group form-group-sm">
            <label class="control-label col-sm-4" for="network"><?=$this->transEsc('Network')?></label>
            <div class="btn-group col-sm-8" data-toggle="buttons" id="network">
                <?php foreach ($this->allNetworks as $name => $isil): ?>
                    <label class="btn btn-default <?php if(in_array($name, $this->selectedNetworks)):?>active<?php endif; ?>"><input type="checkbox" <?php if(in_array($name, $this->selectedNetworks)):?>checked="checked" <?php endif; ?>name="filter[]" value="~consortium:<?=$this->escapeHtml($isil)?>" autocomplete="off"><?=$this->escapeHtml($name)?></label>
                <?php endforeach; ?>
            </div>
        </div>

        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
                'title' => 'adv_search_title',
                'field'  => 'Title',
                'value'  => $this->params['titel'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
            'title' => 'adv_search_journaltitle',
            'field'  => 'JournalTitle',
            'value'  => $this->params['journaltitle'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
            'title' => 'adv_search_author',
            'field'  => 'Author',
            'value'  => $this->params['verfasser'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
            'title' => 'adv_search_publisher',
            'field'  => 'publisher',
            'value'  => $this->params['verlkag'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
            'title' => 'adv_search_isn',
            'field'  => 'ISN',
            'value'  => $this->params['isn'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
            'title' => 'adv_search_zdbid',
            'field'  => 'ZDB',
            'value'  => $this->params['zdb_id'] ?? ''])?>
        <?=$this->context($this)->renderInContext('bsz/input.phtml', [
        'title' => 'adv_search_year',
        'field'  => 'year',
        'value'  => $this->params['erscheinungsjahr'] ?? ''])?>

        <div class="form-group form-group-sm">
            <div class="col-sm-8 pull-right">
                <button class="btn clear-btn text-danger" type="reset" name="submit" value="<?=$this->transEsc('Submit')?>">
                    <i class="fa fa-times"></i>
                    <span class="text"><?=$this->transEsc('Clear')?></span>
                </button>

                <input class="btn btn-success" type="submit" name="submit" value="<?=$this->transEsc('Submit')?>" />
            </div>
        </div>
    </form>
</div>
<div class="col-sm-.12 col-md-4 ">
    Platz für Hilfetext
</div>
