<?php
$this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('ILL::Resigning') . '</li>';

$this->headTitle()->setPrefix($this->transEsc('ILL::Resigning'));
?>
<div class="col-sm-12 col-md-6">
    <h3><?=$this->transEsc('ILL::resigning_header')?></h3>
    <form class="form-horizontal" method="GET" action="<?=$this->url('search-results')?>">
        <input type="hidden" value="AND" name="join" />
        <input type="hidden" value="AND" name="bool0[]" />

        <div class="form-group form-group-sm">
            <label class="control-label col-sm-6" for="ill-title"><?=$this->transEsc('Titel')?></label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="ill-title" value="" name="lookfor0[]"/>
                <input type="hidden" value="Title" name="type0[]" />
            </div>
        </div>

        <div class="form-group form-group-sm">
            <label class="control-label col-sm-6" for="ill-author"><?=$this->transEsc('Author')?></label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="ill-author" value="" name="lookfor0[]"/>
                <input type="hidden" value="Author" name="type0[]" />
            </div>
        </div>
        <div class="form-group form-group-sm">
            <div class="col-sm-6 pull-right">
                <input class="btn btn-success" type="submit" name="submit" value="<?=$this->transEsc('Submit')?>" />
            </div>
        </div>
    </form>
</div>
