<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

$this->headTitle($this->translate('Libraries') . ': ' . $this->driver->getBreadcrumb());
$content = $this->tab->getContent();
$fulltext_key = $this->driver->isFree() ? 'Volltext_frei' : 'Volltext';
?>

<?php if (isset($content) && count($content) > 0): ?>

    <table class="table table-striped table-condensed tablesorter">
        <thead>
        <tr>
            <th class="col-sm-1 col-xs-1 hidden-xs"><?= $this->transEsc('Contact') ?></th>
            <th><?= $this->transEsc('Library') ?></th>
            <th><?= $this->transEsc('access_column_heading') ?></th>
            <?php if ($this->client()->is('show_ill_column')): ?>
                <th class="col-sm-2 col-xs-2 hidden-xs"><?= $this->transEsc('Interlibrary Loan') ?></th>
            <?php endif; ?>
            <?php if ($this->driver->isJournal()): ?>
                <th><?= $this->transEsc('Collection') ?></th><?php endif; ?>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($content as $result): ?>
            <tr>
                <td class="hidden-xs">
                    <?php if (isset($result['isil']) && trim($result['isil']) != ''): ?>
                        <?php if ($result['isil'] !== 'LFER'): ?>
                            <span class="text-nowrap">
                            <?php if (isset($result['homepage'])): ?>
                                <a data-toggle="tooltip"
                                   title="<?= $this->transEsc('ILL::library_homepage') ?>"
                                   href="<?= $result['homepage'] ?>"
                                   class="external hasicon"><i
                                            class="fa fa-globe"></i><?= $this->escapeHtml($result['isil']) ?></a>
                            <?php else: ?>
                                <?= $this->escapeHtml($result['isil']) ?>
                            <?php endif; ?>
                        </span>
                        <?php else: ?>
                            <?= $this->abbrev($result['isil'], 'LFER_long') ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?= isset($result['isil']) ? $this->escapeHtml($result['isil']) : '' ?>
                    <?php endif; ?>
                </td>

                <td>
                    <?php if (isset($result['opacurl']) && isset($result['name']) && trim($result['opacurl']) != '' && $this->driver->getNetwork() !== 'ZDB'): ?>
                        <?php $opac = preg_replace('/%PPN%/', $this->driver->getPPN(), $result['opacurl']) ?>
                        <a data-toggle="tooltip"
                           title="<?= $this->transEsc('ILL::library_opac') ?>"
                           href="<?= $opac ?>"
                           class="external hasicon">
                            <i class="fa fa-globe"></i><?= $this->escapeHtml($result['name']) ?>
                        </a>
                    <?php else: ?>
                        <?= isset($result['name']) ? $this->escapeHtml($result['name']) : '' ?>
                    <?php endif; ?>
                </td>

                <td>
                    <?php if (isset($result['k'])): ?>
                        <a href="<?= $result['k'] ?>" class="external"
                           target="_blank" data-toggle="tooltip"
                           title="<?= $this->transEsc('Fulltext') ?>"><?= $this->transEsc($fulltext_key) ?></a>
                    <?php else: ?>
                        <?php if (isset($result['opacurl']) && isset($result['name']) && trim($result['opacurl']) != '' && $this->driver->getNetwork() !== 'ZDB'): ?>
                            <?php $opac = preg_replace('/%PPN%/', $this->driver->getPPN(), $result['opacurl']) ?>
                            <a data-toggle="tooltip"
                               title="<?= $this->transEsc('ILL::library_opac') ?>"
                               href="<?= $opac ?>"
                               class="external hasicon">
                                <i class="fa fa-globe"></i>OPAC
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>

                <?php if ($this->client()->is('show_ill_column')): ?>
                    <td>
                        <?php if (isset($result['ill_icon'])): ?><i
                            class="fa <?= $result['ill_icon'] ?>"></i> <?php endif; ?>
                        <span
                                class="text hidden-xs"><?= isset($result['ill_status']) ? $this->transEsc($result['ill_status']) : '-' ?></span>
                    </td>
                <?php endif; ?>

                <?php if ($this->driver->isJournal()): ?>
                    <td><?= isset($result['issue']) ? $this->escapeHtml($result['issue']) : '' ?></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tablesorter').tablesorter({
                sortList: [[0, 0]]
            });
        });
    </script>
<?php else: ?>
    <p><?= $this->transEsc('nohit_heading') ?></p>
<?php endif; ?>
