<p>Using IREON, you can search within more than 1 million references from the WAO - World Affairs Online database and 4.4 million references from the ECONIS database</p>
<p>IREON contains references and access to online full-text documents, on:</p>

<p>
<ul>
    <li>Foreign and security policy</li>
    <li>Business administration, economics and business practice</li>
    <li>International cooperation and development policy</li>
    <li>European politics and transatlantic relations</li>
    <li>Regional and country studies worldwide</li>
    <li>Foreign cultural policy</li>
    <li>Climate, environment, energy</li>
</ul>
</p>
<p>IREON is operated by <a href="https://fiviblk.de/" target="_blank" class="external">FIV - The German Information Network for International Relations and Area Studies</a>.</p>

<p>All references are indexed with descriptors from the multilingual <a href="https://fiviblk.de/thesaurus/" target="_blank" class="external">European Thesaurus on International Relations and Area Studies</a> and/or from the STW Standard Thesaurus on Economics.</p>