<p>Über IREON können Sie in mehr als 1 Million Literaturnachweisen der Datenbank WAO
    – World Affairs Online und 4,4 Millionen Nachweisen aus der Datenbank ECONIS
    suchen.</p>
<p>IREON bietet Ihnen Literaturhinweise und elektronische Volltexte zu:</p>

<p>
<ul>
    <li> außen- und sicherheitspolitischen Themen</li>
    <li>Betriebswirtschaftslehre, Volkswirtschaftslehre und Wirtschaftspraxis</li>
    <li>Fragen der internationalen wirtschafts- und entwicklungspolitischen Zusammenarbeit</li>
    <li>europapolitischen und transatlantischen Themen</li>
    <li>regional- und länderbezogenen Fragen weltweit</li>
    <li>auswärtiger Kulturpolitik</li>
    <li>Klima, Umwelt und Energie</li>
</ul>
</p>

<p>Betreiber des Fachportals ist der <a href="https://fiviblk.de/" target="_blank" class="external">FIV – Fachinformationsverbund Internationale Beziehungen und Länderkunde</a>.</p>

<p>Alle Literaturhinweise sind mit Deskriptoren aus dem multilingualen <a href="https://fiviblk.de/thesaurus/" target="_blank" class="external">European Thesaurus on International Relations and Area Studies</a> und/oder aus aus dem STW - Standard Thesaurus Wirtschaft erschlossen.</p>