<?php $data = $this->recommend->getResults(); if (is_array($data)): ?>
    <div class="sidegroup rssResults">
        <div class="suggestionHeader">

            <h4><?= $this->transEsc($data['feedTitle']) ?></h4>

        </div>
        <div>
            <ul class="list-group">
                <?php $i = 0;
                foreach ($data['worksArray'] as $workKey => $work): ?>
                    <li class="list-group-item suggestedResult <?php (++$i % 2) ? 'alt ' : '' ?>record<?= $i ?>">
                        <? //xdebug_var_dump($data)?>
                        <div class="resultitem clearfix">
                            <a href="<?= $this->escapeHtmlAttr($work['link']) ?>"
                               class="external hasicon" target="_blank">
                                <span><?= $this->escapeHtml($this->truncate($work['title'], 90)) ?></span>
                            </a>
                            <?php if (isset($work['description'])): ?>
                                <?php // TODO: very dangerous, no escaping! ?>
                                <p><?= $work['description'] ?></p>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
            <p class="olSubjectMore">
                <a href="<?= $this->escapeHtmlAttr($data['sourceLink']) ?>"
                   title="<?= $this->escapeHtmlAttr($data['feedTitle']) ?>"
                   target="_blank">
                    <?= $this->transEsc('more') ?>...
                </a>
            </p>
        </div>
    </div>
    <div class="clearfix"></div>
<?php endif; ?>
