<?php $data = $this->recommend->getResults(); if (is_array($data)): ?>
    <h4><?= $this->transEsc($data['feedTitle']) ?></h4>
    <div class="panel-group">
        <?php foreach ($data['worksArray'] as $workKey => $work): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?= $this->escapeHtml($work['date']->format('d.m.Y h:m')) ?>
                    <strong><?= $this->escapeHtml($this->truncate($work['title'], 120)) ?></strong>
                </div>
                <div class="panel-body">
                    <?php if (isset($work['description'])): ?><?= $work['description'] ?><?php endif; ?>
                    <?php if (isset($work['link'])): ?>
                        <a href="<?= $this->escapeHtmlAttr($work['link']) ?>"
                           class="external hasicon"
                           target="_blank"><?= $this->transEsc('More Information') ?>
                            ></a>
                    <?php endif ?>
                    <?php if (isset($work['author'])): ?>
                        <p class="small"><?= implode(', ', $work['author']) ?></p>
                    <? endif ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <p class="olSubjectMore">
        <a href="<?= $this->escapeHtmlAttr($data['sourceLink']) ?>"
           title="<?= $this->escapeHtmlAttr($data['feedTitle']) ?>" target="_blank">
            <?= $this->transEsc('more') ?>...
        </a>
    </p>
<?php endif; ?>