<?php $url = $this->recommend->getURL();


$sourceTitle = $this->recommend->getSourceTitle();
$imageName = $this->recommend->getImageName();
$colNumber = $this->recommend->getColNumber();
$label = $this->recommend->getLabel();

?>
<?php if (!empty($url)): ?>
    <?php if (!empty($label)): ?>
        <div class="searchbuttonLabel h4 col-sm-12 col-md-12"><?= $this->transEsc('SearchButtons::' . $label) ?></div>
    <?php endif; ?>
    <div class="searchbutton col-sm-12 col-md-<?= $colNumber ?> col-xs-<?= $colNumber ?>"
         style="padding-left:2px;padding-right:2px;">
        <?php if ($this->client()->getTag() === 'athen'):
            $lang = $this->layout()->userLang;
            switch ($lang) {
                case 'de':
                    $lang = 'de-DE';
                    break;
                case 'el':
                    $lang = 'el-GR';
                    break;
                default:
                    $lang = 'en-US';
            }
            $url = str_replace('%lang%', $lang, $url);
        endif; ?>


        <a href="<?= $this->escapeHtmlAttr($url) ?>"
           title="<?= $this->transEsc('Search') ?> in <?= $this->escapeHtmlAttr($sourceTitle) ?>"
           target="_blank">
            <img class="img-responsive img-rounded"
                 src="<?= $this->imageLink('/searchbuttons/' . $imageName) ?>"
                 alt="<?= $this->transEsc('SearchButtons::' . $sourceTitle) ?>"
                 title="<?= $this->transEsc('SearchButtons::' . $sourceTitle) ?>"
                 data-toggle="tooltip"/>
        </a>
    </div>
<?php endif; ?>

