<?php $suggestions = $this->recommend->getSuggestions();
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

if (!empty($suggestions)): ?>
    <?php $external = false ?>
    <div class="alert alert-info">
        <p><?= $this->transEsc('switchquery_intro') ?></p>
        <ul>
            <?php foreach ($suggestions as $desc => $query): ?>
                <li><?= $this->transEsc($desc) ?>: <a
                            href="<?= $this->recommend->getResults()->getUrlQuery()->setSearchTerms($query) ?>"><?= $this->escapeHtml($query) ?></a>.
                </li>
            <?php endforeach; ?>
            <li><?= $this->transEsc('switchquery_removewords') ?></li>
            <li><?= $this->transEsc('switchquery_typos') ?></li>
            <li><?= $this->transEsc('switchquery_other') ?></li>
        </ul>
        <?php if ($this->searchTabs()->isILL($this->searchClassId)): ?>
            <?php
            $library = $this->libraries()->getFirstActive($this->client()->getIsils());
            $url = $this->url('record-freeform');

            if (isset($library) && $library->hasCustomUrl()) {
                $url = $library->getCustomUrl();
                $external = true;
            }
            ?>
            <p><?= $this->transEsc('switchquery_ill') ?>
                &nbsp;<a class="<?= $external ? 'external' : 'internal' ?>"
                         href="<?= $url ?>"><?= $this->transEsc('ill_request_free_form') ?></a>
            </p>
        <?php endif; ?>
    </div>
<?php endif; ?>