<?php if (isset($list)): ?>
    <input type="hidden" name="listID"
           value="<?= $this->escapeHtmlAttr($list->id) ?>"/>
    <input type="hidden" name="listName"
           value="<?= $this->escapeHtmlAttr($list->title) ?>"/>
<?php endif; ?>
<?php $user = $this->auth()->isLoggedIn(); ?>
<div class="bulkActionButtons">
    <div class="bulk-checkbox">
        <input type="checkbox" name="selectAll" class="checkbox-select-all"
               id="myresearchCheckAll"/>
        <label for="myresearchCheckAll"><?= $this->transEsc('select_page') ?>
            | <?= $this->transEsc('with_selected') ?>:</label>
    </div>
    <div class="btn-group">
        <input class="btn btn-primary btn-xs" type="submit" name="email"
               value="<?= $this->transEsc('Email') ?>"
               title="<?= $this->transEsc('email_selected') ?>"/>
        <?php if ((null !== $this->list && $this->list->editAllowed($user)) || null === $this->list && $user): ?>
            <input class="btn btn-primary btn-xs"
                   id="<?= $this->idPrefix ?>delete_list_items_<?= null !== $this->list ? $this->escapeHtmlAttr($this->list->id) : '' ?>"
                   type="submit" name="delete"
                   value="<?= $this->transEsc('Delete') ?>"
                   title="<?= $this->transEsc('delete_selected') ?>"/>
        <?php endif; ?>
        <?php $exportOptions = $this->export()->getActiveFormats('bulk');
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

if (count($exportOptions) > 0): ?>
            <input class="btn btn-primary btn-xs" type="submit" name="export"
                   value="<?= $this->transEsc('Export') ?>"
                   title="<?= $this->transEsc('export_selected') ?>"/>
        <?php endif; ?>
        <input class="btn btn-primary btn-xs" type="submit" name="print"
               value="<?= $this->transEsc('Print') ?>"
               title="<?= $this->transEsc('print_selected') ?>"
               data-lightbox-ignore/>
        <?php if ($this->cart()->isActive()): ?>
            <input class="btn btn-primary btn-xs"
                   id="<?= $this->idPrefix ?>updateCart" type="submit" name="add"
                   value="<?= $this->transEsc('Add to Book Bag') ?>"/>
        <?php endif; ?>
    </div>
</div>
