<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */


// Set up page title:
$this->headTitle($this->translate('Edit') . ' : ' . $this->driver->getBreadcrumb());

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Edit') . '</li>';
?>
<div class="col-sm-6 col-md-12">
    <div class="record">
        <h2><?= $this->escapeHtml($this->driver->getBreadcrumb()) ?></h2>

        <form class="form-list-edit" method="post" name="editForm">
            <?php if (empty($this->savedData)): ?>
                <p class="alert alert-info">
                    <?php if (isset($listFilter)): ?>
                        <?= $this->transEsc('The record you selected is not part of the selected list.') ?>
                    <?php else: ?>
                        <?= $this->transEsc('The record you selected is not part of any of your lists.') ?>
                    <?php endif; ?>
                </p>
            <?php else: ?>
                <div class="list-edit-container">
                    <?php foreach ($this->savedData as $i => $current): ?>
                        <fieldset class="list-edit-group">
                            <h3><?= $this->transEsc('List') ?>
                                : <?= $this->escapeHtml($current['listTitle']) ?></h3>
                            <input type="hidden" name="lists[]"
                                   value="<?= $current['listId'] ?>"/>
                            <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
                                <div class="form-group">
                                    <label class="control-label"
                                           for="edit_tags<?= $current['listId'] ?>"><?= $this->transEsc('Tags') ?>
                                        :</label>
                                    <input type="text"
                                           name="tags<?= $current['listId'] ?>"
                                           id="edit_tags<?= $current['listId'] ?>"
                                           class="form-control"
                                           value="<?= $this->escapeHtmlAttr($current['tags']) ?>"/>
                                    <span class="help-block"><?= $this->transEsc("add_tag_note") ?></span>
                                </div>
                            <?php endif; ?>
                            <div class="form-group">
                                <label class="control-label"
                                       for="edit_notes<?= $current['listId'] ?>"><?= $this->transEsc('Notes') ?>
                                    :</label>
                                <textarea class="form-control"
                                          id="edit_notes<?= $current['listId'] ?>"
                                          name="notes<?= $current['listId'] ?>"
                                          rows="3"><?= $this->escapeHtml($current['notes']) ?></textarea>
                            </div>
                            <a href="<?= $this->url('userList', ['id' => $current['listId']]) ?>?delete=<?= urlencode($this->driver->getUniqueId()) ?>&amp;source=<?= urlencode($this->driver->getSourceIdentifier()) ?>"
                               id="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>delete<?= $current['listId'] ?>"
                               data-lightbox>
                                <i class="fa fa-trash"></i> <?= $this->transEsc('Delete') /* TODO: replace with better string */ ?>
                            </a>
                        </fieldset>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <?php if (count($this->lists) > 0): ?>
                <hr/>
                <div class="form-group">
                    <select name="addToList" class="form-control">
                        <option value="-1">
                            - <?= $this->transEsc('Add to another list') ?> -
                        </option>
                        <?php foreach ($this->lists as $listID => $listTitle): ?>
                            <option value="<?= $listID ?>"><?= $this->escapeHtml($listTitle) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
            <?php if (!empty($this->savedData) || count($this->lists) > 0): ?>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" name="submit"
                           value="<?= $this->transEsc('Save') ?>"/>
                </div>
            <?php endif; ?>
        </form>
    </div>

</div>
