
<form class="form-inline search-dedup" action="<?=$this->currentPath()?>" method="POST" name=""dedup">    
    <div class="form-group">
        <label for="dedup-checkbox"><?=$this->transEsc('group hits')?></label>
        <input type="checkbox" name="dedup-enabled" value="" id="dedup-checkbox" checked/>          
    </div>
    <noscript>
    <p>Please enable JavaScript</p>
    </noscript>
</form>