<?php $list = $this->params->getSortList();
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

if (!empty($list)): ?>
    <form class="form-inline search-sort" action="<?= $this->currentPath() ?>"
          method="get" name="sort">
        <div class="form-group">
            <?= $this->results->getUrlQuery()->asHiddenFields(['sort' => '/.*/']); ?>
            <label for="sort_options_1"><?= $this->transEsc('Sort') ?></label>
            <select id="sort_options_1" name="sort" class="jumpMenu form-control">
                <?php foreach ($list as $sortType => $sortData): ?>
                    <option value="<?= $this->escapeHtmlAttr($sortType) ?>"<?= $sortData['selected'] ? ' selected="selected"' : '' ?>><?= $this->transEsc($sortData['desc']) ?></option>
                <?php endforeach; ?>
            </select>
            <noscript><input type="submit" class="btn btn-default"
                             value="<?= $this->transEsc("Set") ?>"/></noscript>
        </div>
    </form>
<?php endif; ?>
