<hr/>
<div class="row">  
    <div class="col-sm-3 hidden-xs">
        <a href="<?=$this->client()->getWebsite()?>" class="external hasicon">
            <img class="" src="<?=$this->imageLink($this->client()->getLogo())?>" alt="DLR Logo" />
        </a>
    </div>
    <?=$this->partial('bsz/footerbox.phtml', ['boxNo' => 1, 'heading' => $this->transEsc('Search Options')])?>
    <?=$this->partial('bsz/footerbox.phtml', ['boxNo' => 2, 'heading' => $this->transEsc('Find More')])?>
    <?=$this->partial('bsz/footerbox.phtml', ['boxNo' => 3, 'heading' => $this->transEsc('Help')])?>

    <small><a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-comment"></i> <?=$this->transEsc("Feedback")?></a> &nbsp; <a href="https://wiki.bsz-bw.de/doku.php?id=projekte:boss:bossroadmap" class="external"><?=$this->escapeHtml($this->client()->getVersion())?></a> &copy; <?=date('Y')?> <a href="http://bsz-bw.de" class="external hasicon">BSZ</a>
        powered by <a href="https://vufind.org" class="external">vufind</a> 2, Covers &copy; <a href="https://Buchhandel.de" class="external">Buchhandel.de</a>, <a href="https://openlibrary.org" class="external">OpenLibrary</a></small>        
</div>
