<p>Im <strong>Bibliothekskatalog</strong> suchen Sie im Bestand der Mannheimer Musikhochschulbibliothek - 
    nachgewiesen sind alle Bücher, Noten, CDs, DVDs, Videos, eBooks, Zeitschriften,
    … sogar teilweise enthaltene Werke.</p>
<p>Im Reiter <strong>Digitale Bibliothek</strong> finden Sie digitale Volltexte 
    von Zeitschriftenartikeln, weitere e-Books, Musiktracks (Naxos Datenbanken, 
    Digital Concert Hall), Noten-PDFs (IMSLP), Videos (Naxos) und andere wissenschaftliche/künstlerische 
    Literatur aus lizenzierten und freien Datenbanken.</p>
<p>In „<strong>Andere Bibliotheken</strong>“ finden Sie Bestände anderer Bibliotheken im näheren 
    Umkreis oder in ganz Deutschland. Eine Fernleihe starten Sie bitte über die 
    <a class="external hasicon" target="_blank" href="https://www.bib.uni-mannheim.de/fernleihe/">UB Mannheim</a> 
    oder <a class="external hasicon" target="_blank" href="https://www.ub.uni-heidelberg.de/allg/benutzung/bereiche/fernl.html">UB Heidelberg</a>.</p>