<p>The <strong>Library Catalogue</strong> searches the holdings of the library of 
    the University of Music and Performing Arts Mannheim: you can find books, 
    sheet music, CDs, DVDs, videos, e-books, journals… partly even the works 
    included in article compilations, music collections, etc.</p>
<p>You can find online-content in the <strong>Digital Library</strong>: full texts, 
    articles and eBooks, music tracks (Naxos Libraries, Digital Concert Hall), 
    sheet music (IMSLP), videos (Naxos) and other literature licensed by the 
    University of Music and Performing Arts Mannheim or free sources.
    </p>
<p>The tab „<strong>Other libraries</strong>“ offers the options of searching the 
    holdings of other libraries near Mannheim or even of libraries all over Germany. 
    Please place an interlibrary loan request in the
    <a class="external hasicon" target="_blank" href="https://www.bib.uni-mannheim.de/fernleihe/">UB Mannheim</a> 
    or <a class="external hasicon" target="_blank" href="https://www.ub.uni-heidelberg.de/allg/benutzung/bereiche/fernl.html">UB Heidelberg</a>.</p>