<p>In <strong>Library Catalogue</strong> you search for holdings in the library of 
    Mannheim University of Music and Performing Arts: you find records for books, 
    sheet music, CDs, DVDs, videos, e-books, journals… </p>
<p>Search online-content in the <strong>Digital Library</strong> full texts, articles 
    and e-Books, music tracks (Naxos Libraries, Digital Concert Hall), sheet music (IMSLP), 
    Videos (Naxos)…, licensed by Mannheim University of Music and Performing Arts or free sources.</p>
<p>The tab „<strong>Other libraries</strong>“ shows holdings in other libraries near Mannheim or in Germany. 
    Please start an interlibrary loan request in the 
    <a class="external hasicon" target="_blank" href="https://www.bib.uni-mannheim.de/fernleihe/">UB Mannheim</a> 
    or <a class="external hasicon" target="_blank" href="https://www.ub.uni-heidelberg.de/allg/benutzung/bereiche/fernl.html">UB Heidelberg</a>.</p>