<!-- finc: auth - abstractbase - RESETPASSWORD (custom finc template)-->
<?
// Set page title.
$this->headTitle($this->translate('Reset Password'));
?>
<h2><?=$this->transEsc('Reset Password') ?></h2>
<form method="post" name="resetPasswordForm" action="<?=$this->url('myresearch-resetpassword')?>">
  <?=$this->flashmessages()?>
  <p>
    <?=$this->translate('reset_password_text')?>
  </p>

  <div class="row">
    <label class="col-xs-5 col-sm-2"><?=$this->transEsc('First Name') ?>:</label>
    <div class="col-xs-7 col-sm-4">
      <input type="text" name="firstname" <?=isset($firstname) ? 'value="'.$firstname.'" ' : ''?>required />
    </div>
  </div>
  <div class="row">
    <label class="col-xs-5 col-sm-2"><?=$this->transEsc('Last Name') ?>:</label>
    <div class="col-xs-7 col-sm-4">
      <input type="text" name="lastname" <?=isset($lastname) ? 'value="'.$lastname.'" ' : ''?>required/>
    </div>
  </div>
  <div class="row">
    <label class="col-xs-5 col-sm-2"><?=$this->transEsc('Username') ?>:</label>
    <div class="col-xs-7 col-sm-4">
      <input type="text" name="username" <?=isset($username) ? 'value="'.$username.'" ' : ''?>required/>
    </div>
  </div>
  <div class="row">
    <label class="col-xs-5 col-sm-2"><?=$this->transEsc('Email') ?>:</label>
    <div class="col-xs-7 col-sm-4">
      <input type="email" name="email" <?=isset($email) ? 'value="'.$email.'" ' : ''?>required/>
    </div>
  </div>
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  <div class="row">
    <div class="col-sm-10 offset-sm-2">
      <input class="btn btn-transparent" name="submit" type="submit" aria-label="submit form"  value="<?=$this->transEsc('recovery_title') ?>"/>
    </div>
  </div>
</form>
<!-- finc: auth - abstractbase - RESETPASSWORD (custom finc template) - END -->
