<!-- finc: auth - abstractbase - resetpassword (custom finc template)-->
<? /* compare with BS login templates in Auth during updates */ ?>
<?
// Set page title.
$this->headTitle($this->translate('Reset Password'));
?>
<h2><?=$this->transEsc('Reset Password') ?></h2>
<form method="post" name="resetPasswordForm" action="<?=$this->url('myresearch-resetpassword')?>">
  <?=$this->flashmessages()?>
  <p>
    <?=$this->translate('reset_password_text')?>
  </p>

  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('First Name')?>:</label>
      <input type="text" class="form-control" name="firstname" <?=isset($firstname) ? 'value="'.$firstname.'" ' : ''?>required />
    </div>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Last Name')?>:</label>
      <input type="text" class="form-control" name="lastname" <?=isset($lastname) ? 'value="'.$lastname.'" ' : ''?>required/>
    </div>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Username')?>:</label>
      <input type="text" class="form-control" name="username" <?=isset($username) ? 'value="'.$username.'" ' : ''?>required/>
    </div>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Email')?>:</label>
      <input type="email" class="form-control" name="email" <?=isset($email) ? 'value="'.$email.'" ' : ''?>required/>
    </div>
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  <div class="form-group">
      <input class="btn btn-transparent" name="submit" type="submit" aria-label="submit form"  value="<?=$this->transEsc('recovery_title') ?>"/>
    </div>
</form>
<!-- finc: auth - abstractbase - resetpassword - END -->
