<!-- finc: myresearch - menu -->
<h4><?=$this->transEsc('Your Account')?></h4>
<? /* finc needs to add .facet-group class and classes on sub items for borders - CK */ ?>
<div class="myresearch-menu facet-group">
    <? if ($this->userlist()->getMode() !== 'disabled'): ?>

        <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Favorites')?>
        </a>

    <? endif; ?>
    <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
      <? if ($this->ils()->checkCapability('getMyTransactions')): ?>

        <a href="<?=$this->url('myresearch-checkedout')?>"<?=$this->active == 'checkedout' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('Checked Out Items')?>
          <? /* nxt line finc specific - CK */ ?>
          <span id="getMyTransactions" class="itemCount pull-right no-padding"></span>
        </a>
      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyHolds')): ?>

        <a href="<?=$this->url('myresearch-holds')?>"<?=$this->active == 'holds' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-flag" aria-hidden="true"></i> <?=$this->transEsc('Holds and Recalls')?>
          <? /* nxt line finc specific - CK */ ?>
          <span id="getMyHolds" class="itemCount pull-right no-padding"></span>
        </a>

      <? endif; ?>
      <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>

        <a href="<?=$this->url('myresearch-storageretrievalrequests')?>"<?=$this->active == 'storageRetrievalRequests' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?>
          <? /* nxt line finc specific - CK */ ?>
          <span id="getMyStorageRetrievalRequests" class="itemCount pull-right no-padding"></span>
        </a>

      <? endif; ?>
      <? if ($this->ils()->checkFunction('ILLRequests')): ?>

        <a href="<?=$this->url('myresearch-illrequests')?>"<?=$this->active == 'ILLRequests' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?>
          <? /* nxt line finc specific - CK */ ?>
          <span id="getMyILLRequests" class="itemCount pull-right no-padding"></span>
        </a>

      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyFines')): ?>

        <a href="<?=$this->url('myresearch-fines')?>"<?=$this->active == 'fines' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-usd" aria-hidden="true"></i> <?=$this->transEsc('Fines')?>
        </a>

      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyProfile')): ?>

        <a href="<?=$this->url('myresearch-profile')?>"<?=$this->active == 'profile' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
        </a>

      <? endif; ?>
      <? $user = $this->auth()->isLoggedIn();
      if ($user && $user->libraryCardsEnabled()): ?>

        <a href="<?=$this->url('librarycards-home')?>"<?=$this->active == 'librarycards' ? ' class="active"' : ''?>>
          <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
        </a>

      <? endif; ?>
    <? endif; ?>
    <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>

      <a href="<?=$this->url('search-history')?>?require_login"<?=$this->active == 'history' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
      </a>

    <? endif; ?>
    <? if ($user = $this->auth()->isLoggedIn()): ?>
    <a href="<?=$this->url('myresearch-logout')?>">
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
    <? endif; ?>
</div>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="myresearch-menu facet-group">

    <a href="<?=$this->url('myresearch-changepassword')?>"<?=$this->active == 'newpassword' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password')?>
    </a>

  </div>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="myresearch-menu facet-group">

    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>

    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
      <? /* finc: keep icon inside + keep braces in badge!; CK*/ ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-star-o" aria-hidden="true"></i> <?=$this->escapeHtml($list['title'])?>
        <span class="badge">(<?=$list->cnt?>)</span>
      </a>

    <? endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List')?>
    </a>

  </div>
<? endif ?>
<? /* finc: This script is finc-specific - CK */ ?>
<? $script = <<<JS
$(document).ready(function () {
    countables = new Array;
    $('.itemCount').each(function() {
        countables.push($(this).attr('id'));
    });

    $.ajax({
        dataType: 'json',
        method: 'POST',
        url: VuFind.path + '/AJAX/JSON?method=getAdditionalAccountInfo',
        data: {'views':countables}
    })
    .done(function(response) {
        $.each(response.data, function (i, result) {
            $.each(result, function (id, itemCount) {
                $('#'+id).text('('+itemCount+')');
            });
        });
    });
});
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');?>
<!-- finc: myresearch - menu - END -->
