<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

$this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('Shibboleth') . '</li>';
    $this->headTitle()->setPrefix($this->transEsc('Shibboleth'));
    ?>


<div class="col-sm-12">
    <h3><?=$this->transEsc('shib_wayf_headline')?></h3>
    <p><?=$this->transEsc('shib_wayf_hint')?></p>
</div>
<div class="col-md-6">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button"
                id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="true">
            <?= $this->transEsc('Library') ?>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" id="idp-list">

            <?php
            $baseUrl = $this->url('shib-redirect');
            $params = [];
            foreach ($this->libraries()->getByShib() as $library):
                $params['isil'] = $library->getIsil(); ?>
                <li><a href="<?= $baseUrl . '?' . http_build_query($params) ?>"
                       data-isil="<?= $this->escapeHtmlAttr($library->getIsil()) ?>"><?= $this->EscapeHtml($library->getName()) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var isilsSession = [];
        <?php foreach ($this->client()->getIsils() as $isil): ?>
        isilsSession.push('<?=$this->escapeHtml($isil)?>');
        <?php endforeach; ?>
        isilsSession.forEach(function (isil) {
            var href = $('#idp-list').find('a[data-isil=' + isil + ']').attr('href');
            if (href != undefined && href.length > 0) {
                window.location.replace(href);
            }
        });
    });



</script>