<? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>
<? if (count($searchTabs) > 0): ?>
  <dl class="tabs" data-tab><!-- check if this works - FIXME - CK -->
    <? foreach ($searchTabs as $tab): ?>
      <dd<?=$tab['selected'] ? ' class="tab-title active"' : ''?>>
        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
      </dd>
    <? endforeach; ?>
  </dl>
<? endif; ?>