<?php foreach ($this->driver->getFormats() as $format): ?>
    <?php if ($format == 'Online' || $format == 'E-Book'): ?>
        <?php $labelclass = "label-success"?>
    <?php else: ?>
        <?php $labelclass="label-info"?>
    <?php endif ?>
    <span class="label <?=$labelclass?> <?= $this->record($this->driver)->getFormatClass($format) ?>"><?= $this->transEsc('Formats::'.$format) ?></span>
<?php endforeach; ?>
