<? $labelSize = 3; ?>
<? $inputSize = 9; ?>
<? $id = rand(0, 10000)?>
<? $forceRequired = false; ?>

<? // these fields get class required to be able to set them required in JS when switching to copies ?>
<? $alwaysRequired = ['AufsatzAutor', 'AufsatzTitel'];
if(in_array($name, $alwaysRequired)):
    $forceRequired = true;
endif ;?>
<div class="form-group form-group-sm <? if ($required):?>show required<? endif; ?> <? if ($forceRequired):?>required<? endif; ?>">
    <label class="control-label col-sm-<?=$labelSize?>" for="ill-<?=$id?>"><?=$this->transEsc($label)?></label>
    <div class="col-sm-<?=$inputSize?>"> 
      <? $title = is_array($value) ? implode(',',$value) : $value?>
      <input type="text" class="form-control" 
             id="ill-<?=$this->escapeHtmlAttr($id)?>" 
             value="<?=$this->string()->cleanEsc($value)?>" 
             name="<?=$this->escapeHTMLAttr($name)?>" 
             data-validate="<?=$required ? true : false?>"
             data-<?=strtolower($this->escapeHtmlAttr($name))?>=""
             placeholder="<?=$this->transEsc($placeholder)?>"
             <?=$this->illform($this->status, $this->driver)->maxlength($name)?>
             <? if ($required):?>required="true"<? endif; ?>
             <? if (!empty($error)):?>data-error="<?=$this->transEsc($error)?>"<? endif; ?>/>
             <? if (!empty($error)): ?>
             <span class="help-block with-error"><?=$this->transEsc($error)?></span>             
             <? endif; ?>
    </div>
</div>