<? $labelSize = 3; ?>
<? $inputSize = 9; ?>
<? $id = rand(0, 10000)?>
<div class="form-group form-group-sm">
    <label class="control-label col-sm-<?=$labelSize?>" for="ill-<?=$id?>"><?=$this->transEsc($label)?><? if($required):?>*<? endif; ?></label>
    <div class="col-sm-<?=$inputSize?>"> 
      <? $title = is_array($value) ? implode(',',$value) : $value?>
      <input type="<?=$this->escapeHtmlAttr($type)?>" class="form-control" 
             id="ill-<?=$this->escapeHtmlAttr($id)?>" 
             value="<?=$this->string()->cleanEsc($value)?>" 
             name="<?=$this->escapeHTMLAttr($name)?>" 
             placeholder="<?=$this->transEsc($placeholder)?>"
             <?=$this->illform($this->status, $this->driver)->maxlength($name)?>
             <? if ($required):?>required=""<? endif; ?>
             <? if (!empty($error)):?>data-error="<?=$this->escapeHtml($error)?>"<? endif; ?>/>
             <? if (!empty($error)): ?>
             <span class="help-block with-error"></span>
             <? endif; ?>
    </div>
</div>