<?php $labelSize = 3;


$inputSize = 9;
$account = $this->auth()->getManager();
$library = $this->libraries()->getFirstActive($this->client()->getIsils());
$authMethod = '';
if (isset($library)) {
    $authMethod = $library->getAuth();
}
?>
<?php if (!$account->loginEnabled() || $authMethod != 'shibboleth'): ?>
    <div class=" form-group form-group-sm <?= isset($success) && !$success ? 'has-error' : '' ?>">
        <label class="control-label col-sm-<?= $labelSize ?>"
               for="ill-user"><?= $this->transEsc('Benutzernummer') ?>*</label>
        <div class="col-sm-3">
            <input required="" type="text" class="form-control" id="ill-user"
                   name="BenutzerNummer"
                   value="<?= $params['BenutzerNummer'] ?? '' ?>"/>
        </div>
    </div>
    <?php $libraries = $this->libraries()->getActive($this->client()->getIsils()) ?>
    <?php $firstLibrary = array_shift($libraries);
    if (isset($firstLibrary) && $firstLibrary->getAuth() == 'tan'): ?>
        <div class=" form-group form-group-sm <?= isset($success) && !$success ? 'has-error' : '' ?>">
            <label class="control-label col-sm-<?= $labelSize ?>"
                   for="ill-tan"><?= $this->transEsc('TAN') ?>*</label>
            <div class="col-sm-3">
                <input type="password" class="form-control" id="ill-tan" name="TAN"
                       required=""/>
            </div>
        </div>
    <?php else: ?>
        <div class=" form-group form-group-sm <?= isset($success) && !$success ? 'has-error' : '' ?> ">
            <label class="control-label col-sm-<?= $labelSize ?>"
                   for="ill-password"><?= $this->transEsc('Password') ?>*</label>
            <div class="col-sm-3">
                <input type="password" class="form-control" id="ill-password"
                       name="Passwort" required=""/>
            </div>
        </div>
    <?php endif; ?>
<?php elseif ($account->isLoggedIn()): ?>
    <?php $identity = $account->getIdentity() ?>
    <div CLASS="col-sm-12 col-sm-offset-3">
        <p>
            <i class="fa fa-check text-success"></i> <?= $this->transEsc('shib_already_logged_in') ?>
        </p>
    </div>
    <!-- user name may be replaced before sending to zfl server -->
    <input type="hidden" name="BenutzerNummer"
           value="<?= htmlspecialchars($identity->username) ?>"/>
<?php endif; ?>
<?php $zdb = isset($this->driver) ? $this->driver->getZdbId() : '' ?>
<?php $ppn = 999999999;
$verbund = '';
if (empty($zdb) && isset($this->driver)) {
    $ppn = $this->driver->getPPN();
    $verbund = $this->driver->tryMethod('getNetwork');
} elseif (isset($this->driver) && !empty($zdb)) {
    $ppn = $zdb;
    $verbund = 'ZDB';
}
?>
<input type="hidden" name="Verbund" value="<?= $this->escapeHtmlAttr($verbund) ?>"/>
<input type="hidden" name="TitelId" value="<?= $this->escapeHtmlAttr($ppn) ?>"/>
<input type="hidden" name="Besteller" value="E"/>

<?php if (isset($this->driver)): ?>
    <?php // nicht freies Fernleihformular ?>
    <input type="hidden" name="ATEB" value="off"/>
<?php else: ?>
    <?php // freies Fernleihformular ?>
    <input type="hidden" name="ATEB" value="on"/>
<?php endif; ?>

<input type="hidden" name="SignZustand" value="off"/>

