<!-- finc: record - emailhold -->
<?
    // Set page title.
    $this->headTitle($this->translate('EmailHold::email_hold_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li>')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>'
        . '<li class="active">' . $this->transEsc('EmailHold::email_hold_place_text') . '</li>';
?>
<h2><?=$this->transEsc('EmailHold::email_hold_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>
<div class="email-hold-form">
  <form name="placeEmailHold" method="post">
    <? if (in_array("item-issue", $this->extraFields)): ?>
        <div id="emailHoldReference" class="emailHoldReference">
        <label class="control-label" for="volume"><?=$this->transEsc('EmailHold::email_hold_volume')?>:</label>
        <input type="text" name="gatheredDetails[volume]" value="<?=isset($this->gatheredDetails['volume']) ? $this->escapeHtmlAttr($this->gatheredDetails['volume']) : ''?>" id="volume" class="form-control"/><br/>

        <label class="control-label" for="issue"><?=$this->transEsc('EmailHold::email_hold_issue')?>:</label>
        <input type="text" name="gatheredDetails[issue]" value="<?=isset($this->gatheredDetails['issue']) ? $this->escapeHtmlAttr($this->gatheredDetails['issue']) : ''?>" id="issue" class="form-control"/><br/>

        <label class="control-label" for="year"><?=$this->transEsc('EmailHold::email_hold_year')?>:</label>
        <input type="text" name="gatheredDetails[year]" value="<?=isset($this->gatheredDetails['year']) ? $this->escapeHtmlAttr($this->gatheredDetails['year']) : ''?>" id="year" class="form-control"/><br/>
      </div>
    <? endif; ?>

    <? if (in_array("requiredByDate", $this->extraFields)): ?>

      <label class="control-label" for="requiredByDate"><?=$this->transEsc("EmailHold::hold_required_by")?>:</label>
      <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="form-control"/>
          (<?=$this->dateTime()->getDisplayDateFormat()?>)

    <? endif; ?>

    <? if (in_array("pickUpLocation", $this->extraFields)): ?>
      <? if (count($this->pickup) > 1): ?>
          <?
            if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
                $selected = $this->gatheredDetails['pickUpLocation'];
            } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
                $selected = $this->homeLibrary;
            } else {
                $selected = $this->defaultPickup;
            }
          ?>
        <label class="control-label" for="pickUpLocation"><?=$this->transEsc("EmailHold::pick_up_location")?>:</label>
        <select name="gatheredDetails[pickUpLocation]" id="pickUpLocation" class="form-control">
            <? if ($selected === false): ?>
              <option value="" selected="selected">
                <?=$this->transEsc('EmailHold::select_pickup_location')?>
              </option>
            <? endif; ?>
            <? foreach ($this->pickup as $lib): ?>
              <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>" <?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
                <?=$this->escapeHtml($lib['locationDisplay'])?>
              </option>
            <? endforeach; ?>
            </select>

      <? else: ?>
        <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
      <? endif; ?>
    <? endif; ?>

    <? if (in_array("comments", $this->extraFields)): ?>
      <label class="control-label" for="comment"><?=$this->transEsc("Comments")?>:</label>
      <textarea rows="3" cols="20" name="gatheredDetails[comment]" id="comment" class="form-control"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
    <? endif; ?>

        <input class="btn btn-primary" type="submit" name="placeEmailHold" role="button" value="<?=$this->transEsc('EmailHold::email_hold_submit_text')?>"/>

  </form>
</div>
<!-- finc: record - emailhold - END -->
