<!-- finc: record - EMAILHOLD -->
<?
    // Set page title.
    $this->headTitle($this->translate('EmailHold::email_hold_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li>')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>'
        . '<li class="active">' . $this->transEsc('EmailHold::email_hold_place_text') . '</li>';
?>
<h2><?=$this->transEsc('EmailHold::email_hold_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>
<div class="email-hold-form">
  <form name="placeEmailHold" method="post">
    <? if (in_array("item-issue", $this->extraFields)): ?>
      <div class="row">
        <div id="emailHoldReference" class="emailHoldReference">
          <label class="col-sm-3"><?=$this->transEsc('EmailHold::email_hold_volume')?>:</label>
          <div class="col-sm-9">
            <input type="text" name="gatheredDetails[volume]" value="<?=isset($this->gatheredDetails['volume']) ? $this->escapeHtmlAttr($this->gatheredDetails['volume']) : ''?>" class="auto"/><br/>
          </div>
          <label class="col-sm-3"><?=$this->transEsc('EmailHold::email_hold_issue')?>:</label>
          <div class="col-sm-9">
            <input type="text" name="gatheredDetails[issue]" value="<?=isset($this->gatheredDetails['issue']) ? $this->escapeHtmlAttr($this->gatheredDetails['issue']) : ''?>" class="auto"/><br/>
          </div>
          <label class="col-sm-3"><?=$this->transEsc('EmailHold::email_hold_year')?>:</label>
          <div class="col-sm-9">
            <input type="text" name="gatheredDetails[year]" value="<?=isset($this->gatheredDetails['year']) ? $this->escapeHtmlAttr($this->gatheredDetails['year']) : ''?>" class="auto"/><br/>
          </div>
        </div>
      </div>
    <? endif; ?>

    <? if (in_array("requiredByDate", $this->extraFields)): ?>
      <div class="row">
        <label class="col-sm-3"><?=$this->transEsc("EmailHold::hold_required_by")?>:</label>
        <div class="col-sm-9">
          <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="auto"/>
          (<?=$this->dateTime()->getDisplayDateFormat()?>)
        </div>
      </div>
    <? endif; ?>

    <? if (in_array("pickUpLocation", $this->extraFields)): ?>
      <? if (count($this->pickup) > 1): ?>
        <div class="row">
          <?
            if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
                $selected = $this->gatheredDetails['pickUpLocation'];
            } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
                $selected = $this->homeLibrary;
            } else {
                $selected = $this->defaultPickup;
            }
          ?>
          <label class="col-sm-3"><?=$this->transEsc("EmailHold::pick_up_location")?>:</label>
          <div class="col-sm-9">
            <select name="gatheredDetails[pickUpLocation]" class="form-control">
            <? if ($selected === false): ?>
              <option value="" selected="selected">
                <?=$this->transEsc('EmailHold::select_pickup_location')?>
              </option>
            <? endif; ?>
            <? foreach ($this->pickup as $lib): ?>
              <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>" <?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
                <?=$this->escapeHtml($lib['locationDisplay'])?>
              </option>
            <? endforeach; ?>
            </select>
          </div>
        </div>
      <? else: ?>
        <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
      <? endif; ?>
    <? endif; ?>

    <? if (in_array("comments", $this->extraFields)): ?>
      <div class="row">
        <label class="col-sm-3"><?=$this->transEsc("Comments")?>:</label>
        <div class="col-sm-9">
          <textarea rows="3" cols="20" name="gatheredDetails[comment]" class="auto"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
        </div>
      </div>
    <? endif; ?>

    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <input class="btn btn-primary" type="submit" name="placeEmailHold" role="button" value="<?=$this->transEsc('EmailHold::email_hold_submit_text')?>"/>
      </div>
    </div>
  </form>
</div>
<!-- finc: record - EMAILHOLD - END -->
