<!-- record - PDAFORM.phtml -->
<?
  // Set page title.
  $this->headTitle($this->translate('PDA::Acquisition'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li>')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>'
    . '<li class="active">' . $this->transEsc('PDA::Acquisition') . '</li>';
?>
<h2><?=$this->transEsc('PDA::Acquisition') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
<form method="post" name="acquisitionPDAForm" action="<?=$this->recordLink()->getActionUrl($this->driver, 'PDA')?>">
  <?=$this->flashmessages()?>
  <p>
    <?=$this->translate('PDA::pda_order_text')?>
    <?=(strlen($price = $this->driver->getPrice()) > 0) ? $this->translate('PDA::pda_price_text', [':::PRICE:::'=>$this->safeMoneyFormat($price)]) : ''?>
    <?=$this->translate('PDA::pda_delivery_text')?>
  </p>
  <div class="row collapse">
    <label class="medium-3 columns" for="pdaStatement"><?=$this->transEsc('PDA::pda_form_statement_label')?><span class="required">*</span>:</label>
    <div class="medium-9 columns">
      <textarea id="pdaStatement" class="auto" name="pdaStatement" rows="5" type="text" cols="50"><?=isset($this->pdaStatement) ? $this->pdaStatement : ''?></textarea>
    </div>

    <label class="medium-3 columns" for="pdaSubject"><?=$this->transEsc('PDA::pda_form_field_of_study_label') ?><span class="required">*</span>:</label>
    <div class="medium-9 columns">
      <select name="pdaFieldOfStudy" class="form-control">
        <option value="-1"><?=$this->transEsc('PDA::pda_form_field_of_study_text')?></option>
        <? if (isset( $this->fieldOfStudyList) && is_array( $this->fieldOfStudyList)): ?>
          <? foreach ( $this->fieldOfStudyList as $value): ?>
            <option value="<?=$value?>" <? if (!empty($this->pdaFieldOfStudy) && $value==$this->pdaFieldOfStudy): ?> selected="selected"<? endif; ?>><?= $this->transEsc('PDA::fos_' . $value) ?></option>
          <? endforeach; ?>
        <? endif; ?>
      </select>
    </div>
    <div class="medium-9 columns medium-offset-3">
      <span>
        <?=$this->recaptcha()->html($this->useRecaptcha) ?>
      </span>
      <ul class="button-group">
        <li>
          <input type="submit" class="button small" role="button" name="submit" value="<?=$this->transEsc('Submit')?>"/>
        </li>
        <li>
          <a class="button small has-tip" data-lightbox-ignore data-tooltip data-options="touch_close_text: '<?= $this->transEsc('Tap to close')?>'" aria-haspopup="true" title="<?= $this->transEsc('PDA::pda_open_new_window')?>" href="<?= $this->interlibraryloan()->getSwbLink($this->driver) ?>" target="_blank"><?= $this->transEsc('PDA::pda_tab_interlibrary_button') ?>
          </a>
        </li>
        <li>
          <button class="small secondary close-reveal-modal" href="#"><?=$this->transEsc('Reset')?></button>
        </li>
      </ul>
      <p>
        <?= $this->transEsc('PDA::note_mandatory_fields') ?>
      </p>
    </div>
  </div>
</form>
<!-- record - PDAFORM.phtml end -->