<!-- finc: record - reporterrorsform -->
<?
// Set page title.
$this->headTitle($this->translate('ReportErrors'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li>')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>'
    . '<li class="active">' . $this->transEsc('ReportErrors') . '</li>';
?>
<h2><?=$this->transEsc('ReportErrors') ?>: <?=$this->escapeHtml($this->truncate($this->driver->getShortTitle() . ' ' . $this->driver->getSubTitle(), 90))?></h2>
<form name="reporterrors" method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'ReportErrors')?>">
  <?=$this->flashmessages()?>
  <div class="form-group">
    <label class="control-label" for="reporterrors_email"><?=$this->transEsc("Email")?></label>
      <input type="email" id="reporterrors_email" name="reporterrors_email" class="form-control"<? if (!empty($this->email)): ?> value="<?=$this->email?>"<? endif; ?>/>

    <div class="gutter-top gutter-btm <? if (empty($this->email)): ?>hidden<? endif; ?>" id="replyCheckbox">
      <input type="checkbox" id="reporterrors_checkbox" name="reporterrors_checkbox"<?=($this->reply_requested) ? ' checked' : ''?> class="form-control"/>
      <label for="reporterrors_checkbox" class="control-label"><?=$this->transEsc("reporterrors_response_requested")?></label>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label" for="comment"><?=$this->transEsc("Note")?></label>
      <textarea id="comment" name="comment" class="form-control" required><?=(!empty($this->comment)) ? $this->comment : ''?></textarea>
  </div>
  <div class="form-group">
      <input type="submit" class="btn btn-primary" role="button" name="submit" value="<?=$this->transEsc('Send')?>"/>
  </div>
</form>
<? $script = <<<JS
$(document).ready(function () {
  // show response email checkbox ReportErrors
  $('input#reporterrors_email').on('keyup change', function () {
    var emailcheck = /^[^0-9][a-zA-Z0-9_-]+([.][a-zA-Z0-9_-]+)*[@][a-zA-Z0-9_-]+([.][a-zA-Z0-9_-]+)*[.][a-zA-Z]{2,}$/;
    if (($(this).val().length > 0) && emailcheck.test($(this).val())) {
      $('div#replyCheckbox').removeClass('hidden');
    } else {
      $('div#replyCheckbox').addClass('hidden');
      $('input#reporterrors_checkbox').prop("checked", false);
    }
  });
});
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- finc: record - reporterrorsform - End -->
