<!-- record - view -->
<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
  $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
  $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
  '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();
?>

<? /* we use this row to push down content, finc-specific, CK */ ?>
<div class="row">
  <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
    <ul class="pager hidden-print">
      <? if ($this->scrollData['previousRecord']): ?>
        <li class="left">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('Prev')?></a>
        </li>
      <? else: ?>
        <li class="disabled left"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
      <? endif; ?>
      <? /* finc-specific, CK */ ?>
      <li class="hidden-xs">
        #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results')?>
      </li>
      <? if ($this->scrollData['nextRecord']): ?>
        <li class="right">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>" rel="nofollow"><?=$this->transEsc('Next')?> &raquo;</a>
        </li>
      <? else: ?>
        <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
      <? endif; ?>
    </ul>
  <? endif; ?>

  <? /* finc-specific Remove toolbar from here and add to sidebar below - CK */ ?>

  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId"/>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource"/>
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>
            <? // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $tab_classes = array();
            if (0 === strcasecmp($this->activeTab, $tab)) {
              if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                $tab_classes[] = 'active';
              }
              $tab_classes[] = 'initiallyActive';
              $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
              $activeTabObj = $obj;
            }
            if (!$obj->isVisible()) {
              $tab_classes[] = 'hidden';
            }
            if (!$obj->supportsAjax()) {
              $tab_classes[] = 'noajax';
            }
            ?>
            <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
              <a class="<?=strtolower($tab)?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
            </li>
          <? endforeach; ?>
        </ul>

        <div class="tab-content">
          <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->activeTab?>-tab">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : ''?>
            </div>
          <? endif; ?>
        </div>
      </div>
    <? endif; ?>

    <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>
  </div>


  <div class="<?=$this->layoutClass('sidebar')?>">
    <? /* finc-specific: add toolbar to sidebar - CK */ ?>
    <?=$this->record($this->driver)->getToolbar()?>

    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
  </div>
</div>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET');?>
<!-- record - view - END -->
