<!-- finc: record - view -->
<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
  $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
  $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
  '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();
?>

 <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
    <? /* Pager is identical to pager in collection - view! - CK */ ?>
    <ul class="pager hidden-print">
      <? if ($this->scrollData['previousRecord']): ?>
        <? if ($this->scrollData['firstRecord']): ?>
          <li class="left">
            <a href="<?=$this->recordLink()->getUrl($this->scrollData['firstRecord'])?>" title="<?=$this->transEsc('First Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('First')?></a>
          </li>
        <? endif; ?>
        <li class="left">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('Prev')?></a>
        </li>
      <? else: ?>
        <? if ($this->scrollData['firstRecord']): ?>
          <li class="disabled left"><a href="#">&laquo; <?=$this->transEsc('First')?></a></li>
        <? endif; ?>
        <li class="disabled left"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
      <? endif; ?>
      <? /* finc-specific: li + hidden-xs, and li class="right" below CK */ ?>
      <li class="hidden-xs">
        <?=$this->transEsc('of_num_results', [
          '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
          '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
        ]) ?>
      </li>
      <? if ($this->scrollData['nextRecord']): ?>
        <li class="right">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>" rel="nofollow"><?=$this->transEsc('Next')?> &raquo;</a>
        </li>
        <? if ($this->scrollData['lastRecord']): ?>
          <li class="right">
            <a href="<?=$this->recordLink()->getUrl($this->scrollData['lastRecord'])?>" title="<?=$this->transEsc('Last Search Result')?>" rel="nofollow"><?=$this->transEsc('Last')?> &raquo;</a>
          </li>
        <? endif; ?>
      <? else: ?>
        <li class="disabled right"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
        <? if ($this->scrollData['lastRecord']): ?>
          <li class="disabled right"><a href="#"><?=$this->transEsc('Last')?> &raquo;</a></li>
        <? endif; ?>
      <? endif; ?>
    </ul>
  <? endif; ?>

  <? /* finc-specific: Remove getToolbar from here and add it to sidebar below - CK */ ?>

  <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
    <div class="<?=$this->layoutClass('mainbody')?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId"/>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource"/>
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>

      <? if (count($this->tabs) > 0): ?>
        <a name="tabnav"></a>
        <div class="record-tabs">
          <ul class="nav nav-tabs">
            <? foreach ($this->tabs as $tab => $obj): ?>
              <? // add current tab to breadcrumbs if applicable:
              $desc = $obj->getDescription();
              $tab_classes = [];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tab_classes[] = 'active';
                }
                $tab_classes[] = 'initiallyActive';
                $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) {
                $tab_classes[] = 'hidden';
              }
              if (!$obj->supportsAjax()) {
                $tab_classes[] = 'noajax';
              }
              ?>
              <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
                <a class="<?=strtolower($tab)?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"<? if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)): ?> data-background<? endif ?>><?=$this->transEsc($desc)?></a>
              </li>
            <? endforeach; ?>
          </ul>

          <div class="tab-content">
            <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
              <div class="tab-pane active <?=$this->activeTab?>-tab">
                <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : ''?>
              </div>
            <? endif; ?>
          </div>
        </div>
      <? endif; ?>

      <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>
    </div>


    <div class="<?=$this->layoutClass('sidebar')?>">
      <? /* finc-specific: add toolbar to sidebar - CK */ ?>
      <?=$this->record($this->driver)->getToolbar()?>

      <? foreach ($this->related()->getList($this->driver) as $current): ?>
        <?=$this->related()->render($current)?>
      <? endforeach; ?>
    </div>
  </div>

  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET');?>
  <!-- finc: record - view - END -->
