<?
    $this->headLink()->appendStylesheet('EDS.css');
    
    $items = $this->driver->getItems();
    $dbLabel = $this->driver->getDbLabel();
    $thumb = $this->driver->getThumbnail('medium');
    $pubType = $this->driver->getPubType();
    $customLinks = $this->driver->getCustomLinks();
    $accessLevel = $this->driver->getAccessLevel();
    $restrictedView = empty($accessLevel) ? false : true;
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">    
    <div class="col-xs-12 col-sm-3 pull-right">
    <? if ($thumb): ?>
      <img src="<?=$this->escapeHtmlAttr($thumb)?>" class="recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
    <? else: ?>
      <span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>"></span>
    <? endif; ?>
    <? if ($pubType): ?>
      <p class="text-center"><?=$this->transEsc($pubType)?></p>
    <? endif; ?>

    <div class="external-links">
      <? $pLink = $this->driver->getPLink();
          if($pLink && false): ?>
        <span>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>" class="external">
            <?=$this->transEsc('View in EDS')?>
          </a>
        </span><br />
      <? endif; ?>
      <? $pdfLink = $this->driver->getPdfLink();
          if ($pdfLink): ?>
        <span>
          <a href="<?=$pdfLink?>" class="icon pdf fulltext external hasicon">
            <?=$this->transEsc('PDF Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
      <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
        <span>
          <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext external">
            <?=$this->transEsc('HTML Full Text')?>
          </a>
        </span><br />
      <? endif; ?>
    </div>
  </div>
  <div class="col-sm-9">
    <h3 property="name"><?=$this->driver->getTitle()?></h3>

    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? foreach ($items as $key => $item): ?>
        <? if (!empty($item['Data'])): ?>
        <tr>
          <th><?=$this->transEsc($item['Label'])?>:</th>
          <td><?=$this->driver->linkUrls($item['Data'])?></td>
        </tr>
        <? endif; ?>
      <? endforeach; ?>

      <? if ($dbLabel): ?>
        <tr>
          <th><?=$this->transEsc('Database')?>:</th>
          <td><?=$this->escapeHtml($dbLabel)?></td>
        </tr>
      <? endif; ?>

      <?if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView):
          $fullText = $this->driver->getHtmlFullText();?>
        <tr id="html">
          <td colspan="2">
            <?=$fullText?>
          </td>
        </tr>
      <? elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
        <tr id="html">
          <th>
            <?=$this->transEsc('Full text is not displayed to guests')?>
          </th>
          <td>
            <a class="login external" href="<?=$this->url('myresearch-home')?>" rel="nofollow">
              <strong><?=$this->transEsc('Login for full access')?></strong>
            </a>
          </td>
        </tr>
      <? endif; ?>
      <? $openUrl = $this->openUrl($this->driver, 'record');
         $openUrlActive = $openUrl->isActive();
         $html = $openUrl->renderTemplate();
      ?>
      <? if ($openUrlActive && strlen($html) > 0): ?>
      <tr>
          <th><?=$this->transEsc('Link Resolver')?>:</th>
          <td><?=$html?></td>                
      </tr>
      <? endif; ?>

      <? $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
        if (!empty($customLinks)): ?>
      <? foreach ($customLinks as $customLink): ?>
      <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
          $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
          $icon = isset($customLink['Icon']) ? $customLink['Icon'] : '';
          $name = isset($customLink['Text']) ? $customLink['Text'] : '';
          $icon = str_replace('http://', '//', $icon);
          $url = str_replace('http://', '//', $url);
      ?>
      <? if (strpos($url, 'redi-bw.de') === false): ?>
        <tr>
          <td>
            <a href="<?=$this->escapeHtmlAttr(str_replace('http://dx.doi.org', 'https://doi.org', $url))?>" target="_blank" title="<?=$mot?>" class="custom-link">
              <? if ($icon): ?><img src="<?=$icon?>" /> <? endif; ?><?=$name?>
            </a>              
          </td>
        </tr>
        <? endif; ?>
        <? if ($this->client()->is('only_first_customlink')): ?>
            <? break; ?>
        <? endif; ?>      
      <? endforeach; ?>
      <? endif; ?>
    
    </table>

    <div class="resultItemLine4 custom-links">

    
    </div>
  </div>
</div>
<div class="nofloat"></div>
