<!-- finc: recordDriver - solrDefault - collection-info -->
<? $this->headScript()->appendFile('collection_record.js'); ?>
<div class="row">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('collection-info', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
            <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
          </span>
      <? endif; ?>
  </div>

    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <? /* Use 9 columns if image is available, use 12 cols, if not -- CK */ ?>
  <div class="col-sm-9">
  <? else: ?>
    <div class="col-sm-12">
  <? endif; ?>

      <? /* For all finc-records we want to get rid of trailing special chars in the title and limit its length to 100 chars */ ?>
    <h2><?=$this->escapeHtml(preg_replace('/(\s[\/\.:]\s*)*$/', '', $this->truncate($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection(), 100)))?></h2>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->escapeHtml($summary)?></p>
    <? endif; ?>

    <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
      <strong><?=$this->transEsc("Saved in")?>:</strong>
    </div>

      <? /* finc-specific snippet - Begin - CK */ ?>
      <? /* Do not set to 'hidden' and make table below collapsible - CK */ ?>
      <a id="moreInfoToggle" href="#" class="accordion-toggler" data-toggle="collapse" aria-expanded="false"><?=$this->transEsc('Description')?></a>
    <?/* Display Main Details */?>
    <?/* finc: we use 'collapse in' to initially hide the content, CK */?>
      <table id="collectionInfo" class="table table-striped collapse in">
        <? /* Table summary not supported in html 5, finc-specific solution, CK */ ?>
            <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <? /* finc spec. authors dedupe; same in recordDriver - solrDefault - core, and other core.phtml files, CK */ ?>
      <? $authors = $this->driver->getDeduplicatedAuthors(); if ((isset($authors['main']) && count($authors['main'])) || (isset($authors['secondary']) && count($authors['secondary'])) || (isset($authors['corporate']) && count($authors['corporate'])) || (isset($authors['corporate_secondary']) && count($authors['corporate_secondary']))): ?>
        <? /* finc spec. authors dedupe - END */ ?>
        <tr>
          <th>
            <? /* BS version with '1. Verfasser ..., 2. Verfasser ... etc.' -- there is a larger block from 2016, dubbed 'Improved author indexing', see git hostroy of bootstrap/RecordDriver/SolrDefault/collection-info.phtml */
                /* <?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>:
            */ ?>

            <? /* finc version: 'Personen und Koerperschaften' */ ?>
            <?=$this->transEsc('Authors/Corporations')?>:
          </th>
          <td>
            <? if (isset($authors['main']) && count($authors['main'])): ?>
              <? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['main_orig'][$author])?" / ".array_pop($authors['main_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['secondary']) && count($authors['secondary'])): ?>
              <?=count($authors['main'])?'; ':''?>
              <? $i = 0; foreach ($authors['secondary'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['secondary_orig'][$author])?" / ".array_pop($authors['secondary_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['corporate']) && count($authors['corporate'])): ?>
              <?=count($authors['main'])||count($authors['secondary'])?'; ':''?>
              <? $i = 0; foreach ($authors['corporate'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['corporate_orig'][$author])?" / ".array_pop($authors['corporate_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['corporate_secondary']) && count($authors['corporate_secondary'])): ?>
              <?=count($authors['main'])||count($authors['secondary'])||count($authors['corporate'])?'; ':''?>
              <? $i = 0; foreach ($authors['corporate_secondary'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['corporate_secondary_orig'][$author])?" / ".array_pop($authors['corporate_secondary_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>
      <? /* finc version: 'Personen und Koerperschaften' - END */ ?>

      <? /* finc: NO corporate authors here but title details, CK */ ?>
      <? $titleDetails = $this->driver->getTitleDetails(); if (!empty($titleDetails)): ?>
        <tr>
          <th><?=$this->transEsc('Title')?>: </th>
          <td property="title">
            <? $i = 0; foreach ($titleDetails as $title): ?>
              <?=($i > 0 ? '<br />':'')?><?=$this->escapeHtml($title)?><? $i++ ;?>
            <? endforeach; ?>
          </td>
        </tr>
      <? else: ?>
        <tr>
          <th><?=$this->transEsc('Title')?>: </th>
          <td property="title"><?=$this->escapeHtml($this->driver->getShortTitle() . '  ' . $this->driver->getSubtitle() . '  ' . $this->driver->getTitleSection()) . ($this->driver->getTitleStatement() ? ' / ' . $this->driver->getTitleStatement() : '')?><br /><?=($this->driver->tryMethod('getTitleOrig') && $this->driver->getTitleOrig() != '' ? $this->escapeHtml($this->driver->getTitleOrig()) : '')?></td>
        </tr>
      <? endif; ?>
      <? /* finc: NO corporate authors here but title details - END */ ?>
      <? /* finc: dateSpan, CK */ ?>
      <? $dateSpan = $this->driver->getDateSpan(); if (!empty($dateSpan)): ?>
        <? $contentDisplayed = true; ?>
        <tr>
          <th><?=$this->transEsc('Dates of publication')?>: </th>
          <td>
            <? foreach ($dateSpan as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? /* finc: dateSpan - END */ ?>
    <? /* finc-specific snippet - END */ ?>

      <? if (count($summary) > 1): ?>
        <tr>
          <th><?=$this->transEsc('Summary')?>: </th>
          <td>
            <? foreach (array_slice($summary, 1) as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

        <? /* finc specific - formats - below, in BS here - CK */ ?>

        <? /* finc-specific: langs at the end of the table, not here - CK */ ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subject-line">
            <? $subject = ''; ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" class="subjectHeading" rel="nofollow"><?=$this->escapeHtml($subfield)?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
          // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $notes = $this->driver->getGeneralNotes(); if (!empty($notes)): ?>
        <tr>
          <th><?=$this->transEsc('Notes')?>: </th>
          <td>
            <? foreach ($notes as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
        <tr>
          <th><?=$this->transEsc('Production Credits')?>: </th>
          <td>
            <? foreach ($credits as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

        <? /* finc-specific hierarchyParentTitle - not in BS- CK */ ?>
      <? $hierarchyParentTitle = $this->driver->getHierarchyParentTitle(); if (!empty($hierarchyParentTitle) && empty($series)): ?>
        <tr>
          <th><?=$this->transEsc('Set Multipart')?>: </th>
          <td>
            <? $hierarchyParentId = $this->driver->getHierarchyParentID(); ?>
            <? foreach ($hierarchyParentTitle as $key=>$hTitle): ?>
              <? if(isset($hierarchyParentId[$key])): ?><a href="<?=$this->recordLink()->getUrl($hierarchyParentId[$key])?>"><? endif; ?><?=$this->escapeHtml($hTitle)?><? if(isset($hierarchyParentId[$key])): ?></a><? endif; ?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
        <? /* finc-specific hierarchyParentTitle - END */ ?>

      <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
        <tr>
          <th><?=$this->transEsc('ISBN')?>: </th>
          <td>
            <? foreach ($isbns as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
        <tr>
          <th><?=$this->transEsc('ISSN')?>: </th>
          <td>
            <? foreach ($issns as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* finc specific snippet - additionalNotes - not in BS - CK */ ?>
      <? $additionalNotes = (array) $this->driver->tryMethod('getAdditionalNotes'); if (!empty($additionalNotes)): ?>
        <tr>
          <th><?=$this->transEsc('Notes')?>: </th>
          <td>
            <? foreach ($additionalNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
        <? /* finc specific snippet - additionalNotes - END */ ?>

        <? /* finc specific snippet - formats - here, in BS above - CK */ ?>
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>
      <? /* finc specific snippet - formats - END */ ?>

      <? /* finc-specific langs here, at the end of the table -CK */ ?>
      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? $i = 0; foreach ($langs as $lang): ?><?=($i++ == 0)?'':', '?><?= $this->transEsc($lang)?><? endforeach; ?></td>
        </tr>
      <? endif; ?>
      <? /* finc-specific langs here, at the end of the table - END */ ?>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
<!-- finc: recordDriver - solrDefault - collection-info - END -->
