<!-- finc: RecordDriver - solrDefault - data-publicationDetails -->
<? if (!empty($data)): ?>
<div itemscope itemtype="http://schema.org/publisher">
    <? foreach ($data as $field): ?>
    <span property="publisher" typeof="Organization">
        <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
          <span property="location" typeof="Place">
            <span property="name"><?=$this->escapeHtml($pubPlace)?></span>
          </span>
        <? endif; ?>
        <? $pubName = $field->getName(); if (!empty($pubName)): ?>
            <span property="name"><?=$this->escapeHtml($pubName)?></span>
        <? endif; ?>
    </span>
    <span property="datePublished">
        <? /* do not show solr publish date #13993 - GG */ ?>
    <? /*$pubDateSort = $this->driver->tryMethod('getPublishDateSort');*/ ?>
    <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
        <?=$this->escapeHtml($pubDate)?>
    <? /*else: ?>
        <?=$this->escapeHtml($pubDateSort)*/?></span>
    <? endif; ?>
    </span><br/>
    <? endforeach; ?>
</div>
<? endif ?>
<!-- finc: RecordDriver - solrDefault - data-publicationDetails - END -->
