<!-- finc: RecordDriver - solrDefault - data-titleUniform -->
<? if (!empty($data)): ?>
    <tr>
        <th>
            <?=$this->driver->isRDA()
                ? $this->transEsc('rda_original_title')
                : $this->transEsc('non_rda_original_title')?>:
        </th>
        <td property="title">
            <?if (is_array($data)): ?>
                <a href="<?=$this->record($this->driver)->getLink('title', $data['title'])?>"><?=$this->escapeHtml($data['title'])?></a><? if (isset($data['lang'])): ?> &#x27E8;<?=$this->escapeHtml($data['lang'])?>&#x27E9;<? endif;?>
            <? else: ?>
                <a href="<?=$this->record($this->driver)->getLink('title', $data)?>"><?=$this->escapeHtml($data)?></a>
            <? endif; ?>
        </td>
    </tr>
<? endif; ?>
<!-- finc: RecordDriver - solrDefault - data-titleUniform - END -->
