<!-- finc: RecordDriver - solrDefault - data-authors -->
<?
$formatProperty = function ($datafield, $name, $label) {
if (count($datafield) == 0) {
return '';
}
$that = $this;
$translate = function ($str) use ($that, $label) {
return $that->transEsc($label . $str);
};
return '<span class="author-property-' . $name . '">(' . implode(', ', array_unique(array_map($translate, $datafield))) . ')</span>';
};
$formattedAuthors = [];
$types = [
    'main' => 'author',
    'secondary' => 'contributor',
    'corporate' => 'creator',
    'corporate_secondary' => 'contributor'
];
?>
<? foreach ($types as $type => $schemaLabel): ?>
    <? if (!empty($data[$type])): ?>
        <? foreach ($data[$type] as $author => $roles): ?>
            <? ob_start(); ?>
            <span class="author-data" property="<?=$this->escapeHtml($schemaLabel)?>">
                <a href="<?=$this->record($this->driver)->getLink('author', $author)?>">
            <?=$this->escapeHtml($author)?>
                </a>
                <?
                // Display additional data using the appropriate translation prefix
                // (for example, to render author roles correctly):
                if (!empty($requiredDataFields)) {
                    foreach ($requiredDataFields as $field) {
                        $name = $field['name'];
                        $prefix = isset($field['prefix']) ? $field['prefix'] : '';
                        // deprecated due to more flexible solution at core
                        // to-do: revision of indexing and finc specific treatment
                        // of roles in RecordDriver
                        if (count($roles) > 0 && $name == 'role') {
                            echo $formatProperty($roles, $name, $prefix);
                        }
                    }
                }
                ?>
    </span>
            <?
            // Strip whitespace before close tags to avoid spaces in front of commas:
            $formattedAuthors[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
            ob_end_clean();
            ?>
        <? endforeach; ?>
    <? endif; ?>
<? endforeach; ?>
<?=implode(', ', $formattedAuthors)?>
<!-- finc: RecordDriver - solrDefault - data-authors - END -->
