<?
$normalizedValue = preg_replace('/[^a-z0-9]/', '', strtolower($this->value));

// Convert normalizedValue to styles
// finc: same list of states for icons like in de_15 #13704 - VE
switch ($normalizedValue) {
    case 'marcfincpda':
        echo 'fa-home passive';
        break;
    case 'object':
        echo 'fa-home object';
        break;
    case 'localholdings':
        echo 'fa-home';
        break;
    case 'electronicresources':
        echo 'fa-globe';
        break;
    default:
        echo 'fa-book';
        break;
}
?>
