<!-- finc: recordDriver - solrDefault - toolbar -->
<?
    $addThis = $this->addThis();
    if (!empty($addThis)) {
      $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
    }

// Set up some variables for convenience:
$cart = $this->cart();
$cartId = $this->driver->getSourceIdentifier() . '|' . $this->driver->getUniqueId();
?>

<? /* finc: we use nav-stacked to display in sidebar, CK */ ?>
<ul class="record-nav nav nav-pills nav-stacked hidden-print">
  <? /* finc: we use the sr-only description, CK */ ?>
  <li class="sr-only"><?=$this->transEsc('Toolbar')?></li>
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
    <li>
      <a class="cite-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" rel="nofollow"><i class="fa fa-asterisk" aria-hidden="true"></i> <?=$this->transEsc('Cite this')?></a>
    </li>
  <? endif; ?>
  <? /* finc: we don't use sms, CK */ ?>
  <? /*
  <? if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
    <li><a class="sms-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" rel="nofollow"><i class="fa fa-mobile" aria-hidden="true"></i> <?=$this->transEsc('Text this')?></a></li>
  <? endif; ?>
  */ ?>
  <li>
    <a class="mail-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" rel="nofollow"><i class="fa fa-envelope"    aria-hidden="true"></i> <?=$this->transEsc('Email this')?></a>
  </li>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if (count($exportFormats) > 0): ?>
    <li class="dropdown">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow"><i class="fa fa-list-alt" aria-hidden="true"></i> <?=$this->transEsc('Export Record')?>
      </a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li>
            <a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main"
               <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>"
               rel="nofollow"><?=$this->transEsc('Export to')?><?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a>
          </li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>

  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <? /* finc: we use title, CK */ ?>
    <li>
      <?if ($this->permission()->allowDisplay('feature.Favorites')): ?>
      <a class="save-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>" rel="nofollow"><i class="fa fa-star" aria-hidden="true"></i> <?=$this->transEsc('Add to favorites')?>
      </a>
      <? elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
        <?=$block?>
      <? endif; ?>
    </li>
  <? endif; ?>
  <? if (!empty($addThis)): ?>
    <li>
      <a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-bookmark"  aria-hidden="true"></i> <?=$this->transEsc('Bookmark')?></a>
    </li>
  <? endif; ?>
  <li class="bookbag-menu">
  <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>
  </li>
</ul>
<!-- finc: recordDriver - solrDefault - toolbar - END -->
