<? if ($this->client()->getTag() == 'dlr-literatursuche'): ?>
    <h1>Literatursuche für den DLR-internen Bereich</h1>
    <p>Durchsuchen Sie komfortabel das DLR-Repositorium „elib“, den DLR-Bibliothekskatalog, 
        den NASA Technical Report Server und die Nationallizenzen. 
    </p>
    <p>Sie haben auch die Möglichkeit direkt auf die Datenbanken zuzugreifen:</p>

    <ul class="list-unstyled">
    <li><a href="http://elib.dlr.de/" class="external">elib</a></li>
    <li><a href="https://dlr-bibliothekskatalog.bsz-bw.de/" class="external">Bibliothekskatalog</a></li>
    <li><a href="https://dlr-archivkatalog.bsz-bw.de/" class="external">Archiv</a></li>
</ul>


<? else: ?>
    <h1>DLR Literatursuche</h1>
    <p>Durchsuchen Sie komfortabel das DLR-Repositorium „elib". </p>
    <p>Sie haben auch die Möglichkeit direkt auf das Repositorium  zuzugreifen:</p>
<ul  class="list-unstyled">
    <li><a href="http://elib.dlr.de/" class="external">elib</a></li>    
    <li><a href="https://dlr-archivkatalog.bsz-bw.de/" class="external">Archiv</a></li>
</ul>
<? endif; ?>