<? if ($this->client()->getTag() == 'dlr-literatursuche'): ?>
<h1>Literature Search &ndash; internal area</h1>
<p>Search comfortably the DLR-Repositorium "elib", the DLR Library Catalogue, 
    the NASA Technical Report Server and the National License. 
</p>
<p>You also have the possibility to search directly  in a specific data base: </p>
<ul class="list-unstyled">
    <li><a href="http://elib.dlr.de/" class="external">elib</a></li>
    <li><a href="https://dlr-bibliothekskatalog.bsz-bw.de/" class="external">Library Catalogue</a></li>
        <li><a href="https://dlr-archivkatalog.bsz-bw.de/" class="external">Archive</a></li>
</ul>

    

<? else: ?>
<h1>DLR Literature Search</h1>
<p>Search comfortably in the DLR-Repository "elib”.</p>
<p>You also have the possibility to search directly  in the specific data base: </p>
<ul  class="list-unstyled">
    <li><a href="http://elib.dlr.de/" class="external">elib</a></li>    
    <li><a href="https://dlr-archivkatalog.bsz-bw.de/" class="external">Archive</a></li>
</ul>

<? endif; ?>