<div class="mapongo row">
    <div class="col-sm-6">
        <h5>Mapongo</h5>
        <a href="<?=$this->linkurl?>" class="external hasicon">
            <img class="img-responsive" src="<?=$this->imageurl?>"/>
        </a>        
    </div>    
    <div class="col-sm-6 hidden-xs">
        <h5>QR-Code</h5>
        <a href="<?=$this->linkurl?>" class="external hasicon">
            <img class="img-responsive" src="<?=$this->qrurl?>"/>
        </a>        
    </div>
</div>