<div class="mapongo row">
    <? if (!empty($this->imageurl)): ?>
    <div class="col-sm-6">
        <a href="<?=$this->linkurl?>" class="external hasicon" title="Mapongo" data-toggle=tooltip">
            <img class="img-responsive" src="<?=$this->imageurl?>"/>
        </a>        
    </div>    
    <? endif; ?>
    <? if (!empty($this->qrurl)): ?>
    <div class="col-sm-6 hidden-xs">
        <a href="<?=$this->linkurl?>" class="external hasicon" title="Mapongo QR-Code" data-toggle=tooltip">
            <img class="img-responsive" src="<?=$this->qrurl?>"/>
        </a>        
    </div>
    <? endif; ?>
</div>