<script type="text/javascript">

    var orderStatus = 'no Order';
    if (typeof Cookies !== 'undefined') {
        switch (Cookies.getItem('orderStatus')) {
            case "1":
                var orderStatus = 'successfull';
                break;
            case "0":
                var orderStatus = 'not successfull';
                break;
        }
    }
    window.piwikAsyncInit = function () {
        try {
            <?php if ($this->siteId > 0): ?>
            var piwikTracker = Piwik.getTracker("<?=$this->piwikUrl?>piwik.php", <?=$this->siteId?>);
            piwikTracker.setCustomVariable(1, "IllOrder", orderStatus, "visit");
            piwikTracker.trackPageView();
            <?php endif; ?>
            <?php if ($this->globalSiteId > 0): ?>
            var piwik2 = Piwik.getTracker("<?=$this->piwikUrl?>piwik.php", 28);
            piwik2.setCustomVariable(1, "IllOrder", orderStatus, "visit");
            <?php if ($this->client()->isIsilSession() && $this->client()->hasIsilSession()): ?>
            piwik2.setCustomVariable(1, "sigel", '<?=$this->escapeHtml($this->client()->getSigel())?>', "visit");
            <?php endif; ?>
            piwik2.trackPageView();
            <?php endif; ?>
        } catch (err) {
        }
    };
</script>
<script type="text/javascript" src="<?= $this->piwikUrl ?>piwik.js"></script>
<noscript>
    <?php if ($this->siteId > 0): ?>
        <p><img src="<?= $this->piwikUrl ?>piwik.php?idsite=<?= $this->siteId ?>"
                style="border:0;" alt=""/></p>
    <?php endif; ?>
    <?php if ($this->globalSiteId > 0): ?>
        <p>
            <img src="<?= $this->piwikUrl ?>piwik.php?idsite=<?= $this->globalSiteId ?>"
                 style="border:0;" alt=""/></p>
    <?php endif; ?>
</noscript>

