<?php $rand = rand(0,1000)?>
<? if (!empty($link)): ?>
    <a href="<?=$link?>" class="external"><span id="clipboard-<?=$rand?>"><?=$this->escapeHtml($ppn)?></a> <small><? if(isset($label)):?>(<?=$this->transEsc($label)?>)<? endif; ?></small>
<? else: ?>
    <?=$this->escapeHtml($ppn)?>
<? endif; ?>
<span class="copy-clipboard-toggle" title="<?=$this->transEsc('clipboard')?>" data-clipboard-target="#clipboard-<?=$rand?>"><i class="fa fa-copy"></i></span>
