<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Erwerbungsvorschlag</title>
</head>
<body style="font-family: Arial, Verdana, sans-serif;">
<h2 style="padding:5px 0;">Erwerbungsvorschlag</h2>
<table width="800" border="0">
    <tr valign="top">
        <td width="390">
            Name: <strong><?=$user->lastname ?>, <?=$user->firstname ?></strong><br />
            Lesekarte-Nr.: <strong><?=$user->username ?></strong><br />
            Email: <a href="mailto:<?=$user->email ?>"><?=$user->email ?></a><br />
            <? /*if ($user->group): ?>Benutzergruppe: <?=$user->group ?><? endif;*/ ?>
        </td>
        <td width="20">&nbsp;</td>
        <td width="390">
            hat folgenden Titel zur Erwerbung empfohlen:<br />
            <br />
            <strong><?=$proposal ?></strong><br />
            <br />
            Begründung für Empfehlung:
            <br /><br />
            <strong><?=$reasons ?></strong>
            <br /><br /><br />
            für das Fachgebiet: <strong><?=$subject ?></strong><br />
            <br />
        </td>
    </tr>
    <tr valign="top">
        <td width="800" colspan="3">
            Zeitpunkt der Bestellung: <?=$time ?>
        </td>
    </tr>
</table>
</body>
</html>
