<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Erwerbungsvorschlag</title>
</head>
<body>
<h2>Erwerbungsvorschlag</h2>
<table>
    <tr valign="top">
        <td>
            Name: <strong><?=$user->lastname ?>, <?=$user->firstname ?></strong><br />
            Lesekarte-Nr.: <strong><?=$user->cat_username ?></strong><br />
            Email: <a href="mailto:<?=$user->email ?>"><?=$user->email ?></a><br />
            <? /*if ($user->group): ?>Benutzergruppe: <?=$user->group ?><? endif;*/ ?>
        </td>
        <td>&nbsp;</td>
        <td>
            hat folgenden Titel zur Erwerbung empfohlen:<br />
            <br />
            <strong><?=$proposal ?></strong><br />
            <br />
            Begründung für Empfehlung:
            <br /><br />
            <strong><?=$reasons ?></strong>
            <br /><br /><br />
            für das Fachgebiet: <strong><?=$subject ?></strong><br />
            <br />
        </td>
    </tr>
    <tr valign="top">
        <td colspan="3">
            Zeitpunkt der Bestellung: <?=$time ?>
        </td>
    </tr>
</table>
</body>
</html>
