== <?=$this->translate("Zeitschriftenbestellung")?> ==

Der Benutzer: <?=$this->patron['lastname']?>, <?=$this->patron['firstname']?>
Benutzerkarte: <?=$this->patron['cat_username']?>

hat folgenden Titel bestellt:

<?=$this->record['title']?>

Heft: <?=$this->volume?>

Jahrgang: <?=$this->year?>

Band: <?=$this->issue?>

von <?=$this->record['author']?>


Signatur: <?=$this->callnumber?>

Barcode: <?=$this->barcode?>

Weitere Informationen:

Standort: <?=$this->pickUpLocation?>

Anmerkungen zum Titel:
<? if (isset($this->item_notes)): foreach ($this->item_notes as $note): ?>
    * <?=$note?>

<? endforeach; endif; ?>

Kommentar des Benutzers:

<?=$this->comment?>
