<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title><?=$this->translate("Zeitschriftenbestellung")?></title>
</head>
<body style="font-family: Arial, Verdana, sans-serif;">
<table width="820" border="0">
    <tr valign="top">
        <td width="275">
            <strong>Signatur:</strong> <br>
            <?=$this->callnumber?>
        </td>
        <td width="275">
            <strong>Heft / Jahrgang / Band:</strong><br>
            <?=$this->volume?><br>
            <!--<strong>Barcode:</strong><br>-->
            <!--<?=$this->barcode?><br><br>-->
        </td>
        <td width="50">
            &nbsp;
        </td>
        <td width="220" rowspan="2" align="center" valign="top">
            <strong><?=$this->callnumber?></strong><br>
            Jahrgang/ Band/ Heft:<br>
            <strong><?=$this->volume?></strong><br>
            <strong><?=$this->record['title']?></strong><br><br>
        </td>
    </tr>
    <tr valign="top">
        <td colspan="2">
            <strong>Titel:</strong> <?=$this->record['title']?><br>
            <strong>Standort:</strong> <?=$this->pickUpLocation?><br>
            <? if (isset($this->item_notes)): ?>
            <strong>Anmerkungen zum Titel:</strong>
            <ul>
                <? foreach ($this->item_notes as $note): ?><li><?=$note?></li><? endforeach; ?>
            </ul>
            <? endif; ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr valign="bottom">
        <td colspan="2">
            <?if (!empty($this->comment)): ?>
            <br><br><strong>Kommentar des Benutzers:</strong><br>
            <?=$this->comment?>
            <? endif; ?>
            <strong>wurde bestellt von: </strong><br><br>
            <!--<strong>Email:</strong> <?=$this->patron['email']?><br><br><br>-->
            <strong>Name:</strong> <?=$this->patron['lastname']?>, <?=$this->patron['firstname']?><br>
            <strong>Benutzerkarte:</strong> <?=$this->patron['cat_username']?><br>
        </td>
        <td>&nbsp;</td>
        <td align="center" valign="top" style="font-size: 16px">
            <strong><?=$this->patron['lastname']?>, <?=$this->patron['firstname']?></strong><br>
            <strong><?=$this->patron['cat_username']?></strong>
        </td>
    </tr>
</table>
</body>
</html>
