<?=$this->doctype('HTML5')?>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
    <title>Fehlermeldung durch Benutzer</title>
</head>
<body style="font-family: Arial, Verdana, sans-serif;">
<h2 style="padding:10px 0;">Fehlermeldung durch Benutzer</h2>
<table width="800" border="0">
    <? if ($reply_requested): ?>
        <? if (isset($lastname) && isset($firstname)): ?>
    <tr>
        <td width="30%">Name:</td>
        <td width="70%"><strong><?=$lastname?>, <?=$firstname?></strong></td>
    </tr>
        <? endif; ?>
        <? if (isset($email)): ?>
    <tr>
        <td width="30%">Email:</td>
        <td width="70%"><a href="mailto:<?=$email?>"><?=$email?></a></td>
    </tr>
    <tr>
        <td width="100%" colspan="2"><strong>Um Rückmeldung wird gebeten.</strong></td>
    </tr>
        <? endif; ?>
    <? endif; ?>
    <? if ($comment): ?>
    <tr>
        <td width="30%">Meldung des Benutzers::</td>
        <td width="70%"><span style="font-size: 12px"><?= $comment ?></span></td>
    </tr>
    <? endif; ?>
    <tr>
        <td width="30%">Gemeldeter Titel:</td>
        <td width="70%">
            <strong><?= $title ?></strong><br/>
            <? if ($author): ?>von
                <? foreach ($author as $auth): ?>
                    <?= $auth ?>
                <? endforeach; ?>
            <? endif; ?><br/>
            <br/>
            Link: <a href="<?=$this->serverUrl($this->recordLink()->getUrl($driver))?>" title="<?= $title ?>"><?=$this->serverUrl($this->recordLink()->getUrl($driver))?></a><br/>
            Katalog-ID: <a href="<?= $this->serverUrl($this->recordLink()->getUrl($driver)) ?>"
                           title="<?= $title ?>"><?= $id ?></a><br/>
        </td>
    </tr>
    <tr valign="top">
        <td width="100%" colspan="2">
            Zeitpunkt der Meldung: <?= $timestamp ?>
        </td>
    </tr>
</table>
</body>
</html>