<?=$this->doctype('HTML5')?>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
    <title>Zurücksetzen des Passwortes für Benutzer</title>
</head>
<body style="font-family: Arial, Verdana, sans-serif;">
<h2 style="padding:10px 0;">Zurücksetzen des Passwortes für Benutzer</h2>
<table width="800" border="0">
    <? if (isset($lastname) && isset($firstname)): ?>
    <tr>
        <td width="30%">Name:</td>
        <td width="70%"><strong><?=$lastname?>, <?=$firstname?></strong></td>
    </tr>
    <? endif; ?>
    <? if (isset($username)): ?>
        <tr>
            <td width="30%">Benutzernummer:</td>
            <td width="70%"><strong><?=$username?></strong></td>
        </tr>
    <? endif; ?>
    <? if (isset($email)): ?>
    <tr>
        <td width="30%">Email:</td>
        <td width="70%"><a href="mailto:<?=$email?>"><?=$email?></a></td>
    </tr>
    <? endif; ?>
    <tr valign="top">
        <td width="100%" colspan="2">
            Zeitpunkt der Anfrage: <?= $timestamp ?>
        </td>
    </tr>
</table>
</body>
</html>