<!-- finc: search - pagination -->
<? if ($this->pageCount): ?>
  <ul class="pagination">
    <? if (isset($this->previous)): ?>
      <? if (!isset($this->options['disableFirst']) || !$this->options['disableFirst']): ?>
        <li class="first"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>">[1]</a></li>
      <? endif; ?>
      <li class="page-prev"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>">&laquo; <span class="hidden-xs"><?=$this->transEsc('Prev')?></span></a></li>
    <? endif; ?>

    <? if (count($this->pagesInRange) > 1): ?>
      <? foreach ($this->pagesInRange as $page): ?>
        <? if ($page != $this->current): ?>
          <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
        <? else: ?>
          <li class="active"><span><?=$page?></span></li>
        <? endif; ?>
      <? endforeach; ?>
    <? endif; ?>

    <? if (isset($this->next)): ?>
      <li class="page-next"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><span class="hidden-xs"><?=$this->transEsc('Next');?></span> &raquo;</a></li>
      <? if (!isset($this->options['disableLast']) || !$this->options['disableLast']): ?>
        <li class="last"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>">[<?=$this->pageCount?>]</a></li>
      <? endif; ?>
    <? endif; ?>
  </ul>
<? endif; ?>
<!-- finc: search - pagination - END -->
