<? /* Display series section if at least one series exists. */ ?>
<?php $series = $this->driver->getSeries();
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

if (!empty($series)): ?>
    <tr>
        <th><?= $this->transEsc('Series') ?>:</th>
        <td>
            <?php foreach ($series as $field): ?>
                <? /* Depending on the record driver, $field may either be an array with
       "name" and "number" keys or a flat string containing only the series
       name.  We should account for both cases to maximize compatibility. */ ?>
                <?php if (is_array($field)): ?>
                    <?php if (!empty($field['name'])): ?>
                        <a class="searchicon"
                           href="<?= $this->record($this->driver)->getLink('series', $field['name']) ?>"><?= $this->escapeHtml($field['name']) ?></a>
                        <?php if (!empty($field['number'])): ?>
                            <?= $this->escapeHtml($field['number']) ?>
                        <?php endif; ?>
                        <br/>
                    <?php endif; ?>
                <?php else: ?>
                    <a class="searchicon"
                       href="<?= $this->record($this->driver)->getLink('series', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                    <br/>
                <?php endif; ?>
            <?php endforeach; ?>
        </td>
    </tr>
<?php endif; ?>