<?php $subjects = $this->driver->getAllSubjectHeadings();
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

if (!empty($subjects)): ?>
    <tr>
        <th><?= $this->transEsc('Subjects') ?>:</th>
        <td>
            <?php $count = 0 ?>
            <?php foreach ($subjects as $field): ?>
                <span class="subjectLine" property="keywords">
        <?php $subject = ''; ?>
                    <?php if (is_array($field) && count($field) == 1): $field = explode('--', $field[0]); ?>
                        <?php $i = 0;
                        foreach ($field as $subfield): ?>
                            <?= ($i++ == 0) ? '' : ' &gt; ' ?>
                            <?php $subject = trim($subject . ' ' . $subfield); ?>
                            <a class="searchicon <?php if ($count >= 5): ?>hidden <?php endif; ?>"
                               title="<?= $this->escapeHtmlAttr($subject) ?>"
                               href="<?= $this->record($this->driver)->getLink('topic', $subject, $this->searchClassId) ?>"><?= trim($this->escapeHtml($subfield)) ?></a>
                            <?php $count++ ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php foreach ($field as $subfield): ?>
                            <a class="searchicon <?php if ($count >= 5): ?>hidden <?php endif; ?>"
                               title="<?= $this->escapeHtmlAttr($subfield) ?>"
                               href="<?= $this->record($this->driver)->getLink('subject', $subfield, $this->searchClassId) ?>"><?= trim($this->escapeHtml($subfield)) ?></a>
                            <?php $count++ ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
      </span>
            <?php endforeach; ?>
            <?php if ($count >= 5): ?>
                <a href="#" class="showmore"><?= $this->transEsc('Showmore') ?></a>
            <? endif; ?>
        </td>
    </tr>
    <?php unset($subjects) ?>
<?php endif; ?>

<?php if ($this->driver instanceof \Bsz\RecordDriver\SolrDlrmarc): ?>

    <? $subjects = $this->driver->getAllRVKSubjectHeadings();
    if (!empty($subjects)): ?>
        <tr>
            <th>RVK-<?= $this->transEsc('Subjects') ?>:</th>
            <td>
                <div class="subjectLine" property="keywords">
                    <?php $count = 0; ?>
                    <?php foreach ($subjects as $field): ?>
                        <?php $subject = ''; ?>
                        <?php if (is_array($field) && count($field) == 1): $field = explode('--', $field[0]); ?>
                            <?php $i = 0;
                            foreach ($field as $subfield): ?>
                                <?= ($i++ == 0) ? '' : ' &gt; ' ?>
                                <?php $subject = trim($subject . ' ' . $subfield); ?>
                                <?php //Die Links hatten eine Klasse backlink. Diese führt mit einer
                                // bestimmten Browsererweiterung (uBlock / AdBlock?) zu komischer
                                // Darstellung beim Hovern
                                ?>
                                <a class="searchicon"
                                   title="<?= $this->escapeHtmlAttr($subject) ?>"
                                   href="<?= $this->record($this->driver)->getLink('subject', $subject, $this->searchClassId) ?>"><?= trim($this->escapeHtml($subfield)) ?></a>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <a class="searchicon <?php if ($count >= 5): ?>hidden <?php endif; ?>"
                               title="<?= $this->escapeHtmlAttr($field) ?>"
                               href="<?= $this->record($this->driver)->getLink('rvkheading', $field, $this->searchClassId) ?>">
                                <?= trim($this->escapeHtml($field)) ?></a>
                        <?php endif; ?>
                        <?php $count++ ?>
                    <?php endforeach; ?>
                    <?php if ($count > 5): ?>
                        <a href="#"
                           class="showmore"><?= $this->transEsc('Showmore') ?></a>
                    <?php endif; ?>
                </div>
            </td>
        </tr>
    <?php endif; ?>
<?php endif; ?>



