<p>The <strong>Library Catalogue</strong> searches the holdings of the library of
    the University of Music, Karlsruhe: you can find books,
    sheet music, CDs, DVDs, videos, e-books, journals… partly even the works
    included in article compilations, music collections, etc.</p>
<p>In the <strong>Digital Library</strong> tab you will find digital full texts of
    magazine articles, other e-books, music tracks (Naxos Music Library), sheet music
    PDFs (IMSLP) and other scientific / artistic literature from licensed and free
    databases.
</p>
<p>The tab „<strong>Other libraries</strong>“ offers the options of searching the
    holdings of other libraries near Stuttgart or even of libraries all over Germany.
</p>