<?php if (!empty($this->openUrl) && !empty($this->openUrlBase)): ?>
    <a href="<?= $this->escapeHtmlAttr($this->openUrlBase . '?' . $this->openUrl) ?>"
       class="<?php if (!empty($this->openUrlGraphic)): ?>hasicon <?php endif; ?>external"
       title="<?= $this->transEsc('redi_link_title') ?>">
        <?php if (!empty($this->openUrlGraphic)): ?>
            <img src="<?= $this->escapeHtmlAttr($this->openUrlGraphic) ?>"
                 alt="<?= $this->transEsc('redi_link_text') ?>"
                 title="<?= $this->transEsc('redi_link_text') ?>"/>
        <?php else: ?>
            <?= $this->transEsc('redi_link_text') ?>
        <?php endif; ?>
    </a><br/>
<?php endif; ?>
