<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

  // Set page title.
  $this->headTitle($this->translate('Email this Search'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->transEsc('Email this Search') . '</li>';
?>
<div class="col-sm-12">
    <h2><?=$this->transEsc('Email this Search') ?></h2>
    <?=$this->flashmessages()?>
    <form class="form-search-email" method="post" name="emailSearch">
      <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
      <?=$this->render('Helpers/email-form-fields.phtml')?>
    </form>
</div>
