<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = $this->render('search/searchbox.phtml');

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
      $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;


  $library = $this->libraries()->getFirstActive($this->client()->getIsils());

?>
<div class="col-sm-12 searchHomeContent">
<?php
  $ilsStatusScript = <<<JS
$(document).ready(function() {
  $.ajax({
      dataType: 'json',
      method: 'GET',
      data: {'offlineModeMsg':'ils_offline_home_message'},
      url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
      success: function(response) {
          $('.searchHomeContent').prepend(response.data);
      }
  });
});
JS;
  ?>
  <?php if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <?php $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <?php endif; ?>
  <div class="row">
      <?php if ($this->client()->isIsilSession()): ?>
          <div class="col-xs-5 col-sm-4 col-md-3">
              <img class="img-responsive" src="<?=$this->imageLink('logo/bsz.svg')?>" alt="BSZ Logo" />
          </div>
      <?php else: ?>
          <div class="col-md-8 col-xs-5  hidden-sm hidden-xs">
              <?php if ($this->imageLink($this->clientAsset()->getHeader())): ?>
              <img src="<?=$this->imageLink($this->clientAsset()->getHeader()) ?>" class="img-responsive" alt="Aufmacherbild" />
              <?php endif; ?>
          </div>
      <?php endif; ?>
      <div class="col-xs-6 col-sm-4 pull-right">
          <?=$this->clientAsset()->getLogoHtml()?>
      </div>
  </div>
  <div class="row ">
      <div class="col-sm-12">
          <?php if (($this->client()->isIsilSession() && empty($this->client()->getIsils())) || !$this->client()->isIsilSession()): ?>
            <h2><?=$this->transEsc('homepage_heading')?> <small><?=$this->transEsc('homepage_subheading')?></small></h2>
          <?php elseif ($this->client()->isIsilSession() && $this->client()->hasIsilSession()): ?>
            <h2><?=$this->escapeHtml((string)$library)?> <small><?=$this->transEsc('homepage_subheading')?></small></h2>
          <?php endif; ?>
          <?php if (strpos($this->translate('homepage_text'), '<') !== false): ?>
                <?=$this->translate('homepage_text')?>
          <?php else: ?>
                <?=$this->transEsc('homepage_text')?>
          <?php endif; ?>

          <?php if ($this->client()->isIsilSession()): ?>
              <?=$this->partial('bsz/illselector.phtml')?>
          <?php endif; ?>
          <?php // Set Maintenance hints with SetEnv MAINTENANCE_MODE "..." in httpd-vufind.conf?>
        </div>
  </div>
    <div class="row">
        <div class="col-sm-12 ">
            <?=$this->flashmessages()?>
            <div class="specialhome">
                <?php if ($this->client()->is('pecial_home')): ?>
                    <?= $this->render('bsz/'.$this->client()->getTag().'/'.$this->layout()->userLang.'.phtml')?>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php if ($this->client()->getRSSFeed() !== null): ?>
        <div id="RSSFeedResultsDeferred" class="col-sm-6">
            <p><?=$this->transEsc("Loading")?>... <img src="<?=$this->imageLink('ajax_loading.gif')?>" /></p>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, "var url = VuFind.path + '/AJAX/Recommend?mod=StartPageNews';$('#RSSFeedResultsDeferred').load(url);", 'SET')?>        </div>
    <?php endif; ?>


  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>

  <?//$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
</div>

<?php if (isset($facetList) && is_array($facetList)): ?>
  <div class="search-home-facets">
    <?php foreach ($facetList as $field => $details): ?>
      <?php if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        <?php $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <?php $this->headScript()->appendFile('facets.js'); ?>
        <?php $sort = isset($this->hierarchicalFacetSortOptions[$field]) ? $this->hierarchicalFacetSortOptions[$field] : ''; ?>
        <?php
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <div class="home-facet <?=$this->escapeHtmlAttr($field) ?>">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="all">
          </div>
        </div>
        <noscript>
      <?php endif; ?>
      <?php $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
      <div class="home-facet <?=$this->escapeHtmlAttr($field) ?>">
        <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
        <div class="home-facet-container">
          <ul class="home-facet-list">
          <?php /* Special case: two columns for LC call numbers... */ ?>
          <?php if ($field == "callnumber-first"): ?>
            <?php $i = 0; foreach ($sortedList as $url => $value): ?>
              <?php if (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <?php else: $i--; ?>
              <?php endif; ?>
              <?php if (++$i == 10): ?>
                  </ul><ul class="home-facet-list">
              <?php endif; ?>
            <?php endforeach; ?>
          <?php /* Special case: collections */ ?>
          <?php elseif ($field == 'hierarchy_top_title'): ?>
            <?php $i = 0; foreach ($sortedList as $url => $value): ?>
              <?php if (++$i > 10): ?>
                <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <?php break; ?>
                <?php endif; ?>
                <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
            <?php endforeach; ?>
          <?php else: ?>
            <?php $i = 0; foreach ($sortedList as $url => $value): ?>
              <?php if (++$i > 10): ?>
                <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <?php break; ?>
              <?php elseif (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <?php else: $i--; ?>
              <?php endif; ?>
            <?php endforeach; ?>
          <?php endif; ?>
          </ul>
        </div>
      </div>
      <?php if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        </noscript>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
