<h1>Baustelle von B21 - Betreten strengstens Verboten. Kinder haften für ihre Eltern. </h1>
<p>Why is this so ugly? It's VuFind. </p>
<div class="searchHomeContent">
  <div class="search-hero" role="search">
    <? require(__DIR__ . '/../../../bootstrap3/templates/search/home.phtml'); ?>
    <div class="image-credit">
      Yosemite Valley. Photo by <a class="name" href="https://unsplash.com/@heytowner">John Towner</a>.
    </div>
  </div>
</div>
