<?  /*
     * This template is used for advanced search only
     */

    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    //$lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>


<? if ($this->searchType == 'advanced'): ?>
<div id="searchForm">
    <? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>
    <? if(count($searchTabs) > 1): ?>
      <ul class="nav nav-tabs">
      <? foreach ($searchTabs as $tab): ?>
        <li<?=$tab['selected'] ? ' class="active"' : ''?>>
           <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>"><?=$this->transEsc($tab['label']); ?></a>
        </li>
      <? endforeach; ?>
      </ul>
      <? endif; ?>
  </div>
<? endif; ?>

