<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = $this->client()->isIsilSession() ? 'Interlending' : 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    //$lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
    // prevent adv search strings from being displayed in search bar
    $lookfor = strpos($this->lookfor, '(') !== FALSE ? '' : $this->escapeHtmlAttr($this->lookfor);
?>

<? if(($this->client()->isIsilSession() && $this->client()->hasIsilSession()) || !$this->client()->isIsilSession()): ?>

  <form role="search" class="navbar-form navbar-left" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" autocomplete="off">
    <? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>    
    <? if (count($searchTabs) > 1): ?>
      <ul class="nav nav-tabs">
      <? foreach ($searchTabs as $tab): ?>
        <li<?=$tab['selected'] ? ' class="active"' : ''?>>
            <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>"><i class="fa <?=$this->escapeHTMLAttr($tab['icon'])?>"></i><span class="text"><?=$this->transEsc($tab['label']); ?></span></a>
        </li>
      <? endforeach; ?>
      </ul>
    <? endif; ?>
    <label for="searchForm_lookfor" class="sr-only"><?=$this->transEsc('enter_search_keyword')?></label>
    <input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" id="searchForm_lookfor" type="text" name="lookfor" value="<?=$lookfor?>" placeholder="<?=$this->transEsc('enter_search_keyword')?>" <? if ($this->client()->is('autofocus')): ?> autofocus="true"<? endif; ?>/>
    <? if($this->client()->is('searchbox_dropdown')): ?>
    <? if ($handlerCount > 1): ?>
      <select class="form-control" id="searchForm_type" name="type" data-native-menu="false">
        <? foreach ($handlers as $handler): ?>
          <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
        <? endforeach; ?>
      </select>
    <? elseif ($handlerCount == 1): ?>
      <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
    <? endif; ?>
    <? endif; ?>
    
        <button type="submit" class="btn btn-info"><i class="fa fa-search"></i></button>
        <? if (!isset($frame) && $advSearch && $this->client()->is('advanced_search_button')): ?>
        <a href="<?=$this->url($advSearch)?>" class="btn btn-link advancedSearchLink hidden-xs" title="<?=$this->transEsc("Advanced")?>">
            <i class="fa fa-search-plus"></i>
            <span class="text"><?=$this->transEsc("Advanced")?></span>
        </a>
        <? endif; ?>

    <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
      <br />
      <? foreach ($shards as $shard => $val): ?>
        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
      <? endforeach; ?>
    <? endif; ?>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <div class="checkbox hidden">
        <label>
          <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </div>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
    <div class="nofloat"></div>    
  </form>
<? endif; ?>
