<div class="alert alert-danger">
<p>Aufgrund der Änderungen der Corona-Verordnung und der Corona-Verordnung Studienbetrieb und Kunst des Landes passen wir unser <a href="https://www.wlb-stuttgart.de/die-wlb/moderierte-teiloeffnung/" class="external">Hygienekonzept</a> an:
<ul>
    <li>Die Hölderlin-Ausstellung, Führungen und Veranstaltungen sind einstweilen abgesagt. Eine Besichtigung der Bibliothek auf eigene Faust ist untersagt.</li>
    <li>Bitte nutzen Sie wieder verstärkt den Versand für <a href="https://www.wlb-stuttgart.de/service/ausleihe/#c22085" class="external">Ausleihe</a> und <a href="https://www.wlb-stuttgart.de/service/ausleihe/#c1877" class="external">Rückgabe<a/></li>
    <li>Während Ihres Besuches ist durchweg die Alltagsmaske zu tragen.</li>
</ul>
Wir bitten Sie um Verständnis und Unterstützung dieser Maßnahmen. Wir wollen die Bibliothek offen halten.

</p>
</div>
