<div class="alert alert-danger">
    <p>
        <strong>Schließung der WLB verlängert</strong><br><br/>

        Die Württembergische Landesbibliothek bleibt gemäß der Corona-Verordnung
        des Landes Baden-Württemberg  vom 15.12.2020 § 1d Abs. 1 mit Bezug auf §
        13 Abs. 2 Nr. 2 <strong>bis auf Weiteres geschlossen.</strong> <br/>
        Wir werden Sie an dieser Stelle weiterhin zeitnah über alle Änderungen
        in unserem Service-Angebot informieren. Bis dahin gelten unsere
        bisherigen Regelungen.
        <br/>
        Für die Dauer der Schließzeit wird das Mahnverfahren ausgesetzt. Die
        Buchrückgabe ist während der Schließung nur per Post möglich.
    </p>
</div>
