<div class="alert alert-danger">
    <p>Zur Zeit werden von der Landesregierung die Corona-Verordnungen
    überarbeitet. Von den Ergebnissen hängt ab, inwieweit wir unsere
    Angebote einschränken müssen. Bitte informieren Sie sich vor Ihrem
    Kommen über unsere Homepage. Die einstweilen weiter geltenden
        Regelungen finden Sie <a class="external" href="https://www.wlb-stuttgart.de/die-wlb/moderierte-teiloeffnung">hier.</a></p>
</div>
