<div class="alert alert-danger">
    <p>
        <strong>Schließung der Bibliothek vom 16.12.2020 bis 10.1.2021</strong><br><br/>

        Aufgrund der Coronaverordnung des Landes Baden-Württemberg vom 15.12.2020 § 1d Abs. 1 mit Bezug auf § 13 Abs. 2 Nr. 2 wird die Landesbibliothek vom <b>16.12.2020 bis 10.1.2021</b> für den Publikumsverkehr <b>geschlossen</b>. Das Mahnverfahren wird in dieser Zeit ausgesetzt. <br>
        Die Buchrückgabe ist während der Schließung nur per Post möglich. Bitte informieren Sie sich kurz vor Ihrem Kommen im Neuen Jahr auf der Homepage über die Öffnungszeiten.<br>
        Wir bitten um Entschuldigung für die Einschränkungen und die Kurzfristigkeit Ihrer Mitteilung. <br/><br/>

        Trotz allem gute Feiertage und die besten Wünsche für das neue Jahr. <br/>

        Ihre Landesbibliothek
    </p>
</div>