<div class="alert alert-danger">
    <p>Derzeit ist die Bestellfunktion leider infolge der Schließung außer Betrieb. Bitte informieren Sie sich über die <a class="external" href="https://www.wlb-stuttgart.de/die-wlb/schliessung-der-bibliothek/" target="_blank"><b>bestehenden Angebote</b></a>.</p>
    <p>The state government is currently implementing the Corona ordinances
        revised. The results depend on the extent to which we our
        Have to restrict offers. Please inform yourself before your
        Come through our homepage. The currently still valid Regulations can be found
        <a class="external" href="https://www.wlb-stuttgart.de/die-wlb/moderierte-teiloeffnung">here.</a>.</p>
</div>