<div class="alert alert-danger">
    <p>
        <strong>Closure of the WLB extended</strong><br><br/>

        The Württemberg State Library remains in accordance with the Corona Regulation
        of the state of Baden-Württemberg from December 15, 2020 Section 1d Paragraph 1 with reference to Section
        13 Para. 2 No. 2 <strong> closed until further notice. </strong> <br/>
        We will keep you informed of any changes at this point
        inform in our service offer. Until then, ours apply
        previous regulations.
        <br/>
        The remind procedure is suspended for the duration of the closing time. The
        Books can only be returned by post during the closure.
    </p>
</div>
