<?php


// Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  $this->headScript()->appendFile("vendor/jquery.tablesorter.min.js");

  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

// Set up breadcrumbs:
/*
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
  '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
*/
$this->layout()->title = $this->driver->getShortTitle();

use Zend\View\Helper\HeadScript;

?>

<?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
<div class="col-sm-2 col-sm-offset-5 text-center">
    <a class="backtosearch text-link"
       title="<?= $this->transEsc('Back to Search') ?>"
       href="<?= $this->searchMemory()->getLastSearchUrl('', '', '', false) ?>">
       <i class="fa fa-chevron-left"></i> <?=$this->transEsc('Back to Search')?>
    </a>
</div>
<div class="col-sm-4 col-sm-offset-4">
    <ul class="pager hidden-print">

        <?php if ($this->scrollData['previousRecord']): ?>
            <?php if ($this->scrollData['firstRecord']): ?>
                <li>
                    <a class="btn btn-default"
                       href="<?= $this->recordLink()->getUrl($this->scrollData['firstRecord']) ?>"
                       title="<?= $this->transEsc('First Search Result') ?>"
                       rel="nofollow"><i class="fa fa-chevron-left"></i><i
                                class="fa fa-chevron-left"></i></a>
                </li>
            <?php endif; ?>
            <li>
                <a class="previous btn btn-default"
                   href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>"
                   title="<?= $this->transEsc('Previous Search Result') ?>"
                   rel="nofollow"><i class="fa fa-chevron-left"></i></a>
            </li>
        <?php else: ?>
            <?php if ($this->scrollData['firstRecord']): ?>
                <li class="disabled"><a href="#" class="btn btn-default disabled"><i
                                class="fa fa-chevron-left"></i><i
                                class="fa fa-chevron-left"></i></a></li>
            <?php endif; ?>
            <li class="disabled"><a class="btn btn-default disabled" href="#"><i
                            class="fa fa-chevron-left"></i></a></li>
        <?php endif; ?>
        <li><?= $this->transEsc('of_num_results', [
            '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
            '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
            ]) ?></li>
        <?php if ($this->scrollData['nextRecord']): ?>
            <li>
                <a class="next btn btn-default" class="next"
                   href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>"
                   title="<?= $this->transEsc('Next Search Result') ?>"
                   rel="nofollow"><i class="fa fa-chevron-right"></i></a>
            </li>
            <?php if ($this->scrollData['lastRecord']): ?>
                <li>
                    <a class="btn btn-default"
                       href="<?= $this->recordLink()->getUrl($this->scrollData['lastRecord']) ?>"
                       title="<?= $this->transEsc('Last Search Result') ?>"
                       rel="nofollow"><i class="fa fa-chevron-right"></i><i
                                class="fa fa-chevron-right"></i></a>
                </li>
            <?php endif; ?>
        <?php else: ?>
            <li class="disabled"><a class="btn btn-default disabled" href="#"><i
                            class="fa fa-chevron-right"></i></a></li>
            <?php if ($this->scrollData['lastRecord']): ?>
                <li class="disabled"><a class="btn btn-default disabled" href="#"><i
                                class="fa fa-chevron-right"></i><i
                                class="fa fa-chevron-right"></i></a></li>
            <?php endif; ?>
        <?php endif; ?>
    </ul>
</div>

<?php endif; ?>

<?= $this->record($this->driver)->getToolbar() ?>

<div class="record source<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>">
    <div class="<?= $this->layoutClass('mainbody_details') ?>">
        <input type="hidden"
               value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>"
               class="hiddenId"/>
        <input type="hidden"
               value="<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>"
               class="hiddenSource"/>
        <?= $this->flashmessages() ?>
        <?= $this->record($this->driver)->getCoreMetadata() ?>

        <?php if (count($this->tabs) > 0): ?>
            <a name="tabnav"></a>
            <div class="record-tabs">
                <ul class="nav nav-tabs">
                    <?php foreach ($this->tabs as $tab => $obj): ?>
                        <?php // add current tab to breadcrumbs if applicable:
                        $desc = $obj->getDescription();
                        $tab_classes = [];
                        if (0 === strcasecmp($this->activeTab, $tab)) {
                            if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                                $tab_classes[] = 'active';
                            }
                            $tab_classes[] = 'initiallyActive';
                            $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
                                '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
                            $activeTabObj = $obj;
                        }

                        if (!$obj->isVisible()) {
                            $tab_classes[] = 'hidden';
                        }
                        if (!$obj->supportsAjax()) {
                            $tab_classes[] = 'noajax';
                        }
                        ?>
                        <li <?= count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : '' ?>>
                            <a class="<?= strtolower($tab) ?>"
                               href="<?= $this->recordLink()->getTabUrl($this->driver, $tab) ?>#tabnav"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)): ?> data-background<?php endif ?>><?= $this->transEsc($desc) ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <div class="tab-content">
                    <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
                        <div class="tab-pane active <?= $this->activeTab ?>-tab">
                            <?= isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <?= $this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : '' ?>
    </div>

    <div class="<?= $this->layoutClass('sidebar') ?>">
        <?php foreach ($this->related()->getList($this->driver) as $current): ?>
            <?= $this->related()->render($current) ?>
        <?php endforeach; ?>
    </div>
</div>
<?= $this->inlineScript(HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
