<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */


// Set page title.
$this->headTitle($this->translate('Volumes') . ': ' . $this->driver->getBreadcrumb());

$content = $this->tab->getContent();

?>
<?php if (isset($content) && count($content) > 0): ?>
    <?php $rand = rand(0, 9999) ?>
    <table class="table table-striped table-condensed tablesorter">
        <thead>
        <tr>
            <th class="col-xs-8"><?= $this->transEsc('Title') ?></th>
            <th class="col-xs-1"><?= $this->transEsc('Year') ?></th>
            <th class="col-xs-2"><?= $this->transEsc('Author') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $count = 1;
        foreach ($content as $result): ?>
            <tr <?php if ($count > 10): ?> class="showmore-<?= $rand ?> collapse multi-collapse"<?php endif; ?>>
                <td><a class="internal"
                       href="<?= $this->recordLink()->getUrl($result) ?>"><?= $this->string()->cleanEsc($result->getTitle()) ?> <?= $this->string()->cleanEsc($result->getTitleSection()) ?></a>
                </td>
                <td><?= implode(', ', $result->getPublicationDates()) ?></td>
                <td><?= $result->getPrimaryAuthor() ?></td>
            </tr>
            <?php $count++ ?>
        <?php endforeach; ?>
        </tbody>
        <?php if ($count > 10): ?>
            <tfoot>
            <tr>
                <td>
                    <button class="btn btn-info btn-xs text-toggle"
                            data-toggle="collapse"
                            data-target=".showmore-<?= $rand ?>"
                            aria-expanded="false"
                            data-alttext="<?= $this->transEsc('Showless') ?>">
                        <?= $this->transEsc('Showmore') ?>
                    </button>
                </td>
            </tr>
            </tfoot>
        <?php endif; ?>
    </table>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tablesorter').tablesorter({
                sortList: [[1, 1]]
            });
        });
    </script>
<?php else: ?>
    <p><?= $this->transEsc('nohit_heading') ?></p>
<?php endif; ?>
