<?
    // Set page title.
    $this->headTitle($this->translate('Volumes') . ': ' . $this->driver->getBreadcrumb());
    
    if($this->driver->tryMethod('isCollection') ||  $this->driver->tryMethod('isPart')) {    
        $content = $this->tab->getContent();        
    }
    

?>
<? if(isset($content) && count($content) > 0): ?>
<? $rand = rand(0, 9999)?>
<table class="table table-striped table-condensed" id="showmore-items-<?=$rand?>">
    <tr>
        <th class="col-xs-8"><?=$this->transEsc('Title')?></th>        
        <th class="col-xs-1"><?=$this->transEsc('Year')?></th>
        <th class="col-xs-2"><?=$this->transEsc('Author')?></th>        
    </tr>
    <? $count = 1; foreach ($content as $result): ?>
    <tr <? if ($count > 20): ?> class="showmore-item hidden"<? endif; ?>>
        <td><a class="internal"  href="<?=$this->recordLink()->getUrl($result, $this->overrideRecordLink)?>"><?=$this->string()->cleanEsc($result->getTitle())?> <?=$this->string()->cleanEsc($result->getTitleSection())?></a></td>
        <td><?=implode(', ',$result->getPublicationDates())?></td>
        <td><?=$result->getPrimaryAuthor()?></td>
    </tr>
    <? $count++ ?>  
    <? endforeach; ?>
    <? if ($count > 20): ?> 
        <tfoot>
            <tr><td>
                <a class="btn btn-info btn-xs showmore" id="showmore-<?=$rand?>"><?=$this->transEsc('Showmore')?></a>     
            </td></tr>
        </tfoot>
    <? endif; ?>
</table>
<? else: ?>
<p><?=$this->transEsc('nohit_heading')?></p>
<? endif; ?>