<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());
$rand = rand(0, 2000);

// Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();
?>
<table class="table table-striped">
  <?php $ppn = $this->driver->tryMethod('getPPN'); if (!empty($ppn)): ?>
  <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->abbrev('PPN')?>:</th>
      <td class="markjs">
        <?=$this->recordLink()->linkPPN($this->driver) ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php $zdb = $this->driver->tryMethod('getZdbId'); if (!empty($zdb)): ?>
  <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('ZDB-ID')?>:</th>
      <td class="markjs">
          <?php if (isset($zdb)): ?>
              <a id="clipboard-zdb-<?= $rand ?>" class="external"
                 href="https://zdb-katalog.de/list.xhtml?t=<?= $this->escapeHtml($zdb) ?>&key=zdb"><?= $this->escapeHtml($zdb) ?></a>
              <?= $this->clipboard('', 'clipboard-zdb-' . $rand) ?>
          <?php endif; ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php $note = $this->driver->tryMethod('getNote');
     if (!empty($note)):
     $contentDisplayed = true;
  ?>
    <tr>
        <th><?=$this->transEsc('Note')?></th>
        <td class="markjs"><?=$this->escapeHtml($note)?></td>
    </tr>
  <?php endif; ?>

  <?php $summ = $this->driver->getSummary(); if (!empty($summ)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Summary')?>: </th>
      <td class="markjs">
        <?php foreach ($summ as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php $ean = $this->driver->tryMethod('getGTIN');
     if (!empty($ean)):
         $contentDisplayed = true;
         ?>
         <tr>
             <th><?= $this->abbrev('GTIN') ?>:</th>
             <td class="markjs"><?= $this->clipboard($ean) ?></td>
         </tr>
     <?php endif; ?>

  <?php $dateSpan = $this->driver->getDateSpan(); if (!empty($dateSpan)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Published')?>: </th>
      <td class="markjs">
        <?php foreach ($dateSpan as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $notes = $this->driver->getGeneralNotes(); if (!empty($notes)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Item Description')?>: </th>
      <td class="markjs">
        <?php foreach ($notes as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>


  <?php $freq = $this->driver->getPublicationFrequency(); if (!empty($freq)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication Frequency')?>: </th>
      <td>
        <?php foreach ($freq as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $playTime = $this->driver->getPlayingTimes(); if (!empty($playTime)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Playing Time')?>: </th>
      <td>
        <?php foreach ($playTime as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $system = $this->driver->getSystemDetails(); if (!empty($system)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Format')?>: </th>
      <td>
        <?php foreach ($system as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $audience = $this->driver->getTargetAudienceNotes(); if (!empty($audience)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Audience')?>: </th>
      <td class="markjs">
        <?php foreach ($audience as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $awards = $this->driver->getAwards(); if (!empty($awards)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Awards')?>: </th>
      <td>
        <?php foreach ($awards as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Production Credits')?>: </th>
      <td>
        <?php foreach ($credits as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $bib = $this->driver->getBibliographyNotes(); if (!empty($bib)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Bibliography')?>: </th>
      <td class="markjs">
        <?php foreach ($bib as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->abbrev('ISBN', 'ISBN_long')?>: </th>
      <td class="markjs">
        <?php foreach ($isbns as $field): ?>
            <?= $this->clipboard($field) ?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->abbrev('ISSN', 'ISSN_long')?>: </th>
      <td class="markjs">
        <?php foreach ($issns as $field): ?>
            <?= $this->clipboard($field) ?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $doi = $this->driver->tryMethod('getCleanDOI'); if (!empty($doi)): ?>
      <?php $contentDisplayed = true; ?>
      <tr>
          <th><?= $this->transEsc('DOI') ?>:</th>
          <td><a id="clipboard-doi-<?= $rand ?>"
                 href="https://doi.org/<?= $this->escapeHtml($doi) ?>"
                 target="_blank">https://doi.org/<?= $this->escapeHtml($doi) ?></a>
              <?= $this->clipboard('', 'clipboard-doi-' . $rand) ?>
          </td>
      </tr>
  <?php endif; ?>

  <?php $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Related Items')?>: </th>
      <td>
        <?php foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Access')?>: </th>
      <td>
        <?php foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $findingAids = $this->driver->getFindingAids(); if (!empty($findingAids)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Finding Aid')?>: </th>
      <td>
        <?php foreach ($findingAids as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $publicationPlaces = $this->driver->getHierarchicalPlaceNames(); if (!empty($publicationPlaces)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication_Place')?>: </th>
      <td>
        <?php foreach ($publicationPlaces as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

    <?php $remarks = $this->driver->tryMethod('getRemarks'); if (!empty($remarks)): ?>
        <?php $contentDisplayed = true; ?>
        <tr>
            <th><?=$this->transEsc('remarks')?>: </th>
            <td class="markjs">
                <?php foreach ($remarks as $field): ?>
                    <?=$this->escapeHtml($field)?><br/>
                <?php endforeach; ?>
            </td>
        </tr>
    <?php endif; ?>

    <?php $bibliorelations = $this->driver->tryMethod('getBiblioRelations'); if (!empty($bibliorelations)): ?>
        <?php $contentDisplayed = true; ?>
        <?php $bibliorelationsids = $this->driver->tryMethod('getBiblioRelationsIds'); ?>
        <tr>
            <th><?=$this->transEsc('Bibliographic Relations')?>: </th>
            <td class="markjs">
                <?php foreach ($bibliorelations as $field): ?>
                    <?=$this->escapeHtml($field)?><br/>
                <?php endforeach; ?>
            </td>
        </tr>
    <?php endif; ?>

  <?php if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <?php endif; ?>
</table>

<script type="text/javascript">
    $(document).ready(function(){
        performMark('.tab-content .markjs');
    })
</script>
