<?
    // Set page title.
    $this->headTitle($this->translate('Libraries') . ': ' . $this->driver->getBreadcrumb());
    $content = $this->tab->getContent();        

?>

<? if(isset($content) && count($content) > 0): ?>
    
<table class="table table-striped table-condensed tablesorter">
    <thead>
        <tr>
            <th class="col-sm-1 col-xs-2"><?=$this->transEsc('ISIL')?></th>        
            <th><?=$this->transEsc('Library')?></th>        
            <th><?=$this->transEsc('Signatur')?></th>
            <? if ($this->driver->isJournal()): ?><th><?=$this->transEsc('Collection')?></th><? endif; ?>

        </tr>        
    </thead>
    <tbody>
        <? foreach ($content as $result): ?>

        <tr>
            <td><?=isset($result['b']) ? $this->escapeHtml($result['b']) : ''?></td>
            <td><?=isset($result['name']) ? $this->escapeHtml($result['name']) : ''?></td>
            <td><?=isset($result['g']) ? $this->escapeHtml($result['g']) : ''?></td>
            <? if ($this->driver->isJournal()): ?><td><?=isset($result['z']) ? $this->escapeHtml($result['z']) : ''?></td><? endif; ?>

        </tr>
        <? endforeach; ?>        
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
       $('.tablesorter').tablesorter({
           sortList : [[0,0]]
       }); 
    });
</script>
<? else: ?>
<p><?=$this->transEsc('nohit_heading')?></p>
<? endif; ?>
