<?
    // Set page title.
    $this->headTitle($this->translate('Libraries') . ': ' . $this->driver->getBreadcrumb());
    $content = $this->tab->getContent();
?>

<? if(isset($content) && count($content) > 0): ?>

<table class="table table-striped table-condensed tablesorter">
    <thead>
        <tr>
            <th class="col-sm-1 col-xs-1 hidden-xs"><?=$this->transEsc('Contact')?></th>
            <th><?=$this->transEsc('Library')?></th>
            <th><?=$this->transEsc('Call Number')?></th>
            <? if ( $this->client()->is('show_ill_column') ): ?>
                <th class="col-sm-2 col-xs-2 hidden-xs"><?=$this->transEsc('Interlibrary Loan')?></th>
            <? endif; ?>
            <? if ($this->driver->isJournal()): ?><th><?=$this->transEsc('Collection')?></th><? endif; ?>

        </tr>
    </thead>
    <tbody>
        <? foreach ($content as $result): ?>
        <tr>
            <td class="hidden-xs">
                <? if (isset($result['isil']) && trim($result['isil']) != ''): ?>
                    <? if ($result['isil'] !== 'LFER'): ?>
                        <span class="text-nowrap">
                            <? if (isset($result['homepage'])): ?>
                                <a data-toggle="tooltip" title="<?= $this->transEsc('ILL::library_homepage') ?>"
                                    href="<?= $result['homepage'] ?>"
                                    class="external hasicon"><i class="fa fa-globe"></i><?= $this->escapeHtml($result['b']) ?></a>
                            <? else: ?>
                                <?=$this->escapeHtml($result['isil'])?>
                            <? endif; ?>
                        </span>
                    <? else: ?>
                        <?=$this->abbrev($result['isil'], 'LFER_long')?>
                    <? endif; ?>
                <? else: ?>
                    <?= isset($result['isil']) ? $this->escapeHtml($result['isil']) : '' ?>
                <? endif; ?>
            </td>

            <td>
                <? if (isset($result['opacurl']) && isset($result['name']) && trim($result['opacurl']) != '' && $this->driver->getNetwork() !== 'ZDB'): ?>
                    <? $opac = preg_replace('/%PPN%/', $this->driver->getPPN(), $result['opacurl']) ?>
                    <a data-toggle="tooltip" title="<?= $this->transEsc('ILL::library_opac') ?>" href="<?= $opac ?>"
                       class="external hasicon">
                        <i class="fa fa-globe"></i><?= $this->escapeHtml($result['name']) ?>
                    </a>
                <? else: ?>
                    <?= isset($result['name']) ? $this->escapeHtml($result['name']) : '' ?>
                <? endif; ?>
            </td>

            <td>
                <? if ((isset($result['call_number']) && (isset($result['call_number']) !== true))): ?>
                    <?=$this->escapeHtml($result['call_number'])?>
                <? elseif(isset($result['url']) && isset($result['call_number'])): ?>
                    <a href="<?=$result['url']?>" target="_blank" data-toggle="tooltip" title="<?=$this->transEsc('Fulltext')?>"><i class="fa fa-globe"></i><?=$this->escapeHtml($result['call_number'])?></a>
                <? elseif(isset($result['url'])): ?>
                    <a href="<?=$result['url']?>" target="_blank" data-toggle="tooltip" title="<?=$this->transEsc('Fulltext')?>"><i class="fa fa-globe"></i><?=$this->transEsc('E-Book')?></a>
                <? else: ?>
                    <?= $this->transEsc('NoCallnumber') ?>
                <? endif; ?>
            </td>

            <? if ( $this->client()->is('show_ill_column') ): ?>
                <td>
                    <? if (isset($result['ill_indicator'])): ?><i class="fa <?= $this->record($this->driver)->indicator2icon($result['ill_indicator'])?>"></i> <? endif; ?><span
                        class="text hidden-xs"><?= isst($result['ill_indicator']) ? $this->transEsc($this->record($this->driver)->indicator2status($result['ill_indicator'])) : '-' ?></span>
                </td>
            <? endif; ?>

            <? if ($this->driver->isJournal()): ?>
                <td><?= isset($result['issue']) ? $this->escapeHtml($result['issue']) : '' ?></td>
            <? endif; ?>
        </tr>
        <? endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
       $('.tablesorter').tablesorter({
           sortList : [[0,0]]
       });
    });
</script>
<? else: ?>
<p><?=$this->transEsc('nohit_heading')?></p>
<? endif; ?>
