<?
/**
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

// Set page title.
$this->headTitle($this->translate('ContainedNotes') . ': ' . $this->driver->getBreadcrumb());

?>
    <? $notes = $this->driver->getNotes(); if (!empty($notes)): ?>
        <? $contentDisplayed = true; ?>
        <ul>
            <? foreach ($notes as $field): ?>
                <li>
                    <?=$this->escapeHtml($field)?>
                </li>
            <? endforeach; ?>
        </ul>
    <? endif; ?>

    <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
        <tr><td><?=$this->transEsc('NoContainedNotes')?></td></tr>
    <? endif; ?>

