<?php
    //Set page title.
use Bsz\Debug;
use VuFind\XSLT\Processor;

$this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
?>
<?php if (Debug::isInternal() && $this->driver->tryMethod('getGroupField') !== ''): ?>
    <table class="table citation table-striped">
        <tr>
            <th width="15%">Dedup-Key</th>
            <td><?=$this->escapeHtmlAttr($this->driver->tryMethod('getGroupField'))?></td>
        </tr>
    </table>
<?php endif; ?>
<?= Processor::process('record-marc.xsl', $this->driver->getXML('marc21'))?>
