<!-- recordDriver - solrLido - CORE.phtml -->
<?
if($loggedin = $this->auth()->isLoggedIn()) {
  $user_id = $loggedin->id;
  $loggedin = true;
} else {
  $user_id = false;
}
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="medium-3 columns">
    <div class="text-center">
        <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? /* BOF - finc-specific StyleBasedIcons */ ?>
      <? elseif ($this->record($this->driver)->showStyleBasedIcons()): ?>
        <?=$this->record($this->driver)->getFormatIcon()?>
      <? /* EOF - finc-specific StyleBasedIcons */ ?>
      <? endif; ?>

        <? /* Display qrcode if appropriate: */ ?>
        <? if($QRCode): ?>
        <span class="hide-for-small">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
        <? endif; ?>
        <? /* Image rights: */ ?>
        <? $rights = $this->driver->getImageRights($this->layout()->userLang); ?>
        <div class="access-rights">
          <div class="image-rights">
                <? $hasLink = isset($rights['link']); ?>
                <strong><?= $this->translate("Image Rights") ?>
                    :</strong> <? if (isset($rights['copyright'])) : ?><? if ($hasLink): ?><a target="_blank" href="<?= $rights['link'] ?>"><? endif; ?><?= $this->transEsc($rights['copyright']) ?><? if ($hasLink): ?></a><? endif ?><? endif ?>
          </div>
          <div class="copyright truncate-field">
                <? if (isset($rights['description'])): ?>
                    <? foreach ($rights['description'] as $item): ?>
                        <p><?= $this->transEsc($item) ?></p>
                    <? endforeach ?>
                <? endif ?>
                <? if (!isset($rights['copyright']) && !isset($rights['description'])): ?>
                    <?= $this->translate('Image Rights Default') ?>
                    <!--<p><a href="< ?= $this->url('content-page', array('page' => 'terms_conditions')) . '#image_rights' ?>"><i class="fa fa-arrow-right"></i>< ?= $this->translate('See also terms and conditions') ?></a>-->
                <? endif; ?>
          </div>
        </div>
      </div>

    <? // if you have a preview tab but want to move or remove the preview link
    // from this area of the record view, this can be split into
    // getPreviewData() (should stay here) and
    // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="medium-9 columns">
  <? else: ?>
  <div class="medium-12 columns">
  <? endif; ?>
    <? /* This following line is a finc-specific change */ ?>
    <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hide alert-box info" data-alert tabindex="0" aria-live="assertive" role="alertdialog">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table">
      <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <?
          $containerSource = $this->driver->getSourceIdentifier();
          $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>


      <!-- Creator / Originator -->
      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <tr>
          <th><?= $this->transEsc(count($authors['main']) > 1 ? 'Originators' : 'Originator') ?>: </th>
          <td>
            <? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?= ($i++ == 0) ? '' : ', ' ?><span property="author"><a href="<?= $this->record($this->driver)->getLink('author', $author) ?>"><?= $this->escapeHtml($author) ?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?= ($j++ == 0) ? '' : ', ' ?><?= $this->transEsc("CreatorRoles::" . $role) ?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
        <tr>
          <th><?= $this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Originator' : 'Corporate Originators') ?>:</th>
          <td>
            <? $i = 0; foreach ($authors['corporate'] as $corporate => $roles): ?><?= ($i++ == 0) ? '' : ', ' ?><span property="creator"><a href="<?= $this->record($this->driver)->getLink('author', $corporate) ?>"><?= $this->escapeHtml($corporate) ?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?= ($j++ == 0) ? '' : ', ' ?><?= $this->transEsc("CreatorRoles::" . $role) ?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
        <tr>
          <th><?= $this->transEsc('Other Originators') ?>:</th>
          <td>
            <? $i = 0; foreach ($authors['secondary'] as $author => $roles): ?><?= ($i++ == 0) ? '' : ', ' ?><span property="contributor"><a href="<?= $this->record($this->driver)->getLink('author', $author) ?>"><?= $this->escapeHtml($author) ?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?= ($j++ == 0) ? '' : ', ' ?><?= $this->transEsc("CreatorRoles::" . $role) ?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectDetails()): ?>
        <tr class="recordSubjects">
          <th><?= $this->transEsc('Subject Detail') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectPlaces()): ?>
        <tr class="recordSubjects">
          <th><?= $this->transEsc('Subject Place') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectDates()): ?>
        <tr class="recordSubjects">
          <th><?= $this->transEsc('Subject Date') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectActors()): ?>
        <tr class="recordSubjects">
          <th><?= $this->transEsc('Subject Actor') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getInstitutions()): ?>
        <tr class="recordInstitution">
          <th><?= $this->transEsc('Institution') ?>:</th>
          <td>
            <? foreach ($results as $index => $institution): ?>
              <?= ($index > 0 ? '<br/>' : '') ?><?= $this->transEsc("source_$institution", array(), $this->translate($institution)) ?>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getIdentifier()): ?>
        <tr class="recordIdentifier">
          <th><?= $this->transEsc('Inventory ID') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getMeasurements()): ?>
        <tr class="recordMeasurements">
          <th><?= $this->transEsc('Measurements') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getMeasurementsDescription()): ?>
        <tr class="recordMeasurementsDescription">
          <th><?= $this->transEsc('Measurements') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getCollections()): ?>
        <tr class="recordCollection">
          <th><?= $this->transEsc('Collection') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <!---Format Finc --->
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?= $this->transEsc('Object type') ?>:</th>
          <td><?= $this->record($this->driver)->getFormatList() ?></td>
        </tr>
      <? endif; ?>

      <!-- Format Lido -->
      <? if ($results = $this->driver->getFormatClassifications()): ?>
        <tr class="recordClassifications">
          <th><?= $this->transEsc('Other Classification') ?>:</th>
          <td>
            <div class="truncate-field"><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></div>
          </td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getLocalIdentifiers()): ?>
        <tr class="recordIdentifiers">
          <th><?= $this->transEsc('Other ID') ?>:</th>
          <td><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $results)) ?></td>
        </tr>
      <? endif; ?>

      <? $mainFormat = $this->driver->getMainFormat(); ?> <? foreach ($this->driver->getEvents() as $eventType => $events): ?>
        <tr class="recordEvents">
          <!--<th>< ?=$this->transEsc("lido_event_type_{$mainFormat}_$eventType")?>:</th>-->
          <th>
            <? if ($eventType == 'production'): ?>
              <?= $this->transEsc('expression creation') ?>
            <? elseif ($eventType == 'publication'): ?>
              <?= $this->transEsc('Time of origin') ?>
              <? $publicationIsSet = true; ?>
            <? else: ?>
              <?= $this->transEsc($eventType) ?>
            <? endif; ?>
          </th>
          <td>
            <div class="truncate-field">
              <? foreach ($events as $event): ?>
                <? if ($event != $events[0]): ?><br/><? endif; ?>
                <? if (!empty($event['name'])): ?><?= $this->escapeHtml($event['name']) ?><br/><? endif; ?>
                <? if (!empty($event['date'])): ?><?= $this->escapeHtml($event['date']) ?><br/><? elseif ($event['type'] != 'käyttö' && $event['type'] != 'näyttely'): ?> <?= $this->transEsc('undated') ?><? endif; ?>
                <? if (!empty($event['method'])): ?><?= $this->escapeHtml($event['method']) ?><br/><? endif; ?>
                <? if (!empty($event['materials'])): ?><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $event['materials'])) ?><br/><? endif; ?>
                <? if (!empty($event['places'])): ?><?= implode('<br/>', array_map(array($this, 'escapeHtml'), $event['places'])) ?><br/><? endif; ?>
                <? if (!empty($event['culture'])): ?><?= $this->escapeHtml($event['culture']) ?><br/><? endif; ?>
                <? if (!empty($event['actors'])): ?>
                  <? foreach ($event['actors'] as $actor): ?>
                    <?= $this->escapeHtml($actor['name']) ?><? if (!empty($actor['role'])): ?>, <?= $this->escapeHtml($actor['role']) ?><? endif; ?>
                  <? endforeach; ?>
                  <br/>
                <? endif; ?>
                <? if (!empty($event['description'])): ?><?= $this->escapeHtml($event['description']) ?><br/><? endif; ?>
              <? endforeach; ?>
            </div>
          </td>
        </tr>
      <? endforeach; ?>
      <!-- End -->

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?= $this->transEsc('Language') ?>:</th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang) ?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $dateSpan = $this->driver->getDateSpan(); if (!empty($dateSpan) && !$publicationIsSet): ?>
        <? $contentDisplayed = true; ?>
        <tr>
          <th><?= $this->transEsc('Time of origin') ?>:</th>
          <td>
            <?= $this->record($this->driver)->mapDateListToRangeView($dateSpan); ?>
          </td>
        </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subject-line" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="right hide-for-print">
              <a class="tagRecord right" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" data-lightbox><i class="fa fa-plus"></i><?=$this->transEsc('Add Tag')?></a>
            </span>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
<!-- recordDriver - solrLido - CORE.phtml end -->