<!-- finc: RecordDriver - solrLido - core -->
<? /* keep schema tagging here in finc - CK, #13861 */ ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?
    if ($loggedin = $this->auth()->isLoggedIn()) {
        $user_id = $loggedin->id;
        $loggedin = true;
    } else {
        $user_id = false;
    }
  $formatRoles = function ($roles) {
    if (count($roles) == 0) {
      return '';
    }
    $that = $this;
    $translate = function ($str) use ($that) {
      return $that->transEsc('CreatorRoles::' . $str);
    };
    return ' (' . implode(', ', array_unique(array_map($translate, $roles))) . ')';
  };
  ?>
  <?
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
        <? /* Display thumbnail if appropriate: */ ?>
        <? if($cover): ?>
          <?=$cover?>
        <? /* BOF - finc-specific StyleBasedIcons */ ?>
      <? elseif ($this->record($this->driver)->showStyleBasedIcons()): ?>
        <?=$this->record($this->driver)->getFormatIcon()?>
        <? /* EOF - finc-specific StyleBasedIcons */ ?>
        <? endif; ?>

        <? /* Display qrcode if appropriate: */ ?>
        <? if($QRCode): ?>
          <span class="hidden-xs">
            <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
          </span>
        <? endif; ?>

      <? // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <? if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <? endif; ?>
    </div>
  <? endif; ?>
  <div class="media-body">

    <? /* finc: We want to get rid of trailing special chars in the title and limit its length to 100 chars
      in finc: keep schema name tag here!! #13861 CK
       */
    ?>
    <h3 property="name"><?=$this->escapeHtml(preg_replace('/(\s[\/\.:]\s*)*$/', '', $this->truncate($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection(), 100)))?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p class="hidden-print"><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <?
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core-lido'));
    ?>
    <? if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <? /* Table summary not supported in html 5, finc-specific solution, CK */ ?>
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <? foreach ($coreFields as $key => $current): ?>
            <? if ($key == null): ?>
              <?=$current['value']?>
            <? else: ?>
            <tr><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
            <? endif; ?>
          <? endforeach; ?>
      </table>
    <? endif; ?>
    <?/* End Main Details */?>
  </div>
</div>
<!-- finc: RecordDriver - solrLido - core - END -->