<? if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>
<? if (!empty($this->year)): ?><? if (!empty($this->authors)): ?> <? endif; ?>(<?=$this->escapeHtml($this->year)?>). <? endif; ?>
<? endif; ?>
<i><?=$this->escapeHtml($this->title)?></i><? if ($this->periodAfterTitle): ?>. <? endif ?>
<? if (empty($this->authors)): ?>
<? if (!empty($this->year)): ?> (<?=$this->escapeHtml($this->year)?>). <? endif; ?>
<? endif; ?>
<? if (!empty($this->edition)): ?>(<?=$this->escapeHtml($this->edition)?>). <? endif; ?>
<? if (!empty($this->publisher)): ?><?=$this->escapeHtml($this->publisher)?>.<? endif; ?>
