<? if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>:<br /><? endif; ?>
<span><i><?=$this->escapeHtml($this->title)?></i></span>
<? if (!empty($this->edition)):   ?>. &mdash; <?=$this->escapeHtml($this->edition)?> <? endif; ?>
<? if (!empty($this->publisher)): ?>. &mdash; <?=$this->escapeHtml($this->publisher)?><? endif; ?>
<? if (!empty($this->physical)):  ?>. &mdash; <?=$this->escapeHtml($this->physical)?><? endif; ?>
<? if (!empty($this->series)):    ?>. &mdash; <?=$this->escapeHtml($this->series)?><? endif; ?>
<? if (!empty($this->isbn)): ?>. &mdash; ISBN <?=$this->escapeHtml($this->isbn)?><? endif; ?>
