<div>
<? $containerId = $this->driver->getContainerId();  
   $summDate = $this->driver->getPublicationDates();   
   $summAuthors = $this->driver->getDeduplicatedAuthors(['role', 'gnd', 'live']); 
   $summDate = $this->driver->getPublicationDates();
   $summInCollection = $this->driver->getContainingCollections(); 
   $journalTitle = $this->driver->getContainerTitle();    
   $link = isset($containerId) ? $this->recordLink()->getUrl($containerId) : $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle));
?>  

<? if($this->driver->isCollection()): ?>
    <? if (!empty($summDate) && isset($summDate[0])): ?>
        <strong><?=$this->transEsc('Published in') . '</strong> <a href="' . $link . '">' . $this->highlight($journalTitle) . '</a>';?>
        <? $summAuthors = $this->driver->getDeduplicatedAuthors()?> 
        <?=count($summDate) > 0? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>               
    <? endif; ?>
<? endif; ?> 
    
<? if (!empty($summAuthors)) ?>
    <? if (!empty($summAuthors['primary'])): ?>
        <strong><?=$this->transEsc('by')?></strong>
        <? foreach ($summAuthors['primary'] as $name => $info): ?>
            <?=$this->context($this)->renderInContext('RecordDriver/SolrDefault/parts/singleauthor.phtml', ['name' => $name, 'info' => $info, 'hiddenFilterString' => $hiddenFilterString])?>
        <? endforeach; ?>
        <br/>
    <? endif; ?>
    <? if (!empty($summAuthors['secondary'])): ?>
        <? if (!empty($summAuthors['primary'])):?>
            <strong><?=$this->transEsc('and')?></strong>
        <? else: ?> 
            <strong><?=$this->transEsc('by')?></strong>
        <?endif?>
        <? $count = 0?>
        <? foreach ($summAuthors['secondary'] as $name => $info): ?>
            <? if ($count < 3): ?>
            <?=$this->context($this)->renderInContext('RecordDriver/SolrDefault/parts/singleauthor.phtml', ['name' => $name, 'info' => $info, 'hiddenFilterString' => $hiddenFilterString])?>
            <? endif; ?>
            <? $count++ ?>
        <? endforeach; ?>
        <? if (count($summAuthors['secondary']) >= 3): ?>
            <?=$this->transEsc('et al.')?>
        <? endif; ?>
        <br/>
<? endif; ?>
    


<?=!empty($summAuthor) ? '<br />' : ''?>
<? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
<? $count = 0 ?>
<strong><?=$this->transEsc('Published')?>: </strong> 
<? if (!empty($publications[0])): ?>
    <? foreach ($publications as $field): ?>                        
        <? if($count > 0):?>; <?endif;?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
            <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
        <? endif; ?>
        <? $pubName = $field->getName(); if (!empty($pubName)): ?>
            <span property="name"><?=$this->escapeHtml($pubName)?></span>
        <? endif; ?>
        </span>
        <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
            <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
        <? endif; ?>
        <? $count++ ?>
    <? endforeach; ?>
<? else: ?>
    <? if (!empty($summDate) && isset($summDate[0])): ?>
        <?= $this->escapeHtml($summDate[0])?>
    <? endif; ?>
<? endif; ?>
<? endif; ?>
<? if (!empty($summInCollection)): ?>
    <? foreach ($summInCollection as $collId => $collText): ?>
        <div>
            <b><?=$this->transEsc("in_collection_label")?></b>
            <a class="ckText" href="<?=$this->url('collection', ['id' => $collId])?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
            <?=$this->escapeHtml($collText)?>
            </a>
        </div>
    <? endforeach; ?>
<? endif; ?>
</div>   
