<?php
$network = $this->driver->getNetwork(); 
$class = '';

$url = $this->recordLink()->getUrl($this->driver).'/ILLForm';
if ($this->customUrl) {
    $url = $this->openUrl($this->driver, 'illform')->getUrl();
}
?>
<?php if ($status): ?>
    <div class="col-sm-12" style="padding-left: 0;">    
                <?php if (isset($messages) && count($messages) > 0): ?>       
        <strong><?=$this->transEsc('ILL::cond_heading')?></strong>
        <ul class="help-text">
            <?php foreach ($messages as $message): ?>
            <li><?= $this->transEsc($message)?></li>
            <?php endforeach; ?>            
            <li><?= $this->recordLink()->linkPPN($this->driver) ?></li>
        </ul>              
        <?php endif; ?>
        <?php // TODO Permissions.ini to check login ?>
        <span <?php if (false): ?>             
            data-toggle="popover"
            data-trigger="focus"
            role="button"
            tabindex
            data-content="<?=$this->transEsc('shib_login_required')?>"
            data-title="<?=$this->transEsc('shib_login_required_title')?>"            
             <?php endif; ?>>
             <a title="<?= $this->transEsc('Interlibrary Loan') ?>" 
                accesskey="" href="<?= $url ?>" 
                id="illform" class="<?=$this->escapeHtmlAttr($class)?> btn btn-success btn-sm <? if($this->customUrl):?>external hasicon<? endif; ?>"><?= $this->transEsc('Recall as Interlibrary Loan') ?></a>
         </span>
    </div>

<?php endif; ?>
