<?php  /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
    but even if we don't plan to display the link, we still want to get the $openUrl
    value for use in generating a COinS (Z3988) tag -- see bottom of file.
*/

// Account for replace_other_urls setting
$openUrl = $this->openUrl($this->driver, 'results');
$openUrlActive = $openUrl->isActive();
$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
if (!is_array($urls)):
    $urls = [];
endif;

$localUrls = $this->driver->tryMethod('getLocalUrls'); ?>
<?php // Show local Urls?>
<?php if (!empty($localUrls[0]['url'])): ?>
    <div>
        <?php foreach ($localUrls as $current): ?>
            <?php if (is_array($current['label'])):?>
                <a class="external <?php if ($this->area == 'record'):?>localUrls<?php endif ?>" href="<?=$current['url']?>"><?=$this->transEsc($current['label'][0])?></a>
                <?php if ($this->client()->is('local_url_help_regex') && isset($current['label'][1])): ?>
                    <?php $htmllink =  preg_replace(
    $this->client()->getHelpRegEx(),
    "<a class='external' href='" . $this->client()->getHelpUrl() . "'>" . $this->client()->getHelpGroups() . "</a>",
    $this->transEsc($current['label'][1])
                    )?>
                    <?=$htmllink?>
                <?php elseif (isset($current['label'][1])): ?>
                    <?=$this->transEsc($current['label'][1])?>
                    <br/>
                <?php endif; ?>
            <?php else: ?>
                <a class="external" href="<?=$current['url']?>"><?=$this->transEsc($current['label'])?></a>
            <?php endif ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <?php // Show SWB-links?>
    <?php if (!$this->driver->isCollection()): ?>
        <?php if (count($urls) > 2): ?>
            <?php $urls = array_slice($urls, 0, 3) ?>
        <?php endif; ?>
        <?php foreach ($urls as $current): ?>
            <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($current['url'])) ?>"
               class="fulltext external"><?= ($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->transEsc($current['desc']) ?></a>
            <br/>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

<?php // JOP resp. Redi Linkresolver
// see VuFind/View/Helper/Bodensee/OpenUrl.php
//     themes/bodensee/Helpers/openurl.phtml
//     openurl.js
?>
<?php if ($openUrlActive): ?>
    <?= $openUrl->renderTemplate() ?>
<?php endif; ?>
<?= $this->driver->supportsCoinsOpenUrl() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>' : '' ?>
