<?php /*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */ /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
    but even if we don't plan to display the link, we still want to get the $openUrl
    value for use in generating a COinS (Z3988) tag -- see bottom of file.
*/

// Account for replace_other_urls setting
$openUrl = $this->openUrl($this->driver, 'results');
$openUrlActive = $openUrl->isActive();
$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
if (!is_array($urls)):
    $urls = [];
endif;

$localUrls = $this->driver->tryMethod('getLocalUrls'); ?>
<?php // Show local Urls ?>
<?php if (!empty($localUrls[0]['url'])): ?>
    <div>
        <?php foreach ($localUrls as $current): ?>
            <?php $pos = strpos($current['label'], ' | '); ?>
            <?php $len = strlen($current['label']); ?>
            <?php if ($this->client()->is('local_url_help_regex')): ?>
                <a class="external"
                   href="<?= str_replace('http://dx.doi.org', 'https://doi.org', $current['url']) ?>"><?= $pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label']) ?></a>  <?= $pos ? preg_replace($this->client()->getHelpRegEx(), "<a class='external' href='" . $this->client()->getHelpUrl() . "'>" . $this->client()->getHelpGroups() . "</a>", $this->transEsc(substr($current['label'], $pos + 3, $len))) : '' ?>
                <br/>
            <?php else: ?>
                <a class="external"
                   href="<?= str_replace('http://dx.doi.org', 'https://doi.org', $current['url']) ?>"><?= $pos ? $this->transEsc(substr($current['label'], 0, $pos)) : $this->transEsc($current['label']) ?></a> <?= $pos ? $this->transEsc(substr($current['label'], $pos + 3, $len)) : '' ?>
                <br/>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <?php // Show SWB-links ?>
    <?php if (!$this->driver->isCollection()): ?>
        <?php if (count($urls) > 2): ?>
            <?php $urls = array_slice($urls, 0, 3) ?>
        <?php endif; ?>
        <?php foreach ($urls as $current): ?>
            <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($current['url'])) ?>"
               class="fulltext external"><?= ($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->transEsc($current['desc']) ?></a>
            <br/>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

<?php // JOP resp. Redi Linkresolver
// see VuFind/View/Helper/Bodensee/OpenUrl.php
//     themes/bodensee/Helpers/openurl.phtml
//     openurl.js
?>
<?php if ($openUrlActive): ?>
    <?= $openUrl->renderTemplate() ?>
<?php endif; ?>
<?= $this->driver->supportsCoinsOpenUrl() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>' : '' ?>
