<?php
    $count = 0;
    $rand = rand(0, 9999);
    $max = 5;
?>
<?php foreach ($this->subjects as $field): ?>
    <span class="subjectLine" property="keywords">
         <?php $subject = ''; ?>
        <?php // case 1 : subjects in one field separated by --?>
        <?php if( is_array($field) && count($field) == 1): $field = explode('--', $field[0]); ?>
            <?php $i = 0; foreach ($field as $subfield): ?>
                <?=($i++ == 0) ? '' : ' &gt; '?>
                <?php $subject = trim($subject . ' ' . $subfield); ?>
                <a class="markjs searchicon <?php if($count >= $max): ?><?=$this->type?>subjects-<?=$rand?>collapse-inline collapse multi-collapse<?php endif; ?>" title="<?=$this->escapeHtmlAttr($subject)?>"
                   href="<?=$this->record($this->driver)->getLink('subject', $subject, $this->searchClassId)?>"><?=trim($this->escapeHtml($subfield))?></a>
                <?php $count++ ?>
            <?php endforeach; ?>
        <?php // case 2: subjects in array ?>
        <?php elseif (is_array($field) && count($field) > 1): ?>
            <?php foreach ($field as $subfield): ?>
                <a class="markjs searchicon <?php if($count >= $max): ?><?=$this->type?>subjects-<?=$rand?>collapse-inline  collapse multi-collapse<?php endif; ?>" title="<?=$this->escapeHtmlAttr($subfield)?>" href="<?=$this->record($this->driver)->getLink('subject', $subfield, $this->searchClassId)?>"><?=trim($this->escapeHtml($subfield))?></a>
                <?php $count++ ?>
            <?php endforeach; ?>
        <?php // case 3: subjects in string ?>
        <?php else: ?>
            <a class="markjs searchicon <?php if ($count >= $max): ?><?=$this->type?>subjects-<?=$rand?> collapse-inline collapse multi-collapse<?php endif; ?>"
               title="<?= $this->escapeHtmlAttr($field) ?>"
               href="<?= $this->record($this->driver)->getLink('subject', $field, $this->searchClassId) ?>"><?= trim($this->escapeHtml($field)) ?></a>
            <?php $count++ ?>
        <? endif; ?>
      </span>
<?php endforeach; ?>

<?php if($count >= $max): ?>
    <?=$this->showmore('.'.$this->type.'subjects-'.$rand, false)?>
<?endif; ?>