<?php $subjects = $this->driver->getAllSubjectHeadings();?>
<?php if (!empty($subjects)): ?>

<?php $rand = rand(0, 9999)?>
  <tr>
    <th><?=$this->transEsc('Subjects')?>:</th>
    <td id="showmore-items-<?=$rand?>">
      <?php $count = 0 ?>
      <?php foreach ($subjects as $field): ?>
        <span class="subjectLine" property="keywords">
         <?php $subject = ''; ?>
         <?php if( is_array($field) && count($field) == 1): $field = explode('--', $field[0]); ?>
            <?php $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <?php $subject = trim($subject . ' ' . $subfield); ?>
              <a class="markjs showmore-item searchicon <?php if($count > 5): ?>hidden <?php endif; ?>" title="<?=$this->escapeHtmlAttr($subject)?>"
                 href="<?=$this->record($this->driver)->getLink('subject', $subject, $this->searchClassId)?>"><?=trim($this->escapeHtml($subfield))?></a>
              <?php $count++ ?>
            <?php endforeach; ?>
          <?php elseif (is_array($field) && count($field) > 1): ?>
                <?php foreach ($field as $subfield): ?>
                    <a class="markjssearchicon showmore-item <?php if($count > 5): ?>hidden <?php endif; ?>" title="<?=$this->escapeHtmlAttr($subfield)?>" href="<?=$this->record($this->driver)->getLink('subject', $subfield, $this->searchClassId)?>"><?=trim($this->escapeHtml($subfield))?></a>
                    <?php $count++ ?>
                <?php endforeach; ?>
          <?php else: ?>
             <a class="markjs searchicon showmore-item <?php if ($count >= 5): ?>hidden <?php endif; ?>"
                title="<?= $this->escapeHtmlAttr($field) ?>"
                href="<?= $this->record($this->driver)->getLink('subject', $field, $this->searchClassId) ?>"><?= trim($this->escapeHtml($field)) ?></a>
             <?php $count++ ?>
         <?php endif; ?>
      </span>
      <?php endforeach; ?>
      <?php if($count > 5): ?>
      <a href="#" class="showmore" id="showmore-<?=$rand?>">[<?=$this->transEsc('Showmore')?>...]</a>
      <?endif; ?>
    </td>
  </tr>
  <?php unset($subjects)?>
  <?php endif; ?>


  <?php $notations = $this->driver->tryMethod('getRVKNotations');
  if(!empty($notations) && $this->client()->is('show_rvk')): ?>
  <?php $contentDisplayed = true; ?>
  <tr>
      <th><span class="text-nowrap"><?=$this->abbrev('RVK')?>-<?=$this->transEsc('Notation')?>:</span></th>
      <?php if(is_array($notations)): ?>
      <td>
          <?php foreach ($notations as $shortcut => $description): ?>
          <?php           $descriptionHtml = '<ol>';
          foreach($description as $item) {
            $descriptionHtml .= '<li>'.$item.'</li>';
          }
          $descriptionHtml .= '</ol>';
          if ($descriptionHtml == '<ol></ol>') {$descriptionHtml = '';}

          ?>
          <span class="notationLine markjs">
                <a data-toggle="tooltip" data-placement="right" data-html="true" href="<?=$this->record($this->driver)->getLink('rvknotation', $shortcut, $this->searchClassId)?>" class="searchicon" title="<?=$descriptionHtml?>" ><?=$this->transEsc($shortcut)?></a>
          </span>
          <?php endforeach; ?>
      </td>
  <?php endif; ?>
  </tr>
  <?php endif; ?>

  <?php $fivclassification = $this->driver->tryMethod('getFIVClassification');
  if(!empty($fivclassification) && $this->client()->is('show_fiv')): ?>
  <?php $contentDisplayed = true; ?>
  <tr>
      <th><span class="text-nowrap"><?=$this->abbrev('FIV')?>-<?=$this->transEsc('Classification')?>:</span></th>
      <?php if(is_array($fivclassification)): ?>
      <td>
          <?php foreach ($fivclassification as $notation): ?>
            <?php $trans = 'FIV::'.preg_replace('/\.|\s.*/', '', strtolower($notation))?>
                <span class="notationLine markjs">
                    <a href="<?=$this->record($this->driver)->getLink('fivclassification', $notation, $this->searchClassId)?>" class="searchicon"><?=$this->transEsc($trans)?></a>
                </span>
          <?php endforeach; ?>
      </td>
  <?php endif; ?>
  </tr>
  <?php endif; ?>

  <?php $fivsubjects = $this->driver->tryMethod('getFIVSubjects');
  if(!empty($fivsubjects) && $this->client()->is('show_fiv')): ?>
  <?php $contentDisplayed = true; ?>
  <tr>
      <th><span class="text-nowrap"><?=$this->abbrev('FIV')?>-<?=$this->transEsc('Subjects')?>:</span></th>
      <?php if(is_array($fivsubjects)): ?>
      <td>
          <?php foreach ($fivsubjects as $notation): ?>
              <span class="notationLine markjs"><a href="#" class="searchicon"><?=$this->escapeHtml($notation)?></a></span>
          <?php endforeach; ?>
      </td>
  <?php endif; ?>
  </tr>
  <?php endif; ?>

  <?php $dficlassification = $this->driver->tryMethod('getDFIClassification');
  if(!empty($dficlassification) && $this->client()->is('show_dfi')): ?>
  <?php $contentDisplayed = true; ?>
  <tr>
      <th><span class="text-nowrap"><?=$this->abbrev('DFI')?>-<?=$this->transEsc('Classification')?>:</span></th>
      <?php if(is_array($dficlassification)): ?>
      <td>
          <?php foreach ($dficlassification as $notation): ?>
            <span class="notationLine markjs">
                <a data-toggle="tooltip" data-placement="right" data-html="true" href="<?=$this->record($this->driver)->getLink('dficlassification', $notation, $this->searchClassId)?>" class="searchicon" title="<?=$this->transEsc($notation)?>" ><?=$notation?></a>
            </span>
          <?php endforeach; ?>
      </td>
  <?php endif; ?>
  </tr>
  <?php endif; ?>


<?php $subjects = $this->driver->tryMethod('getAllRVKSubjectHeadings');
if (!empty($subjects) && $this->client()->is('show_rvk')): ?>
  <tr>
    <th><span class="text-nowrap"><?=$this->abbrev('RVK')?>-<?=$this->transEsc('Subjects')?>:</span></th>
    <td>
      <div class="subjectLine" property="keywords">
      <?php $count = 0; ?>
      <?php foreach ($subjects as $field): ?>
        <?php $subject = ''; ?>
        <?php if( is_array($field) && count($field) == 1): $field = explode('--', $field[0]); ?>
            <?php $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <?php $subject = trim($subject . ' ' . $subfield); ?>
              <?php //Die Links hatten eine Klasse backlink. Diese führt mit einer
              // bestimmten Browsererweiterung (uBlock / AdBlock?) zu komischer
              // Darstellung beim Hovern
              ?>
              <a class="markjs searchicon" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject, $this->searchClassId)?>"><?=trim($this->escapeHtml($subfield))?></a>
            <?php endforeach; ?>
        <?php else: ?>
            <a class="markjs searchicon <?php if($count >= 5): ?>hidden <?php endif; ?>" title="<?=$this->escapeHtmlAttr($field)?>"
               href="<?=$this->record($this->driver)->getLink('rvkheading', $field, $this->searchClassId)?>">
                <?=trim($this->escapeHtml($field))?></a>
        <?php endif; ?>
        <?php $count++ ?>
      <?php endforeach; ?>
      <?php if($count > 5):?>
      <a href="#" class="showmore"><?=$this->transEsc('Showmore')?></a>
      <?php endif; ?>
      </div>
    </td>
  </tr>
  <?php endif; ?>


