<!-- recordtab - additional.phtml -->
<?
// Set page title.
$this->headTitle($this->translate('Additionals') . ': ' . $this->driver->getBreadcrumb());

// Grab clean ISBN for convenience:
?>
<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">
	<? $additionals = $this->driver->getAdditionals(); if (!empty($additionals) && is_array($additionals)): ?>
		<? $contentDisplayed = true; ?>
		<? foreach($additionals as $additional) :?>
			<tr>
				<th><?=$this->escapeHtml($additional['identifier'])?>: </th>
				<td>
					<? if(isset($additional['id'])): ?>
					<a href="<?=$this->url('record')?><?=$this->escapeHtml($additional['id'])?>">
						<? endif; ?>
						<?=$this->escapeHtml($additional['text'])?>
						<? if(isset($additional['id'])): ?>
					</a>
				<? endif; ?>
				</td>
			</tr>
		<? endforeach; ?>
	<? else: ?>
		<tr><td><?=$this->transEsc('Additional Items unavailable')?></td></tr>
	<? endif; ?>

	<? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
		<tr><td><?=$this->transEsc('Additional Items unavailable')?></td></tr>
	<? endif; ?>
</table>
<!-- recordtab - additional.phtml - END -->