<!-- finc: recordtab - description -->
<?
// Set page title.
$this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

$formatter = $this->recordDataFormatter();
$mainFields = $formatter->getData($driver, $formatter->getDefaults('description'));
?>
<? /* finc: remove schema tag here but keep in core,*/ ?>
<table class="table table-striped">
  <? /* finc: table summary not supported in html 5, finc-specific solution, CK */
  /* Table gets filled via recordDriver/.../data-... templates as referenced in RecordDataFormatterFactory */ ?>
  <caption class="sr-only"><?=$this->transEsc('Description')?></caption>
  <? if (!empty($mainFields)): ?>
    <? foreach ($mainFields as $key => $current): ?>
      <? if ($key == null): ?>
        <?=$current['value']?>
      <? else: ?>
        <tr>
          <th><?=$this->transEsc($key)?>:</th>
          <td><?=$current['value']?></td>
        </tr>
      <? endif; ?>
    <? endforeach; ?>
  <? else: ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
</table>
<!-- finc: recordtab - description - END -->
