<!-- recordTab - HOLDINGSILS.phtml -->
<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

<? if ($offlineMode == "ils-offline"): ?>
  <div data-alert class="alert-box warning" tabindex="0" aria-live="assertive" role="alertdialog">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div data-alert class="alert-box info" tabindex="0" aria-live="assertive" role="alertdialog">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div data-alert class="alert-box info" tabindex="0" aria-live="assertive" role="alertdialog">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
<? endif; ?>
<? foreach ($holdings as $holding): ?>
  <h3>
    <? $locationText = $this->transEsc('location_' . $holding['location'], array(), $holding['location']); ?>
    <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
      <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
    <? else: ?>
      <?=$locationText?>
    <? endif; ?>
  </h3>
<table class="table">
  <caption class="sr-only"><?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?></caption>
  <? /* WE USE NO callNos here, next are th for availability and details - 04.16. CK */ ?>
  <tr>
    <th><?=$this->transEsc("Availability")?></th>
    <th><?=$this->transEsc("Details")?></th>
  </tr>
  <? /* WE USE NO callNos here - 04.16. CK */ ?>
  <? /* WE USE NO textFields, see rev #6237 - 04.16. CK */ ?>
  <? foreach ($holding['items'] as $row): ?>
    <?
    // AJAX Check record?
    $check = isset($row['check']) && $row['check'];
    $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
    $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
    // AJAX block record?
    $block = !$check && isset($row['addLink']) && $row['addLink'] === 'block';
    $blockStorageRetrievalRequest = !$checkStorageRetrievalRequest && isset($row['addStorageRetrievalRequestLink']) && $row['addStorageRetrievalRequestLink'];
    $blockILLRequest = !$checkILLRequest && isset($row['addILLRequestLink']) && $row['addILLRequestLink'];
    $checkEmailHold = (isset($row['checkEmailHold']) && $row['checkEmailHold']);    
    ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
    <tr vocab="http://schema.org/" typeof="Offer">
      <? /* WE USE NO Copy NOR on Reserve here but below, see rev #6237 - 04.16. CK */ ?>
      <td>
        <? if ($row['availability']): ?>
        <? /* Begin Available Items (Holds) */ ?>
        <span class="label success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
        <? else: ?>
        <? /* Begin Unavailable Items (Recalls) */ ?>
        <span class="label alert"><?=empty($row['status'])?$this->transEsc("Unavailable"):$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
        <? endif; ?>
      </td>
      <td>
        <? if ($row['reserve'] == "Y"): ?>
          <link property="availability" href="http://schema.org/InStoreOnly" />
          <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
        <? endif; ?>
        <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
          <span class="label secondary"><?=$this->transEsc("status_unknown_message")?></span>
        <? else: ?>
          <? /* WE USE callnumbers here, rev #6237 - 04.16. CK */ ?>
          <? if (isset($row['callnumber'])): ?>
            <span class="callnumber"><?=$this->transEsc("Call Number")?>: <?=$row['callnumber']?></span>
          <? endif; ?>
          <? if (isset($row['storage']) && $row['storage'] != 'Unknown'): ?>
            <span class="storage"><?=$this->transEsc("Location")?>: <?=$row['storage']?></span>
          <? endif; ?>

          <? if ($row['availability']): ?>
            <? /* Begin Available Items (Holds) */ ?>
            <? /* WE USE notes here, rev #6237 - 04.16. CK - item_notes below*/ ?>
            <? if (isset($row['notes'])): ?>
              <span class="notes"><?=$this->transEsc("Notes")?>:</span>
              <ul class="notes">
                <? foreach ($row['notes'] as $note): ?>
                  <li><?=$note?></li>
                <? endforeach; ?>

                <? foreach ($row['item_notes'] as $item_note): ?>
                  <li><?=$this->escapeHtml($item_note) ?></li>
                <? endforeach; ?>
              </ul>
            <? endif; ?>
            <? if (!$block && isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest ' : ''?>inlineblock placehold hide-for-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
            <? endif; ?>
            <? if (!$blockStorageRetrievalRequest && isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
            <? endif; ?>
            <? if (!$blockILLRequest && isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>" title="<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
            <? endif; ?>
            <? if (isset($row['emailHoldLink']) && $row['emailHoldLink']): ?>
              <a class="<?=$checkEmailHold ? 'checkEmailHold ' : ''?>modal-link placeEmailHold " data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['emailHoldLink'])?>" title="<?=$this->transEsc($checkEmailHold ? "EmailHold::email_hold_check_text" : "EmailHold::email_hold_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkEmailHold ? "EmailHold::email_hold_check_text" : "EmailHold::email_hold_place_text")?></a>
            <? endif; ?>
          <? else: ?>
            <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="label alert"><?=empty($row['status'])?$this->transEsc("Unavailable"):$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
            <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
            <? if (isset($row['duedate']) && $row['duedate']): ?>
              &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
            <? endif; ?>
            <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
              <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
            <? endif; ?>
            <? if (!$block && isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> inlineblock placehold hide-for-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
            <? endif; ?>
            <? endif; ?>
            <? if (isset($row['item_notes'])): ?>
              <div class="item-notes">
                <strong><?=$this->transEsc("Item Notes")?>:</strong>
                <ul>
                  <? foreach ($row['item_notes'] as $item_note): ?>
                    <li><?=$this->escapeHtml($item_note) ?></li>
                  <? endforeach; ?>
                </ul>
              </div>
          <? endif; ?>
        <? endif; ?>
        <? /* Embed item structured data: library, barcode, call number */ ?>
        <? if ($row['location']): ?>
          <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
        <? endif; ?>
        <? if ($row['barcode']): ?>
          <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
        <? endif; ?>
        <? if ($row['callnumber']): ?>
          <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
        <? endif; ?>
        <? /* Declare that the item is to be borrowed, not for sale */ ?>
          <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
          <link property="itemOffered" href="#record" />
      </td>
    </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
<!-- recordTab - HOLDINGSILS.phtml end -->