<!-- finc: ajax - resolverlinks -->
<div>
  <? /* finc-specific change #8447 - CK */ ?>
  <? $noResolverContent = true; ?>
  <? if (!empty($this->electronic)): ?>
    <? $noResolverContent = false; ?>
  <? /* finc-specific change #8447 - END */ ?>
    <div class="openurls">
      <? /*<strong><?=$this->transEsc('Electronic')?></strong>*/ ?>
      <ul>
        <? foreach ($this->electronic as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <? /* finc-specific change #7986 - CK - traffic light */ ?>
              <div <? if(!empty($link['access'])): ?> data-toggle="tooltip" title="<?=$this->transEsc('resolver_link_access_'.$link['access'])?>" class="traffic-light access-<?=$link['access']?>"<? endif;?>>
                <span class="first"></span>
                <span class="second"></span>
                <span class="last"></span>
              </div>
              <? /* finc-specific change #7986 - END */ ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a> <br />
              <? /* finc-specific change #5334 - CK */ ?>
              <small><?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?><?=isset($link['coverageHref'])?' <a href="'.$link['coverageHref'].'" target="_blank">'.$this->translate('Readme').'</a>':''?></small>
              <? /* finc-specific change #5334 - END */ ?>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?> <?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?>
            <? endif; ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>

  <? /* finc-specific change - commented out in #7643 - CK */ ?>
  <? /*
 <? if (!empty($this->print)): ?>
    <? $noResolverContent = false; ?>
    <div class="openurls">
      <strong><?=$this->transEsc('Holdings')?></strong>
      <ul>
        <? foreach ($this->print as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a> <?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?> <?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?>
            <? endif; ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>
  <div class="openurls">
    <strong><a href="<?=$this->escapeHtmlAttr($this->openUrlBase)?>?<?=$this->escapeHtmlAttr($this->openUrl)?>"><?=$this->transEsc('More options')?></a></strong>
    <? if (!empty($this->services)): ?>
      <ul>
        <? foreach ($this->services as $link): ?>
          <? if (!empty($link['href'])): ?>
            <li>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            </li>
          <? endif; ?>
        <? endforeach; ?>
      </ul>
    <? endif; ?>
  </div>
  */ ?>
  <? /* finc-specific change - commented out in #7643 - END */ ?>

  <? /* finc-specific change #9274 - CK */ ?>
  <? if ($noResolverContent): // no content to show, so tell the user ?>
    <span id="noResolverContentMessage" style="display: none"><?=$this->resolver . ': ' . $this->translate('no_resolver_links')?></span>
    <script>if ($('#urlsHideable').length) { $('#urlsHideable').show(); } else { $('#noResolverContentMessage').show(); }</script>
  <? endif; ?>
  <? /* finc-specific change #9274 - END */ ?>
</div>
<!-- finc: ajax - resolverlinks - END -->
