<!-- ajax - resolverlinks.phtml -->
<div>
  <? $noResolverContent = true; ?>
  <? if (!empty($this->electronic)): ?>
    <? $noResolverContent = false; ?>
    <div class="openurls">
      <? /*<strong><?=$this->transEsc('Electronic')?></strong>*/ ?>
      <ul class="no-bullet">
        <? foreach ($this->electronic as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <div <? if(!empty($link['access'])): ?> data-tooltip aria-haspopup="true" data-options="disable_for_touch:true;touch_close_text:'<?= $this->transEsc('Tap to close')?>'" title="<?=$this->transEsc('resolver_link_access_'.$link['access'])?>" class="has-tip traffic-light access-<?=$link['access']?>"<? endif;?>>
                <span class="first"></span>
                <span class="second"></span>
                <span class="last"></span>
              </div>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a> <br />
              <small><?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?><?=isset($link['coverageHref'])?' <a href="'.$link['coverageHref'].'" target="_blank">'.$this->translate('Readme').'</a>':''?></small>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?> <?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?>
            <? endif; ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>
  <? /**<? if (!empty($this->print)): ?>
    <? $noResolverContent = false; ?>
    <div class="openurls">
      <strong><?=$this->transEsc('Holdings')?></strong>
      <ul class="no-bullet">
        <? foreach ($this->print as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <div <?=!empty($link['access'])?' class="traffic-light access-'.$link['access'].'"':''?>> <span class="first"></span> <span class="second"></span> <span class="last"></span> </div><a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a> <br /><small><?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?><?=isset($link['coverageHref'])?' <a href="'.$link['coverageHref'].'" target="_blank">'.$this->translate('Readme').'</a>':''?></small>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?> <?=isset($link['coverage'])?$this->escapeHtml($link['coverage']):''?>
            <? endif; ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>
  <div class="openurls">
    <strong><a href="<?=$this->escapeHtmlAttr($this->openUrlBase)?>?<?=$this->escapeHtmlAttr($this->openUrl)?>"><?=$this->transEsc('More options')?></a></strong>
    <? if (!empty($this->services)): ?>
      <ul class="no-bullet">
        <? foreach ($this->services as $link): ?>
          <? if (!empty($link['href'])): ?>
            <li>
              <div <?=!empty($link['access'])?' class="traffic-light access-'.$link['access'].'"':''?>> <span class="first"></span> <span class="second"></span> <span class="last"></span> </div><a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?>><?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            </li>
          <? endif; ?>
        <? endforeach; ?>
      </ul>
    <? endif; ?>
  </div> */ ?>
  <? if ($noResolverContent): // no content to show, so tell the user ?>
    <span><?=$this->resolver . ': ' . $this->translate('no_resolver_links')?></span>
  <? else: // content to show, so do javascript to properly render tooltips?>
    <script type="text/javascript">$(document).foundation('tooltip', 'reflow');</script>
  <? endif; ?>
</div>
<!-- ajax - resolverlinks.phtml - END -->