<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */


// Set page title.
  $this->headTitle($this->translate('Error'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

$this->layout()->breadcrumbs = '<li class="active">Error</li>';
?>

<div class="col-sm-12">
    <h1><?= $this->transEsc('An error has occurred') ?></h1>
    <h2><?= $this->transEsc($this->message) ?></h2>
    <?php if (isset($this->reason) && $this->reason): ?>
        <b><?= $this->transEsc('Message') ?>
        :</b> <?= $this->transEsc($this->reason) ?><?php endif; ?>
</div>
