<div class="alert alert-danger">
    <p><h3>Achtung!</h3></p>
    <p>Das Untergeschoss der Bibliothek ist bis auf Weiteres geschlossen.<br/>Bereitstellung und Ausleihe der dort aufgestellten Medien (Signaturen beginnend mit C – J und P – Y) sowie der Medien aus dem Magazinbereich ist nicht möglich.<br/>Bitte bestellen Sie diese Medien kostenfrei über die Fernleihe.
    </p>
    <p>Bitte nehmen Sie Kontakt mit uns auf, wenn Sie Medien aus diesem Bereich benötigen, damit wir versuchen können, alternative Lösungen zu finden.<br/>E-Mail: bibliothek(at)ph-gmuend.de<br/>Telefon: 07171 983-340</p>
</div>
