<div class="alert alert-danger">
    <p>Die Bibliothek ist nun im ehemaligen Arbeitsraum der Bibliothek zu finden!</p>
    <p>Ein Zugang zur "bisherigen" Bibliothek ist bis auf Weiteres nicht möglich. ALLE Medien müssen vorab über den OPAC bestellt werden. Bestellungen bis 12 Uhr werden am nächsten Öffnungstag bereitgestellt. Pro Tag sind max. 10 Bestellungen pro Person möglich.    </p>
    <p>! Aufgrund des hohen Bestellaufkommens sind Bestellungen, die am Wochenende eingehen, erst ab Dienstag abholbereit. !</p>
</div>