<div class="alert alert-danger">
    <p>Die Medien im Untergeschoss der Bibliothek (Signaturen beginnend mit C – J und P – Y) sind wieder verfügbar und können über den OPAC zur Abholung in der Bibliothek bestellt werden.</p>
    <p>Fernleihbestellungen auf Titel aus dem Bibliotheksbestand sind damit nicht mehr notwendig.</p>
    <p>Die Fernleihe ist wieder kostenpflichtig (1,50 € pro Bestellung) und auf Medien beschränkt, die nicht im Bibliotheksbestand vorhanden sind.</p>
</div>
