<h4>Im <strong>Katalog<sup>+</sup></strong> finden Sie:</h4>
<ul>
    <li>Bücher, Noten und Tonträger der Bibliothek</li>
    <li>sowie alle für Studierende und Lehrende verfügbaren digitalen Quellen.</li>
    <li>Einzelne Artikel aus Online-Lexika müssen weiterhin direkt über deren Homepage recherchiert werden (Link zum <a href="https://www.mgg-online.com/" target="_blank">MGG-Online</a>).</li>
</ul>