<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */


// Set page title.
use Zend\View\Helper\HeadScript;

$this->headTitle($this->translate('email_selected_favorites'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li><a href="' . $this->url('cart-home') . '">' . $this->transEsc('Cart') . '</a></li> '
    . '<li class="active">' . $this->transEsc('email_selected_favorites') . '</li>';
?>
<div class="col-sm-12">
    <h2><?= $this->transEsc('bookbag_email_selected') ?></h2>
    <?= $this->flashmessages() ?>
    <form class="form-cart-email" action="<?= $this->url('cart-email') ?>"
          method="post" name="bulkEmail">
        <?php foreach ($this->records as $current): ?>
            <input type="hidden" name="ids[]"
                   value="<?= $this->escapeHtmlAttr($current->getSourceIdentifier() . '|' . $current->getUniqueId()) ?>"/>
        <?php endforeach; ?>
        <div class="form-group">
            <label class="control-label"><?= $this->transEsc('Title') ?>: </label>
            <?php if (count($this->records) > 1): ?>
                <button type="button" class="btn btn-primary btn-xs hidden"
                        data-toggle="collapse" data-target="#itemhide">
                    <?= count($this->records) . ' ' . $this->transEsc('items') ?>
                </button>
                <div id="itemhide" class="collapse in">
                    <ul>
                        <?php foreach ($this->records as $current): ?>
                            <li><?= $this->escapeHtml($current->getBreadcrumb()) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php else: ?>
                <p class="form-control-static"><?= $this->records[0]->getBreadcrumb() ?></p>
            <?php endif; ?>
        </div>
        <?= $this->render('Helpers/email-form-fields.phtml') ?>
    </form>
    <?php
    $script = <<<JS
    $('button.btn.hidden').removeClass('hidden');
    $('#itemhide').removeClass('in');
JS;
    ?>
    <?= $this->inlineScript(HeadScript::SCRIPT, $script, 'SET') ?>
    <div class="nofloat"></div>
</div>