<?php
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

    // Set page title.
    $this->headTitle($this->translate('Export Favorites'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li><a href="' . $this->url('cart-home') . '">' . $this->transEsc('Cart') . '</a></li> '
    . '<li class="active">' . $this->transEsc('Export Favorites') . '</li>';
?>
<h2><?= $this->transEsc('Export Favorites') ?></h2>

<?= $this->flashmessages() ?>

<?php if (!empty($this->exportOptions)): ?>
    <form class="form-cart-export" method="post"
          action="<?= $this->url('cart-export') ?>" name="exportForm"
          title="<?= $this->transEsc('Export Items') ?>">
        <?php foreach ($this->records as $current): ?>
            <input type="hidden" name="ids[]"
                   value="<?= $this->escapeHtmlAttr($current->getSourceIdentifier() . '|' . $current->getUniqueId()) ?>"/>
        <?php endforeach; ?>
        <div class="form-group">
            <label class="control-label"><?= $this->transEsc('Title') ?>:</label>
            <?php if (count($this->records) > 1): ?>
                <button type="button" class="btn btn-primary btn-xs hidden"
                        data-toggle="collapse" data-target="#itemhide">
                    <?= count($this->records) . ' ' . $this->transEsc('items') ?>
                </button>
                <div id="itemhide" class="collapse in">
                    <ul>
                        <?php foreach ($this->records as $current): ?>
                            <li><?= $this->escapeHtml($current->getBreadcrumb()) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php else: ?>
                <?php /* <p class="form-control-static"><?=$this->records[0]->getBreadcrumb() ?></p> */ ?>
                <p class="form-control-static"><?= $this->records[0]->getTitle() ?></p>
            <?php endif; ?>
        </div>
        <div class="form-group">
            <label for="format"
                   class="control-label"><?= $this->transEsc('Format') ?>:</label>
            <select name="format" id="format" class="form-control">
                <?php $firstOption = null; ?>
                <?php foreach ($this->exportOptions as $exportOption): ?>
                    <?php if ($firstOption == null) $firstOption = $exportOption; ?>
                    <option value="<?= $this->escapeHtmlAttr($exportOption) ?>"<?php if ($this->export()->needsRedirect($exportOption)): ?> data-redirect<?php endif; ?>><?= $this->transEsc($this->export()->getLabelForFormat($exportOption)) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <input class="export btn btn-primary" type="submit" name="submit"
                   value="<?= $this->transEsc('Export') ?>"<?php if ($this->export()->needsRedirect($firstOption)): ?> data-lightbox-ignore<?php endif; ?>/>
        </div>
    </form>
<?php endif; ?>
<?php
$script = <<<JS
  $('button.btn.hidden').removeClass('hidden');
  $('#itemhide').removeClass('in');
  $('.export.btn').click(function exportButtonClick() {
    if (typeof $('#format option:selected').attr('data-redirect') !== 'undefined') {
      VuFind.modal('hide');
    }
  });
  $('#format').change(function exportFormatChange(e) {
    if (this.selectedOptions[0].getAttribute('data-redirect') === null) {
      $('.export.btn').removeAttr('data-lightbox-ignore');
      $('form[name=exportForm]').removeAttr('target');
    } else {
      $('.export.btn').attr('data-lightbox-ignore', '1');
      $('form[name=exportForm]').attr('target', this.selectedOptions[0].value + 'Main');
    }
  }).trigger('change');
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
