<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
   <div class="col-xs-4 col-sm-3 col-xs-offset-4 col-sm-offset-0 pull-right-sm" >
    <?
        $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', '#');
        $cover = $coverDetails['html'];
        $thumbnail = false;
        $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
        if ($cover): ?>
            <? if ($coverDetails['html'] !== ''): ?> 
                <?=$cover ?>
            <? endif; ?>
        <? else: ?>
            <div class="recordcover unavailable <?=$this->mapper()->mapIcon($this->driver->getFormats())?>">     
                <span class=""></span>
            </div>
        <? endif; ?>   
    </div>
    
    <div class="col-xs-12 col-sm-9">        
        <div class="media-body">

    <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

    <?php if(!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>

</div>
