<div class="row" vocab="http://schema.org/" resource="#record">
    <div class="col-xs-10 col-sm-3 pull-right">
        <?php /* Display thumbnail if appropriate: */ ?>
        <?php $formats = $this->driver->getFormats();

           $format = array_shift($formats);
           //$this->format = $this->mapper()->mapIcon($format);
        ?>
        <?php $mediumThumb = $this->record($this->driver)->getThumbnail('medium');
           $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
        <?php if ($mediumThumb): ?>
          <?php if ($largeThumb): ?>
          <a class="modal-popup cover" data-toggle="modal" href="#" data-img-url="<?=$this->escapeHtmlAttr($largeThumb);?>" data-title="<?= $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection()) ?>">
          <?php endif; ?>
            <img alt="" class="recordcover <?=$this->
                  mapper()->mapIcon($this->driver->getFormats())?>" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <?php else: ?>
           <?=$this->render('RecordDriver/SolrDefault/parts/cover.phtml')?>
        <?php endif; ?>
        <?php if ($largeThumb): ?>
          </a>
        <?php endif; ?>

        <?php /* Display qrcode if appropriate: */ ?>
        <?php $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
        <?php if ($QRCode): ?>
          <span class="hidden-xs">
            <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
          </span>
        <?php endif; ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
  <div class="col-xs-12 col-sm-9">
      <?php
       $title = $this->driver->getTitle();
       $subtitle = $this->driver->getTitleSection();
    ?>
    <h3 property="name">
    <?=$this->escapeHtml($title)?> <small><?=$this->string()->cleanEsc($subtitle)?></small></h3>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?/* Display Main Details */?>

    <table class="table table-striped">
      <?php $container = $this->driver->tryMethod('getContainer'); if (count($container) > 0) : ?>
      <tr>
          <th><?=$this->transEsc('collective_editions')?>:</th>
          <td>
              <?php foreach ($container as $cont): ?>
              <a class="internal" href="<?=$this->RecordLink()->getUrl($cont, $this->overrideRecordLink)?>"><?=$this->string()->cleanEsc($cont->getTitle())?></a><br/>
              <?php endforeach; ?>
          </td>
      </tr>
      <?php endif; ?>

      <?php $journalTitle = $this->driver->getContainerTitle();
      if (is_array($journalTitle)) {
          $journalTitle = array_shift($journalTitle);
      }
      if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <?=$this->string()->cleanEsc($journalTitle)?>
        </td>
      </tr>
      <?php endif; ?>

      <?php $journalIssue = $this->driver->getContainerIssue();
      if (!empty($journalIssue)): ?>
      <tr>
        <th><?=$this->transEsc('Issue')?>:</th>
        <td>
          <?=$this->string()->cleanEsc($journalIssue)?>
        </td>
      </tr>
      <?php endif; ?>

      <?php $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <?php if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <?php foreach ($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <?php endforeach; ?>
        </td>
      </tr>
      <?php endif; ?>

      <?php if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <?php foreach ($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <?php endforeach; ?>
        </td>
      </tr>
      <?php endif; ?>

      <?php $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <?php if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td property="author"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $authors['main'], $this->overrideRecordLink)?>"><?=$this->escapeHtml($authors['main'])?></a></td>
      </tr>
      <?php endif; ?>

      <?php if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td property="creator"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'], $this->overrideRecordLink)?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
      </tr>
      <?php endif; ?>

      <?php if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <?php $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $field, $this->overrideRecordLink)?>"><?=$this->escapeHtml($field)?></a></span><?php endforeach; ?>
        </td>
      </tr>
      <?php endif; ?>

      <?php if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
        <?php $institutes = $this->driver->getInstitutes() ?>
        <?php if (isset($institutes) && !empty($institutes)): ?>
            <tr>
                <th><?=$this->transEsc('Institute')?>: </th>
                <td property="institute">
                    <?php foreach ($institutes as $institute): ?>
                        <div>
                            <a class="author" href="<?=$this->record($this->driver)->getLink('institute', $institute, $this->overrideRecordLink)?>"><?=$this->transEsc($institute)?></a>
                        </div>
                    <?php endforeach; ?>
                </td>
            </tr>
        <?php endif; ?>
      <?php endif; ?>

      <?php if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
        <?php $documentLink = $this->driver->getDokumentLink(); if (!empty($documentLink)):?>
        <tr>
          <th><?=$this->transEsc('DocumentID')?>: </th>
          <td>
              <a href="<?=$documentLink['url']?>" class="external"><?=$this->escapeHtml($documentLink['desc'])?></a>
          </td>
        </tr>
        <?php endif; ?>
      <?php endif; ?>

      <?php if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
          <?php $copyright= $this->driver->getCopyright(); if (!empty($copyright)):?>
            <tr>
                <th><?=$this->transEsc('Rights')?>: </th>
                <td>
                    <?=$this->escapeHtml($copyright)?>
                </td>
            </tr>
          <?php endif; ?>
      <?php endif; ?>

      <?php $source = $this->driver->getSource(); if (!empty($source)):?>
        <tr>
          <th><?=$this->transEsc('Source')?>: </th>
          <td>
              <?=$this->escapeHtml($source)?>
          </td>
        </tr>
      <?php endif; ?>
      <?php $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td>
              <?php foreach ($this->mapper()->simplify($this->driver->getFormats()) as $format): ?>
              <span><?=$this->transEsc($format)?></span>
              <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>
      <?php $physical = $this->driver->getPhysicalDescriptions(); if (!empty($physical)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Physical Description')?>: </th>
      <td>
        <?php foreach ($physical as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>


      <?php
         $isbn = $this->driver->getCleanISBN();
         $issn = $this->driver->getCleanISSN();
         if (!empty($isbn)): ?>
      <tr>
          <th><?=$this->transEsc('ISBN')?></th>
          <td><?=$this->driver->getCleanISBN()?></td>

      </tr>
      <?php elseif (!empty($issn)): ?>
      <tr>
          <th><?=$this->transEsc('ISSN')?></th>
          <td><?=$this->driver->getCleanISSN()?></td>

      </tr>
      <?php endif; ?>

      <?php $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <?php foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <?php $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <?php endif; ?>
            <?php $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <?php endif; ?>
            </span>
            <?php $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <?php endif; ?>
            <br/>
          <?php endforeach; ?>
        </td>
      </tr>
      <?php endif; ?>

      <?php $relatedItems = $this->driver->tryMethod('getRelatedItems'); if (!empty($relatedItems)): ?>
      <tr>
        <th><?=$this->transEsc('Contains')?>: </th>
        <td>
            <ul>
            <?php foreach ($relatedItems as $item): ?>
                <li>
                    <?php if (isset($item['author']) && !empty($item['author'])): ?>
                        <span property="author"><?=$this->escapeHtml($item['author'])?>: </span>
                    <?php endif; ?>
                    <?php if (isset($item['title']) && !empty($item['title'])): ?>
                        <span property="title">
                        <?php if (isset($item['id']) && !empty($item['id'])): ?>
                            <a href="<?=$this->url('search-results')?>?lookfor=ctrlnum:%22(Horizon)<?= $item['id'];?>%22">
                                <?=$this->escapeHtml($item['title'])?>;
                            </a>
                        <?php else: ?>
                            <?=$this->escapeHtml($item['title'])?>;</a>
                        <?php endif; ?>
                        </span>
                    <?php endif; ?>
                    <?php if (isset($item['edition']) && !empty($item['edition'])): ?>
                        <span property="edition"><?=$this->escapeHtml($item['edition'])?></span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </td>
      </tr>
      <?php endif; ?>

      <?php $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <?php endif; ?>

      <?php $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <?php endif; ?>

      <?=$this->render('RecordDriver/SolrDefault/parts/series.phtml')?>
      <?=$this->render('RecordDriver/SolrDefault/parts/subjects.phtml')?>
      <?php
            $openUrl = $this->openUrl($this->driver, 'record');
            $openUrlActive = $openUrl->isActive();

            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <?php if (!empty($urls)): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <?php foreach ($urls as $current): ?>
            <a class="external" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->transEsc($current['desc'])?></a><br/>
          <?php endforeach; ?>
        </td>
      </tr>
      <?php endif; ?>

      <?=$this->render('RecordDriver/SolrDefault/parts/illbutton.phtml')?>
      <?php $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <?php if (!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <?php foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <?php endforeach; ?>
            <?php /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <?php foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <?php endforeach; ?>
            <?php endif; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
        <?php $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <?php if (count($tagList) > 0): ?>
                <?php $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<?php endforeach; ?>
              <?php else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <?php endif; ?>
            </div>
          </td>
        </tr>
      <?php endif; ?>
        <?php $abstract = $this->driver->tryMethod('getAbstract');
        if ($abstract): ?>
        <tr>
         <th><?=$this->transEsc('Abstract')?></th>
         <td><?=$this->escapeHtml($abstract)?></td>
        </tr>
         <?php endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
