<div class="row" vocab="http://schema.org/" resource="#record">
    <div class="col-xs-10 col-sm-3 pull-right">
        <? /* Display thumbnail if appropriate: */ ?>
        <? $formats = $this->driver->getFormats();
        
           $format = array_shift($formats);
           //$this->format = $this->mapper()->mapIcon($format);
        ?>
        <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); 
           $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
        <? if ($mediumThumb): ?>
          <? if ($largeThumb): ?>
          <a class="modal-popup cover" data-toggle="modal" href="#" data-img-url="<?=$this->escapeHtmlAttr($largeThumb);?>" data-title="<?= $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection()) ?>">
          <? endif; ?>
            <img alt="" class="recordcover <?=$this->
                  mapper()->mapIcon($this->driver->getFormats())?>" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>          
        <? else: ?>
           <?=$this->render('RecordDriver/SolrDefault/parts/cover.phtml')?>
        <? endif; ?>
        <? if ($largeThumb): ?>
          </a>
        <? endif; ?>        

        <? /* Display qrcode if appropriate: */ ?>
        <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
        <? if($QRCode): ?>
          <span class="hidden-xs">
            <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
          </span>
        <? endif; ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
  <div class="col-xs-12 col-sm-9">
      <?
       $title = $this->driver->getTitle();
       $subtitle = $this->driver->getTitleSection();
    ?>
    <h3 property="name">  
    <?=$this->escapeHtml($title)?> <small><?=$this->string()->cleanEsc($subtitle)?></small></h3>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    
    <table class="table table-striped">
      <? $container = $this->driver->tryMethod('getContainer'); if (count($container) > 0 ) : ?>
      <tr>
          <th><?=$this->transEsc('collective_editions')?>:</th>
          <td>
              <? foreach($container as $cont): ?>
              <a class="internal" href="<?=$this->RecordLink()->getUrl($cont, $this->overrideRecordLink)?>"><?=$this->string()->cleanEsc($cont->getTitle())?></a><br/>
              <? endforeach; ?>
          </td>
      </tr>
      <? endif; ?>
      
      <? $journalTitle = $this->driver->getContainerTitle(); 
      if (is_array($journalTitle)) {
         $journalTitle = array_shift($journalTitle);
      }
      if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <?=$this->string()->cleanEsc($journalTitle)?>
        </td>
      </tr>
      <? endif; ?>
      
      <? $journalIssue = $this->driver->getContainerIssue(); 
      if (!empty($journalIssue)): ?>
      <tr>
        <th><?=$this->transEsc('Issue')?>:</th>
        <td>
          <?=$this->string()->cleanEsc($journalIssue)?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td property="author"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $authors['main'], $this->overrideRecordLink)?>"><?=$this->escapeHtml($authors['main'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td property="creator"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'],  $this->overrideRecordLink)?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a class="author" href="<?=$this->record($this->driver)->getLink('author', $field,  $this->overrideRecordLink)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
        <? $institutes = $this->driver->getInstitutes() ?>
        <? if (isset($institutes) && !empty($institutes)): ?>
            <tr>
                <th><?=$this->transEsc('Institute')?>: </th>
                <td property="institute">
                    <? foreach ($institutes as $institute): ?>
                        <div>
                            <a class="author" href="<?=$this->record($this->driver)->getLink('institute', $institute, $this->overrideRecordLink)?>"><?=$this->transEsc($institute)?></a>
                        </div>
                    <? endforeach; ?>
                </td>
            </tr>
        <? endif; ?>
      <? endif; ?>

      <? if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
        <? $documentLink = $this->driver->getDokumentLink(); if (!empty($documentLink)):?>
        <tr>
          <th><?=$this->transEsc('DocumentID')?>: </th>
          <td>
              <a href="<?=$documentLink['url']?>" class="external"><?=$this->escapeHTML($documentLink['desc'])?></a>
          </td>
        </tr>
        <? endif; ?>  
      <? endif; ?>
      
      <? if ($this->driver instanceof \Bsz\RecordDriver\SolrNtrsoai):?>
          <? $copyright= $this->driver->getCopyright(); if (!empty($copyright)):?>
            <tr>
                <th><?=$this->transEsc('Rights')?>: </th>
                <td>
                    <?=$this->escapeHTML($copyright)?>
                </td>
            </tr>
          <? endif; ?>  
      <? endif; ?>

      <? $source = $this->driver->getSource(); if (!empty($source)):?>
        <tr>
          <th><?=$this->transEsc('Source')?>: </th>
          <td>
              <?=$this->escapeHTML($source)?>
          </td>
        </tr>
      <? endif; ?>  
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td>
              <? foreach($this->mapper()->simplify($this->driver->getFormats()) as $format): ?>
              <span><?=$this->transEsc($format)?></span>
              <? endforeach; ?>              
          </td>
        </tr>
      <? endif; ?>  
      <? $physical = $this->driver->getPhysicalDescriptions(); if (!empty($physical)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Physical Description')?>: </th>
      <td>
        <? foreach ($physical as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
      
      
      <?  
         $isbn = $this->driver->getCleanISBN(); 
         $issn = $this->driver->getCleanISSN();
         if (!empty($isbn)): ?>
      <tr>
          <th><?=$this->transEsc('ISBN')?></th>
          <td><?=$this->driver->getCleanISBN()?></td>
          
      </tr>
      <? elseif (!empty($issn)): ?>
      <tr>
          <th><?=$this->transEsc('ISSN')?></th>
          <td><?=$this->driver->getCleanISSN()?></td>
          
      </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      
      <? $relatedItems = $this->driver->tryMethod('getRelatedItems'); if (!empty($relatedItems)): ?>
      <tr>
        <th><?=$this->transEsc('Contains')?>: </th>
        <td>
            <ul>
            <? foreach ($relatedItems as $item): ?>
                <li>
                    <? if (isset($item['author']) && !empty($item['author'])): ?>
                        <span property="author"><?=$this->escapeHtml($item['author'])?>: </span>
                    <? endif; ?>
                    <? if (isset($item['title']) && !empty($item['title'])): ?>
                        <span property="title">
                        <? if (isset($item['id']) && !empty($item['id'])): ?>
                            <a href="<?=$this->url('search-results')?>?lookfor=ctrlnum:%22(Horizon)<?= $item['id'];?>%22">
                                <?=$this->escapeHtml($item['title'])?>;
                            </a>
                        <? else: ?>
                            <?=$this->escapeHtml($item['title'])?>;</a> 
                        <? endif; ?>
                        </span>               
                    <? endif; ?>
                    <? if (isset($item['edition']) && !empty($item['edition'])): ?>
                        <span property="edition"><?=$this->escapeHtml($item['edition'])?></span>
                    <? endif; ?>
                </li>
            <? endforeach; ?>
            </ul>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>
     
      <?=$this->render('RecordDriver/SolrDefault/parts/series.phtml')?>
      <?=$this->render('RecordDriver/SolrDefault/parts/subjects.phtml')?>
      <?
            $openUrl = $this->openUrl($this->driver, 'record');
            $openUrlActive = $openUrl->isActive();
            
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls)): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a class="external" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->transEsc($current['desc'])?></a><br/>
          <? endforeach; ?>          
        </td>
      </tr>
      <? endif; ?>
      
      <?=$this->render('RecordDriver/SolrDefault/parts/illbutton.phtml')?>
      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
        <? $abstract = $this->driver->tryMethod('getAbstract');
        if ($abstract): ?>
        <tr>
         <th><?=$this->transEsc('Abstract')?></th>
         <td><?=$this->escapeHtml($abstract)?></td>
        </tr>
         <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
