<!-- recordDriver - solrMarc - CORE.phtml -->
<?
if($loggedin = $this->auth()->isLoggedIn()) {
  $user_id = $loggedin->id;
  $loggedin = true;
} else {
  $user_id = false;
}
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="medium-3 columns">
    <div class="text-center">
        <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? /* BOF - finc-specific StyleBasedIcons */ ?>
      <? elseif ($this->record($this->driver)->showStyleBasedIcons()): ?>
        <?=$this->record($this->driver)->getFormatIcon()?>
      <? /* EOF - finc-specific StyleBasedIcons */ ?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hide-for-small">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
    // from this area of the record view, this can be split into
    // getPreviewData() (should stay here) and
    // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="medium-9 columns">
  <? else: ?>
  <div class="medium-12 columns">
  <? endif; ?>

    <? /* For alle finc-records we want to get rid of trailing special chars in the title and limit its length to 100 chars */ ?>
    <h3 property="name"><?=$this->escapeHtml(preg_replace('/(\s[\/\.:]\s*)*$/', '', $this->truncate($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection(), 100)))?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hide alert-box info" data-alert tabindex="0" aria-live="assertive" role="alertdialog">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table">
      <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <?
          $containerSource = $this->driver->getSourceIdentifier();
          $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? /* finc specific rows - Start */ ?>
      <? $authors = $this->driver->getDeduplicatedAuthors(); if ((isset($authors['main']) && count($authors['main'])) || (isset($authors['secondary']) && count($authors['secondary'])) || (isset($authors['corporate']) && count($authors['corporate'])) || (isset($authors['corporate_secondary']) && count($authors['corporate_secondary']))): ?>
        <tr>
          <th><?=$this->transEsc('Authors/Corporations')?>: </th>
          <td>
            <? if (isset($authors['main']) && count($authors['main'])): ?>
              <? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['main_orig'][$author])?" / ".array_pop($authors['main_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['secondary']) && count($authors['secondary'])): ?>
              <?=count($authors['main'])?'; ':''?>
              <? $i = 0; foreach ($authors['secondary'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['secondary_orig'][$author])?" / ".array_pop($authors['secondary_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['corporate']) && count($authors['corporate'])): ?>
              <?=count($authors['main'])||count($authors['secondary'])?'; ':''?>
              <? $i = 0; foreach ($authors['corporate'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['corporate_orig'][$author])?" / ".array_pop($authors['corporate_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
            <? if (isset($authors['corporate_secondary']) && count($authors['corporate_secondary'])): ?>
              <?=count($authors['main'])||count($authors['secondary'])||count($authors['corporate'])?'; ':''?>
              <? $i = 0; foreach ($authors['corporate_secondary'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?><?=count($authors['corporate_secondary_orig'][$author])?" / ".array_pop($authors['corporate_secondary_orig'][$author]):''?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?></span><? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $titleDetails = $this->driver->getTitleDetails(); if (!empty($titleDetails)): ?>
        <tr>
          <th><?=$this->transEsc('Title')?>: </th>
          <td property="title">
            <? $i = 0; foreach ($titleDetails as $title): ?>
              <?=($i > 0 ? '<br />':'')?><?=$this->escapeHtml($title)?><? $i++ ;?>
            <? endforeach; ?>
          </td>
        </tr>
      <? else: ?>
        <tr>
          <th><?=$this->transEsc('Title')?>: </th>
          <td property="title"><?=$this->escapeHtml($this->driver->getShortTitle() . '  ' . $this->driver->getSubtitle() . '  ' . $this->driver->getTitleSection()) . ($this->driver->getTitleStatement() ? ' / ' . $this->driver->getTitleStatement() : '')?><br /><?=($this->driver->tryMethod('getTitleOrig') && $this->driver->getTitleOrig() != '' ? $this->escapeHtml($this->driver->getTitleOrig()) : '')?></td>
        </tr>
      <? endif; ?>

      <? /* finc only SolrMarc core specific changes - Start */ ?>
      <? $workPartTitleDetails = $this->driver->tryMethod('getWorkPartTitleDetails'); if (!empty($workPartTitleDetails)): ?>
        <tr>
          <th><?=$this->transEsc('Work Part Title')?>: </th>
          <td property="work part title">
            <? $i = 0; foreach ($workPartTitleDetails as $title): ?>
              <?=($i > 0 ? '<br />':'')?><?=$this->escapeHtml($title)?><? $i++ ;?>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $workTitleDetails = $this->driver->tryMethod('getWorkTitleDetails'); if (!empty($workTitleDetails)): ?>
        <tr>
          <th><?=$this->transEsc('Work Title')?>: </th>
          <td property="work title">
            <? $i = 0; foreach ($workTitleDetails as $title): ?>
              <?=($i > 0 ? '<br />':'')?><?=$this->escapeHtml($title)?><? $i++ ;?>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? /* finc only SolrMarc core specific changes - End */ ?>

      <? $titleUniform = $this->driver->getTitleUniform(); ?>
      <? if (!empty($titleUniform)): ?>
        <tr>
          <th><?=$this->driver->isRDA()?$this->transEsc('rda_original_title'):$this->transEsc('non_rda_original_title')?>: </th>
          <td><a href="<?=$this->record($this->driver)->getLink('title', $titleUniform)?>"><?=$this->escapeHtml($titleUniform)?></a></td>
        </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
        <tr>
          <th><?=$this->transEsc('Edition')?>: </th>
          <td property="bookEdition"><?=$this->escapeHtml($edition)?><? $editionOrig = $this->driver->getEditionOrig(); if (!empty($editionOrig)): ?><br /><?=$this->escapeHtml($editionOrig)?><? endif; ?></td>
        </tr>
      <? endif; ?>

      <? $dissertationNote = $this->driver->getDissertationNote(); if (!empty($dissertationNote)): ?>
        <tr>
          <th><?=$this->transEsc('Dissertation Note')?>: </th>
          <td><?=$dissertationNote?></td>
        </tr>
      <? endif; ?>
      <? /* finc specific rows - END */  ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <?
      $publications = $this->driver->getPublicationDetails();
      $pubDateSort = $this->driver->getPublishDateSort();
      if (!empty($publications)): ?>
        <tr>
          <th><?=$this->transEsc('Published')?>: </th>
          <td>
            <? foreach ($publications as $field): ?>
              <span property="publisher" itemtype="http://schema.org/Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                  <span itemprop="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
                <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                  <span itemprop="name"><?=$this->escapeHtml($pubName)?></span>
                <? endif; ?>
            </span>
              <? $pubDate = $field->getDate(); if (!empty($pubDateSort)): ?>
                <span property="datePublished"><?=$this->escapeHtml($pubDateSort)?></span>
              <? elseif (!empty($pubDate)): ?>
                <span property="datePublished"><?=$this->escapeHtml($pubDate)?></span>
              <? endif; ?>
              <br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $germanPrintsIndexNumber = $this->driver->getIndexOfGermanPrints(); if (!empty($germanPrintsIndexNumber)): ?>
        <tr>
          <th><?=$this->transEsc('German Prints Index Number')?>: </th>
          <td property="germanPrintsIndexNumber"><?=$this->escapeHtml($germanPrintsIndexNumber[0])?></td>
        </tr>
      <? endif; ?>

      <? /* finc specific row - replaces series - Start */ ?>
      <? $hierarchyParentTitle = $this->driver->getHierarchyParentTitle(); if (!empty($hierarchyParentTitle) && empty($series)): ?>
        <tr>
          <th><?=$this->transEsc('Set Multipart')?>: </th>
          <td>
            <? $hierarchyParentId = $this->driver->getHierarchyParentID(); ?>
            <? foreach ($hierarchyParentTitle as $key=>$hTitle): ?>
              <? if(isset($hierarchyParentId[$key])): ?><a href="<?=$this->recordLink()->getUrl($hierarchyParentId[$key])?>"><? endif; ?><?=$this->escapeHtml($hTitle)?><? if(isset($hierarchyParentId[$key])): ?></a><? endif; ?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? /* finc specific row - replaces series - End */ ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subject-line" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="right hide-for-print">
              <a class="tagRecord right" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" data-lightbox><i class="fa fa-plus"></i><?=$this->transEsc('Add Tag')?></a>
            </span>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* finc specific rows - Start */ ?>
      <? $subjects = $this->driver->getLocalSubject(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? $i = 0; foreach ($subjects as $field): ?>
              <?=($i++ == 0) ? '' : ', '?>
              <a title="<?=$this->escapeHtmlAttr($field)?>" href="<?=$this->record($this->driver)->getLink('subject', $field)?>" rel="nofollow"><?=trim($this->escapeHtml($field))?></a>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $megaCollection = (array) $this->driver->tryMethod('getMegaCollection'); if (!empty($megaCollection)): ?>
        <tr>
          <th><?=$this->transEsc('Source')?>: </th>
          <td>
            <? foreach ($megaCollection as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $otherRelationshipEntry = (array) $this->driver->tryMethod('getOtherRelationshipEntry'); if (!empty($otherRelationshipEntry)): ?>
        <? foreach ($otherRelationshipEntry as $key => $values): ?>
          <tr>
            <th><?=$this->transEsc($key)?>: </th>
            <td>
              <? foreach ($values as $value): ?>
                <? if (!empty($value['link']) && $recordLink = $this->RecordLink()->getRecordLink($value['link'], 'record_id')): ?>
                  <a href="<?=$recordLink?>"><?=$this->escapeHtml($value['text'])?></a><br/>
                <? else: ?>
                  <?=$this->escapeHtml($value['text'])?><br/>
                <? endif; ?>
              <? endforeach; ?>
            </td>
          </tr>
        <? endforeach; ?>
      <? endif; ?>

      <? $additionalNotes = (array) $this->driver->tryMethod('getAdditionalNotes'); if (!empty($additionalNotes)): ?>
        <tr>
          <th><?=$this->transEsc('Notes')?>: </th>
          <td>
            <? foreach ($additionalNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
      <? /* finc specific rows - End */ ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
<!-- recordDriver - solrMarc - CORE.phtml end -->