<!-- finc: RecordDriver - solrMarc - data-localSubjects -->
<? if (!(empty($data))): ?>
<? $i = 0; foreach ($data as $subject): ?>
    <?= ($i++ == 0) ? '' : ', '; ?>
    <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow">
        <?=trim($this->escapeHtml($subject))?>
    </a>
<? endforeach; ?>
<? endif; ?>
<!-- finc: RecordDriver - solrMarc - data-localSubjects - END -->
