<!-- finc: RecordDriver - solrMarc - data-linkviafincid -->
<? if (!empty($data)): ?>
<? foreach($data as $field): ?>
    <? if (isset($field['id']) || isset($field['text'])):
        $url = isset($field['id'])
            ? $this->url('record').$field['id']
            : $this->record($this->driver)->getLink('title', $field['text']);
        ?>
        <? if (isset($field['pretext']) && !empty($field['pretext'])): ?>
            <?=$this->escapeHtml($field['pretext'])?>:
        <? endif; ?>
        <a href="<?=$url?>"><?=$this->escapeHtml($field['text'])?></a><br/>
    <? else: ?>
        <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
    <? endif; ?>
<? endforeach; ?>
<? endif; ?>
<!-- finc: RecordDriver - solrMarc - data-linkviafincid - END -->
