
<div>
    <a target="_blank" href="https://verbundwiki.gbv.de/display/VZG/K10plus-Zentral">K10plus-Discovery</a> enthält ca. 207 Mio. Datensätze:<br/><br/>
</div>
    
<ul>
    <li>ca. 24,1 Millionen Nachweise der Bestände aller SWB-Bibliotheken (<a target="_blank" href="http://swb.bsz-bw.de/DB=2.1/" rel="nofollow">Südwestdeutscher Bibliotheksverbund</a>)</li>    
    <li>ca. 45,7 Millionen Nachweise der Bestände aller GBV-Bibliotheken (der GBV Gesamtkatalog <a target="_blank" href="https://gso.gbv.de/DB=2.1/" rel="nofollow">GVK</a>)</li>
    <li>ca. 49,9 Millionen Aufsätze aus über 27.900 Zeitschriften aus den <a target="_blank" href="http://www.gbv.de/benutzer/datenbanken/ssg" rel="nofollow">Online Contents Daten (OLC)</a> mit Besitznachweisen aus der <a target="_blank" href="http://www.zeitschriftendatenbank.de/" rel="nofollow">ZDB</a></li>
    <li>ca. 29,0 Millionen Aufsätze aus <a target="_blank" href="http://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.FAQs" rel="nofollow">PubMed / Medline</a></li>
    <li>ca. 23,2 Millionen digitale Objekte und bibliographischen Nachweise aus den <a target="_blank" href="http://www.nationallizenzen.de/" rel="nofollow">Nationallizenzen</a></li>
    <li>ca. 12,3 Mio. Nachweise aus JSTOR</li>
    <li>ca. 6,3 Millionen Aufsätze aus Springer E-Journals</li>
    <li>ca. 5,5 Datensätze Datenbank TEMA® Technik und Management des <a target="_blank" href="https://www.wti-frankfurt.de/">WTI-Frankfurt eG</a> </li>
    <li>ca. 3,7 Millionen Nachweise des Verbundkatalogs Öffentlicher Bibliotheken (ÖVK)</li>
    <li>ca. 3,7 Millionen Artikel und Zeitschriften aus dem Directory of Open Access Journals (<a target="_blank" href="http://www.doaj.org/" rel="nofollow">DOAJ</a>)</li>
    <li>ca. 288.000 klinische Studien aus der Datenbank <a target="_blank" href="http://clinicaltrials.gov/" rel="nofollow">ClinicalTrials.gov</a></li>
    <li>ca. 45.000 eBooks aus dem <a target="_blank" href="http://www.gutenberg.org" rel="nofollow">Projekt Gutenberg</a></li>
</ul>

<div>
    Bei technischen Fragen und Anregungen: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</div>

<div>
    Ein Projekt zum Aufbau einer gemeinsamen Infrastruktur des <a target="_blank" href="https://www.bsz-bw.de">Bibliotheksservice-Zentrums Baden-Württemberg</a> (BSZ) und der <a target="_blank" href="https://www.gbv.de/Verbundzentrale">Verbundzentrale des GBV</a>.<br/><br/>
</div>
