
<div>
    <a target="_blank" href="https://verbundwiki.gbv.de/display/VZG/K10plus-Zentral">K10plus-Discovery</a> contains some 207 million records:<br/><br/>
</div>
    
<ul>
    <li>ca. 24,1 million holdings of SWB-Libraries (<a target="_blank" href="http://swb.bsz-bw.de/DB=2.1/" rel="nofollow">Südwestdeutscher Bibliotheksverbund</a>)</li>
    <li>ca. 45,7 million holdings of GBV-Libraries (the GBV Union Catalogue <a target="_blank" href="https://gso.gbv.de/DB=2.1/" rel="nofollow">GVK</a>)</li>
    <li>ca. 49,9 million articles from more than 27.900 journals out of  <a target="_blank" href="http://www.gbv.de/benutzer/datenbanken/ssg" rel="nofollow">Online Contents Repository (OLC)</a> including <a target="_blank" href="http://www.zeitschriftendatenbank.de/" rel="nofollow">ZDB</a> data</li>
    <li>ca. 29,0 million articles from <a target="_blank" href="http://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.FAQs" rel="nofollow">PubMed / Medline</a></li>
    <li>ca. 23,2 million digital objects and metadata from <a target="_blank" href="http://www.nationallizenzen.de/" rel="nofollow">Nationwide Licensed Material</a></li>
    <li>ca. 12,3 Mio. items from JSTOR</li>
    <li>ca. 6,3 million articles from Springer E-Journals</li>
    <li>ca. 5,4 Records from database TEMA® Technik und Management of <a target="_blank" href="https://www.wti-frankfurt.de/">WTI-Frankfurt eG</a></li>
    <li>ca. 3,7 million holdings from public libraries (ÖVK)</li>
    <li>ca. 3,7 million articles and journals from the Directory of Open Access Journals (<a target="_blank" href="http://www.doaj.org/" rel="nofollow">DOAJ</a>)</li>
    <li>ca. 288.000 clinical studies from the <a target="_blank" href="http://clinicaltrials.gov/" rel="nofollow">ClinicalTrials.gov</a> database</li>
    <li>ca. 45.000 eBooks from the <a target="_blank" href="http://www.gutenberg.org" rel="nofollow">Gutenberg Project</a></li>
</ul>

<div>
    Do you have any technical questions or proposals? Please mail to: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</div>

<div>
    A project to build a joint infrastructure by <a target="_blank" href="https://www.bsz-bw.de">SWB Library Network</a> (BSZ) and  <a target="_blank" href="https://www.gbv.de/Verbundzentrale">GBV Library Network</a> (GBV).<br/><br/>
</div>
