<hr/>
<div class="row">
    <div class="graybg clearfix">
        <?php
        $count = $this->client()->get('Footer')->get('boxes');
        for ($i = 1; $i <= $count; $i++) {
            if ($this->client()->get('FooterBox' . $i) !== null) {
                echo $this->partial('bsz/well.phtml', [
                    'count' => $count,
                    'settings' => $this->client()->get('FooterBox' . $i)
                ]);
            }
        }
        ?>
    </div>

</div>
<div class="row lastline">
    <small class="pull-left"><?php if ($this->client()->is('show_bw_logo')): ?><img
            src="<?= $this->imageLink('bw.svg') ?>" alt="Baden-Württemberg"
            style="width: 32px; padding-bottom: 3px;"/><?php endif ?><?= $this->transEsc('footer_custom_text') ?>
    </small>
    <small class="pull-right" role="contentinfo"><a
            href="https://wiki.bsz-bw.de/display/BOSS/Roadmap"
            class="external"><?= $this->escapeHtml($this->client()->getVersion()) ?></a>
        &copy; <?= date('Y') ?> <a href="https://www.bsz-bw.de"
                                   class="external hasicon">BSZ</a>
        powered by <a href="https://vufind.org" class="external">VuFind</a> 6, <a
            href="https://www.agv-gvi.de/" class="external">GVI</a>, Covers
        &copy; <a href="https://Buchhandel.de" class="external">Buchhandel.de</a>
    </small>
</div>
