<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Call Number')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <?php $count = 0; foreach ($this->statusItems as $item): ?>
    <?php if ($count++ == 5) {
    break;
} // Show no more than 5 items?>
        <?php $class = 'text-success';
        $icon = 'fa-check';
        if ($item['availability'] == false) {
            $class = "text-danger";
            $icon = 'fa-times';
        }

        $message = '';
        if (isset($item['message']) && is_array($item['message']) && array_key_exists('en', $item['message'])) {
            $message = isset($item['message'][$this->layout()->userLang]) ? $item['message'][$this->layout()->userLang] : $item['message']['en'];
        }
    ?>
    <tr>
      <td class="fullLocation">
        <?php $locationText = $this->transEsc('location_' . $item['location'], [], $item['location']); ?>
        <?php if (isset($item['locationhref']) && $item['locationhref']): ?>
          <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
      </td>
      <td class="fullCallnumber">
        <?php if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($item['callnumber']) ?>"><?=$this->escapeHtml($item['callnumber'])?></a>
        <?php else: ?>
          <span><?= preg_replace('/^.*\s\|\s/', '', $this->string()->cleanEsc($item['callnumber'])); ?></span>
        <?php endif; ?>
      </td>
      <td class="fullAvailability">
        <?php if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
         <span class="text-nowrap">
             <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
             <?=$this->transEsc("status_unknown_message")?>
         </span>
        <?php elseif ($item['availability']): ?>
          <span class="text-success text-nowrap">
            <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
            <?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?>
          </span>
        <?php elseif (strtolower($item['status']) === "on loan"): ?>
            <span class="text-danger text-nowrap">
                <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
                <?=$this->transEsc("On loan")?>
            </span>
            <?php if (isset($item['duedate']) && $item['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($item['duedate'])?></span>
            <?php endif; ?>
        <?php else: ?>
          <span class="text-danger text-nowrap">
            <i class="fa <?=$this->escapeHtmlAttr($icon)?> <?=$class?>"></i>
            <?=$this->escapeHtml($message)?>
          </span>
        <?php endif; ?>
      <?php if ($this->client()->is('hold_links_result_list')): ?>
           <br/>
            <?php // no idea why this is necessary here?>
            <?php $item['ilslink'] = str_replace('SOPAC', 'SMOPAC', $item['ilslink'])?>
            <?php $status = strtolower($item['status'])?>
            <?php if ($status == 'on loan' && !empty($duedate)): ?>
                <?=$this->transEsc('Due')?> <?=$this->escapeHtml($duedate)?>
                <?php if (!empty($item['ilslink']) && !$this->client()->is('only_one_holds_button')): ?>
                    &ndash;
                    <a class="open-popup" data-name="KIOSK" href="<?=$item['ilslink']?>"><?=$this->transEsc('Recall This')?></a>
                <?php endif; ?>
            <?php elseif ($status == 'unavailable'): ?>
                <?=$this->transEsc('daia-' . $status)?>
                <?php if (!empty($item['ilslink']) && !$this->client()->is('only_one_holds_button')): ?>
                    &ndash;
                    <a class="open-popup" data-name="KIOSK" href="<?=$item['ilslink']?>"><?=$this->transEsc('Recall This')?></a>
                <?php endif; ?>
            <?php else: ?>
                <?=$this->transEsc('daia-' . $status)?>
                <?php if (!empty($item['ilslink']) && !$this->client()->is('only_one_holds_button') && $this->client()->is('always_place_hold') && (strtolower($item['status']) != 'for reference') || $this->client()->is('show_readingroom_link') && !$isStorageReadingroom) : ?>
                    &ndash;
                    <a class="open-popup" data-name="KIOSK" href="<?=$item['ilslink']?>"><?=$this->transEsc('Place a Hold')?></a>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
<?php if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', ['id' => $this->statusItems[0]['id']])?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more')?> ...</a></td></tr>
<?php endif; ?>
</table>
