<? $cart = $this->cart(); ?>
<? if ($cart->isActive()): ?>
  <? $cartId = $this->source . '|' . $this->id; ?>
  <li class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a href="#" class="btn cart-add hidden<? if(!$cart->contains($cartId)): ?> correct<? endif ?>">
      <i class="cart-link-icon fa fa-plus" title="<?=$this->transEsc('Add to Book Bag') ?>"></i><!--
   --><span class="cart-link-label"><?=$this->transEsc('Add to Book Bag') ?></span><!--
 --></a>
    <a href="#" class="btn cart-remove hidden<? if($cart->contains($cartId)): ?> correct<? endif ?>">
      <i class="cart-link-icon fa fa-times" title="<?=$this->transEsc('Remove from Book Bag') ?>"></i><!--
   --><span class="cart-link-label"><?=$this->transEsc('Remove from Book Bag') ?></span>
    </a>
  </li>
<? endif; ?>
