<div class="cover-container" <?php if (isset($this->cover)):?>data-cover="<?=$this->cover?><?php endif; ?>">
    <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
        <svg width="100%">
            <use href="/themes/bodensee/images/formats/sprite.svg#<?=$this->record($this->driver)->getFormatIcon()?>"/>
        </svg>
        <img class="hidden recordcover" alt="Cover image" />
    </a>
</div>
