<?php /* Display thumbnail if appropriate: */ ?>
<?php $formats = $this->driver->getFormats();


$icon = $this->mapper()->mapIcon($formats);
?>
<?php if ($cover): ?>
    <?php if ($this->link): ?>
        <a class="modal-popup cover" data-toggle="modal" href="#" data-img-url="<?= $this->escapeHtmlAttr($cover); ?>" data-title="title">
    <?php endif; ?>
    <img <?php if ($linkPreview): ?>data-linkpreview="true"
         <?php endif; ?>class="<?= $icon ?> img-responsive"
         src="<?= $this->escapeHtmlAttr($cover); ?>"/>
    <?php if ($this->link): ?>
        </a>
    <?php endif; ?>
<?php else: ?>
    <div class="unavailable <?= $this->mapper()->mapIcon($this->driver->getFormats()) ?> medium">
        <span class=""></span>
    </div>
<?php endif; ?>
