<div class="cover-container" <?php if (isset($this->cover)):?>data-cover="<?=$this->cover?><?php endif; ?>">
    <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg">
            <style type="text/css">
                svg {
                    max-width: 100px;
                    width: 100px;
                }
            </style>
            <use href="/themes/bodensee/images/formats/sprite.svg#<?=$this->record($this->driver)->getFormatIcon()?>"/>
        </svg>
        <img class="hidden recordcover" alt="Cover image" />
    </a>
</div>
