<?php /* Display thumbnail if appropriate: */ ?>
<?php $formats = $this->driver->getFormats();
/*
 * Copyright 2020 (C) Bibliotheksservice-Zentrum Baden-
 * Württemberg, Konstanz, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

$icon = $this->mapper()->mapIcon($formats);
?>
<?php if ($cover): ?>
    <?php if ($this->link): ?>
        <a class="modal-popup cover" data-toggle="modal" href="#" data-img-url="<?= $this->escapeHtmlAttr($cover); ?>" data-title="title">
    <?php endif; ?>
    <img <?php if ($linkPreview): ?>data-linkpreview="true"
         <?php endif; ?>class="<?= $icon ?> img-responsive"
         src="<?= $this->escapeHtmlAttr($cover); ?>"/>
    <?php if ($this->link): ?>
        </a>
    <?php endif; ?>
<?php else: ?>
    <div class="unavailable <?= $this->mapper()->mapIcon($this->driver->getFormats()) ?> medium">
        <span class=""></span>
    </div>
<?php endif; ?>
